# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
ZEN70 全局 Redis Key & Pub/Sub Channel 常量注册表。

法典 §1.2（IaC 唯一事实来源）：
所有 Redis 键名和 Pub/Sub 频道名必须从本模块导入使用，
严禁在业务代码中硬编码字符串。违反此规定将导致链路 1/9 类型的
键名不对齐脑裂，使探针/网关/路由三方永远无法通信。
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Pub/Sub Channels (频道名)
# ---------------------------------------------------------------------------

CHANNEL_SWITCH_EVENTS: str = "switch:events"
"""开关事件频道：网关发布 → 探针订阅执行容器操作。"""

CHANNEL_HARDWARE_EVENTS: str = "hardware:events"
"""硬件探测事件频道：探针发布 → SSE 推送前端。"""



CHANNEL_NODE_EVENTS: str = "node:events"
"""Node 控制面事件频道：注册/心跳/状态变更。"""

CHANNEL_JOB_EVENTS: str = "job:events"
"""Job 控制面事件频道：创建/拉取/完成/失败。"""

CHANNEL_CONNECTOR_EVENTS: str = "connector:events"
"""Connector 控制面事件频道：注册/触发/自检。"""


# ---------------------------------------------------------------------------
# Switch State Keys (开关状态键)
# ---------------------------------------------------------------------------

KEY_SWITCH_PREFIX: str = "switch:"
"""
网关侧开关状态哈希键前缀。
`set_switch()` 写入 HSET `switch:{name}` → 用于前端 `get_switch()` 读取当前状态。
"""

KEY_SWITCH_EXPECTED_PREFIX: str = "switch_expected:"
"""
探针侧期望状态键前缀。
探针收到 Pub/Sub 事件后写入 `switch_expected:{name}` → 调谐循环读取决定容器操作。
Caddy `routing_operator` 也从此键读取判定是否添加反向代理路由。
"""


# ---------------------------------------------------------------------------
# System-Level Guard Keys (系统级大闸键)
# ---------------------------------------------------------------------------

KEY_SYSTEM_READONLY_DISK: str = "zen70:disk:readonly"
"""
磁盘 95% 全局只读大闸标志。
disk_guardian 写入 → middleware global_readonly_lock 检查。
"""

KEY_SYSTEM_UPS_STATUS: str = "zen70:topology:ups"
"""
UPS 电源状态键。
thermal_ups_guardian 写入 → middleware global_readonly_lock 检查。
值为 'LOW_BATTERY_SHUTDOWN' 时触发全局只读。
"""


# ---------------------------------------------------------------------------
# Auth & Rate Limiting Keys (认证与限流键)
# ---------------------------------------------------------------------------

KEY_HW_PREFIX: str = "hw:"
"""硬件缓存键前缀。"""

KEY_LOCK_PREFIX: str = "lock:"
"""通用互斥锁键前缀。"""

KEY_AUTH_CHALLENGE_PREFIX: str = "auth:challenge:"
"""WebAuthn Challenge 存储键前缀。"""

KEY_DB_MIGRATION_LOCK: str = "zen70:DB_MIGRATION_LOCK"
"""Alembic DDL 迁移全局互斥锁键。"""

KEY_INVITE_TOKEN_PREFIX: str = "zen70:invite:"
"""带外邀请 Token 存储键前缀。"""


# ---------------------------------------------------------------------------
# Capabilities & Topology Keys (能力矩阵与拓扑键)
# ---------------------------------------------------------------------------

KEY_CAPABILITIES_PREFIX: str = "zen70:capability:"
"""能力矩阵缓存键前缀。"""

KEY_DISK_TAINT: str = "zen70:taint:disk_pressure"
"""磁盘压力污点标志键。"""
