"""
ZEN70 性能监控组件 (法典 4.0 & 7.0 契约)
========================================
负责收集系统内核心 API 的 P99 延迟与并发活跃连接数。
数据格式兼容 Prometheus，供网关 Categraf SRE 探针主动拉取。

@generated by ZEN70-AI-Agent
"""

import time
from typing import Any, Awaitable, Callable

from fastapi import Request, Response
from prometheus_client import Counter, Gauge, Histogram

# ---------------------------------------------------------------------------
# SRE 指标定义
# ---------------------------------------------------------------------------

API_REQUESTS_TOTAL = Counter(
    "zen70_api_requests_total",
    "Total HTTP requests handled by the FastAPI application",
    ["method", "endpoint", "status"],
)

API_REQUEST_DURATION = Histogram(
    "zen70_api_request_duration_seconds",
    "HTTP request duration in seconds (Target P99 <= 500ms)",
    ["method", "endpoint"],
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

ACTIVE_CONNECTIONS = Gauge(
    "zen70_sse_active_connections",
    "Number of active HTTP/SSE connections currently handled by the server",
)


def _normalize_endpoint_label(request: Request, raw_path: str) -> str:
    scope: Any = getattr(request, "scope", None)
    if isinstance(scope, dict):
        route = scope.get("route")
        route_path = getattr(route, "path", None)
        if isinstance(route_path, str) and route_path.strip():
            return route_path
    segments = [part for part in raw_path.split("/") if part]
    normalized: list[str] = []
    for part in segments:
        token = part.strip()
        if not token:
            continue
        if token.isdigit() or len(token) >= 16:
            normalized.append(":id")
            continue
        normalized.append(token)
    return "/" + "/".join(normalized)


async def metrics_middleware(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """
    轻量级 FastAPI Prometheus 中间件。
    记录耗时、状态码及并发活跃连接，免疫超时脑裂。
    """
    path = request.url.path
    # 忽略单纯拉取监控的接口，防止指标自旋爆炸
    if path == "/metrics" or path == "/api/v1/health":
        return await call_next(request)

    method = request.method
    endpoint_label = _normalize_endpoint_label(request, path)

    # 锁定活跃连接，支持防脑裂挂盘观测
    ACTIVE_CONNECTIONS.inc()
    start_time = time.perf_counter()

    try:
        response = await call_next(request)
        status = str(response.status_code)
    except (OSError, ValueError, KeyError, RuntimeError, TypeError) as e:
        status = "500"
        raise e
    finally:
        ACTIVE_CONNECTIONS.dec()
        duration = time.perf_counter() - start_time

        # 记录指标
        API_REQUESTS_TOTAL.labels(method=method, endpoint=endpoint_label, status=status).inc()
        API_REQUEST_DURATION.labels(method=method, endpoint=endpoint_label).observe(duration)

    return response
