# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
"""
ZEN70 Gateway API (FastAPI) entry module.

Owns the public control-plane HTTP surface, SSE events, health checks,
Request-ID propagation, and router / lifecycle wiring.
"""

from __future__ import annotations

import asyncio
import importlib
import json
import os
import re
import signal
import time
import uuid
from collections.abc import Awaitable, Callable, Sequence
from contextlib import asynccontextmanager
from typing import cast

from fastapi import APIRouter, FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.responses import Response

from backend.api import alerts as alerts_router
from backend.api import audit_logs as audit_logs_router
from backend.api import auth as auth_router
from backend.api import connectors as connectors_router
from backend.api import console as console_router
from backend.api import evaluations as evaluations_router
from backend.api import extensions as extensions_router
from backend.api import jobs as jobs_router
from backend.api import kernel as kernel_router
from backend.api import node_approval as node_approval_router
from backend.api import nodes as nodes_router
from backend.api import permissions as permissions_router
from backend.api import profile as profile_router
from backend.api import quotas as quotas_router
from backend.api import reservations as reservations_router
from backend.api import routes
from backend.api import scheduling_governance as scheduling_governance_router
from backend.api import sessions as sessions_router
from backend.api import settings as settings_router
from backend.api import triggers as triggers_router
from backend.api import user_management as user_management_router
from backend.api import workflows as workflows_router
from backend.api.deps import get_settings
from backend.api.models import ErrorResponse, HealthResponse
from backend.core.extension_sdk import bootstrap_extension_runtime
from backend.core.gateway_profile import get_enabled_router_names as resolve_enabled_router_names
from backend.core.gateway_profile import (
    normalize_gateway_pack_keys,
    normalize_gateway_profile,
)
from backend.core.redis_client import RedisClient, get_logger
from backend.core.runtime_support import connect_redis_with_retry
from backend.core.version import get_runtime_version
from backend.middleware import RequestIDMiddleware, global_readonly_lock, limit_request_body

# -------------------- Logging --------------------
logger = get_logger("api")

# Kernel admission control: only these optional routers are allowed in default kernel runtime.
# Pack declarations in pack_registry.py define capability contracts, NOT automatic runtime admission.
KERNEL_ALLOWED_OPTIONAL_ROUTERS = {"cluster"}

OPTIONAL_ROUTER_MODULES = {
    "cluster": "backend.api.cluster",
    "health": "backend.api.health",
    "search": "backend.api.search",
}


def get_gateway_profile() -> str:
    return normalize_gateway_profile(os.getenv("GATEWAY_PROFILE", "gateway-kernel"))


def get_gateway_packs() -> tuple[str, ...]:
    return normalize_gateway_pack_keys(
        os.getenv("GATEWAY_PACKS", ""),
        profile=os.getenv("GATEWAY_PROFILE", "gateway-kernel"),
    )


def get_enabled_router_names(profile: str) -> tuple[str, ...]:
    raw_packs = os.getenv("GATEWAY_PACKS", "")
    selected_packs = normalize_gateway_pack_keys(raw_packs, profile=profile) if raw_packs else None
    return resolve_enabled_router_names(profile, selected_packs=selected_packs)


def _load_optional_router(name: str) -> APIRouter:
    module = importlib.import_module(OPTIONAL_ROUTER_MODULES[name])
    router = getattr(module, "router", None)
    if not isinstance(router, APIRouter):
        raise TypeError(f"Optional router '{name}' is missing a valid APIRouter")
    return router


# -------------------- PostgreSQL health check --------------------
async def _check_postgres_async(dsn: str | None) -> str:
    """Health check: prefer SELECT 1 and fallback to TCP connectivity."""
    # Prefer the shared async session factory so the health check stays aligned
    # with runtime DB configuration before falling back to raw TCP.
    try:
        from backend.db import _async_session_factory

        if _async_session_factory:
            from sqlalchemy import text

            async with _async_session_factory() as session:
                await session.execute(text("SELECT 1"))
            return "ok"
    except (ImportError, OSError, ValueError, KeyError, RuntimeError, TypeError) as exc:
        logger.debug("Health check Postgres SELECT 1 failed: %s", exc)
        # TCP fallback when SELECT 1 is unavailable.
    if not dsn or not dsn.strip():
        return "not_configured"
    try:
        m = re.search(r"@([^:/]+)(?::(\d+))?", dsn)
        if not m:
            return "error"
        host, port_str = m.group(1), m.group(2)
        port = int(port_str) if port_str else 5432
        reader, writer = await asyncio.wait_for(asyncio.open_connection(host, port), timeout=2.0)
        writer.close()
        await writer.wait_closed()
        return "tcp_only"
    except (OSError, ValueError, KeyError, RuntimeError, TypeError) as exc:
        logger.debug("Postgres TCP connectivity check failed: %s", exc)
        return "error"


@asynccontextmanager  # type: ignore[arg-type]
async def lifespan(app: FastAPI) -> object:
    """FastAPI lifespan hook for ingress-only startup."""
    logger.info("Starting API server")

    # Fail fast on JWT and RLS readiness before serving requests.
    from backend.core.jwt import assert_jwt_runtime_ready
    from backend.core.rls import assert_rls_ready, validate_rls_runtime_mode
    from backend.db import _async_session_factory

    assert_jwt_runtime_ready()
    validate_rls_runtime_mode()

    jwt_previous = os.getenv("JWT_SECRET_PREVIOUS", "")
    if jwt_previous:
        logger.info("JWT dual-track rotation active (PREVIOUS key loaded)")

    app.state.rls_ready = False
    if _async_session_factory is not None:
        async with _async_session_factory() as session:
            await assert_rls_ready(session)
        app.state.rls_ready = True
        logger.info("RLS runtime readiness verified before serving tenant traffic")

    # Restore auto-tune EMA weights from DB so scheduling quality is not
    # reset on every process restart.
    if _async_session_factory is not None:
        try:
            from backend.core.governance_facade import get_governance_facade

            async with _async_session_factory() as session:
                await get_governance_facade().load_tuner_state(session)
        except (OSError, ValueError, KeyError, RuntimeError, TypeError) as exc:
            logger.warning("Failed to restore scheduler tuner weights: %s", exc)

    # Redis is optional; keep degraded mode but log clearly.
    settings = get_settings()
    app.state.redis = await connect_redis_with_retry(settings, logger=logger)
    if app.state.redis is None:
        logger.error("Redis unavailable after retries; API will run with degraded capabilities")

    bootstrap_extension_runtime()

    # Emit an explicit trace on SIGTERM so orchestrated shutdown stays visible.
    def _sigterm_handler(signum: int, frame: object) -> None:
        logger.info("SIGTERM received (signal=%s), initiating graceful shutdown", signum)
        del frame

    original_handler = signal.getsignal(signal.SIGTERM)
    signal.signal(signal.SIGTERM, _sigterm_handler)

    from backend.capabilities import clear_lru_cache
    from backend.core.telemetry import init_telemetry, shutdown_telemetry

    # Kernel observability: conditional OTEL tracing (requires OTEL_EXPORTER_OTLP_ENDPOINT)
    init_telemetry(app)

    logger.info("API process is ingress-only; control-plane workers must run out of process")

    try:
        yield
    finally:
        logger.info("Shutting down API server and draining connections")
        signal.signal(signal.SIGTERM, original_handler)
        shutdown_telemetry()
        clear_lru_cache()

        if getattr(app.state, "redis", None) is not None:
            try:
                await app.state.redis.close()
            except (OSError, ValueError, KeyError, RuntimeError, TypeError) as exc:
                logger.warning("Error closing Redis during shutdown: %s", exc)
            app.state.redis = None
        logger.info("Graceful shutdown complete")


# -------------------- App --------------------
_is_production = os.getenv("ZEN70_ENV", "development").lower() == "production"

# ── API stability contract tags ──────────────────────────────────────
# stability tiers: stable (GA, semver-protected), beta (may change in minor),
# experimental (may change or disappear at any time), deprecated (removal planned).
_API_STABILITY_TAGS: list[dict[str, object]] = [
    {"name": "auth", "description": "Authentication & token management", "x-stability": "stable"},
    {"name": "health", "description": "Health checks", "x-stability": "stable"},
    {"name": "jobs", "description": "Job lifecycle & dispatch", "x-stability": "stable"},
    {"name": "nodes", "description": "Node registration & status", "x-stability": "stable"},
    {"name": "connectors", "description": "Connector management", "x-stability": "stable"},
    {"name": "settings", "description": "System settings", "x-stability": "stable"},
    {"name": "console", "description": "Dashboard & operational views", "x-stability": "stable"},
    {"name": "workflows", "description": "Workflow orchestration", "x-stability": "beta"},
    {"name": "scheduling-governance", "description": "Scheduling policies, feature flags, decision audit", "x-stability": "beta"},
    {"name": "quotas", "description": "Tenant resource quotas", "x-stability": "beta"},
    {"name": "alerts", "description": "Alert rules & notifications", "x-stability": "beta"},
    {"name": "kernel", "description": "Kernel introspection & capabilities", "x-stability": "beta"},
    {"name": "extensions", "description": "Extension SDK manifests, published schemas, workflow templates", "x-stability": "beta"},
    {"name": "triggers", "description": "Unified trigger registry, ingress, and delivery history", "x-stability": "beta"},
    {"name": "reservations", "description": "Time-dimension reservations and backfill planning windows", "x-stability": "beta"},
    {"name": "node-approval", "description": "Node enrollment approval flow", "x-stability": "stable"},
    {"name": "audit-logs", "description": "Audit trail query", "x-stability": "stable"},
    {"name": "permissions", "description": "RBAC permission management", "x-stability": "stable"},
    {"name": "sessions", "description": "Session management", "x-stability": "stable"},
    {"name": "user-management", "description": "User admin", "x-stability": "stable"},
    {"name": "profile", "description": "User profile", "x-stability": "stable"},
    {"name": "cluster", "description": "Multi-node cluster (optional)", "x-stability": "experimental"},
]

app = FastAPI(
    title="ZEN70 API",
    version=get_runtime_version(),
    lifespan=lifespan,
    docs_url=None if _is_production else "/api/docs",
    redoc_url=None if _is_production else "/api/redoc",
    openapi_tags=_API_STABILITY_TAGS,
)

settings = get_settings()
cors_origins = cast(Sequence[str], settings["cors_origins"])
app.add_middleware(
    CORSMiddleware,
    allow_origins=cors_origins,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type", "X-Request-ID", "X-Idempotency-Key"],
    expose_headers=["X-Request-ID", "X-New-Token", "X-Process-Time"],
)


# -------------------- Request Guards --------------------
# The specialized middleware module owns the read-only disk / UPS guard and
# request-size limit. Keep the FastAPI wiring thin here.
@app.middleware("http")
async def _readonly_lock(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """Read-only guard for UPS and critical disk pressure states."""
    return await global_readonly_lock(request, call_next)


@app.middleware("http")
async def _limit_body(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """Reject oversized request bodies using configured max_request_size."""
    return await limit_request_body(request, call_next)


@app.middleware("http")
async def add_request_id_and_log(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """Attach request id, timing headers, and structured request logging."""
    request_id = getattr(request.state, "request_id", None) or request.headers.get("X-Request-ID") or str(uuid.uuid4())
    request.state.request_id = request_id
    start = time.perf_counter()
    response = await call_next(request)
    duration = time.perf_counter() - start
    response.headers["X-Request-ID"] = request_id
    response.headers["X-Process-Time"] = f"{duration:.3f}"
    logger.info(
        "%s %s %s %.3fs",
        request.method,
        request.url.path,
        response.status_code,
        duration,
        extra={
            "request_id": request_id,
            "method": request.method,
            "path": request.url.path,
            "status_code": response.status_code,
            "duration": duration,
        },
    )
    return response


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException) -> JSONResponse:
    """Convert HTTPException to unified error response."""
    request_id = getattr(request.state, "request_id", "unknown")
    detail = cast(object, exc.detail)
    if isinstance(detail, dict) and "code" in detail:
        return JSONResponse(status_code=exc.status_code, content=detail)
    return JSONResponse(
        status_code=exc.status_code,
        content=ErrorResponse(
            code=f"ZEN-HTTP-{exc.status_code}",
            message=str(exc.detail) if exc.detail else "HTTP error",
            recovery_hint="Check the request and retry",
            details={"request_id": request_id},
        ).model_dump(mode="json"),
    )


@app.exception_handler(StarletteHTTPException)
async def starlette_http_exception_handler(request: Request, exc: StarletteHTTPException) -> JSONResponse:
    """Convert Starlette HTTPException to unified error response."""
    request_id = getattr(request.state, "request_id", "unknown")
    return JSONResponse(
        status_code=exc.status_code,
        content=ErrorResponse(
            code=f"ZEN-HTTP-{exc.status_code}",
            message=str(exc.detail) if exc.detail else "HTTP error",
            recovery_hint="Check the URL and retry",
            details={"request_id": request_id},
        ).model_dump(mode="json"),
    )


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError) -> JSONResponse:
    """Convert request validation errors to unified 422 response."""
    request_id = getattr(request.state, "request_id", "unknown")
    return JSONResponse(
        status_code=422,
        content=ErrorResponse(
            code="ZEN-VAL-422",
            message="Validation error",
            recovery_hint="Check request payload and retry",
            details={"request_id": request_id, "errors": exc.errors()},
        ).model_dump(mode="json"),
    )


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Convert unexpected exceptions to unified 500 error response."""
    request_id = getattr(request.state, "request_id", "unknown")
    logger.error("Unhandled exception: %s", exc, exc_info=True, extra={"request_id": request_id})
    return JSONResponse(
        status_code=500,
        content=ErrorResponse(
            code="ZEN-INT-5000",
            message="Internal server error",
            recovery_hint="Retry later or contact administrator",
            details={"request_id": request_id},
        ).model_dump(mode="json"),
    )


@app.get("/health", response_model=HealthResponse)
async def health_check(request: Request) -> HealthResponse:
    """Health endpoint with dependency connectivity checks."""
    redis_client: RedisClient | None = getattr(request.app.state, "redis", None)
    services: dict[str, str] = {}
    if redis_client:
        try:
            ok = await asyncio.wait_for(redis_client.ping(), timeout=2.0)
            services["redis"] = "ok" if ok else "error"
        except asyncio.TimeoutError:
            services["redis"] = "timeout"
        except (OSError, ValueError, KeyError, RuntimeError, TypeError) as exc:
            logger.debug("Health check Redis ping failed: %s", exc)
            services["redis"] = "error"
    else:
        services["redis"] = "error"
    try:
        postgres_dsn = get_settings().get("postgres_dsn")
        services["postgres"] = await asyncio.wait_for(_check_postgres_async(postgres_dsn), timeout=2.0)  # type: ignore[arg-type]
    except asyncio.TimeoutError:
        services["postgres"] = "timeout"
    status = (
        "healthy"
        if services.get("redis") == "ok" and services.get("postgres") == "ok"
        else ("unhealthy" if services.get("redis") != "ok" and services.get("postgres") != "ok" else "degraded")
    )
    return HealthResponse(status=status, version=get_runtime_version(), services=services)


_ALL_ROUTERS = {
    "routes": routes.router,
    "auth": auth_router.router,
    "settings": settings_router.router,
    "profile": profile_router.router,
    "console": console_router.router,
    "nodes": nodes_router.router,
    "node_approval": node_approval_router.router,
    "jobs": jobs_router.router,
    "connectors": connectors_router.router,
    "triggers": triggers_router.router,
    "reservations": reservations_router.router,
    "extensions": extensions_router.router,
    "user_management": user_management_router.router,
    "audit_logs": audit_logs_router.router,
    "permissions": permissions_router.router,
    "sessions": sessions_router.router,
    "quotas": quotas_router.router,
    "alerts": alerts_router.router,
    "evaluations": evaluations_router.router,
    "kernel": kernel_router.router,
    "workflows": workflows_router.router,
    "scheduling_governance": scheduling_governance_router.router,
}

_gateway_profile = get_gateway_profile()
_gateway_packs = get_gateway_packs()

# Load core routers (always included)
for router_name, router_obj in _ALL_ROUTERS.items():
    app.include_router(router_obj)
    logger.info("Loaded core router: %s", router_name)

# Load optional routers (explicit admission control)
# Load optional routers (explicit admission control)
# Pack-declared routers are admitted when the pack IS selected via GATEWAY_PACKS.
_pack_declared_routers: set[str] = set()
for pk in _gateway_packs:
    from backend.core.pack_registry import PACK_DEFINITIONS

    _pdef = PACK_DEFINITIONS.get(pk)
    if _pdef:
        _pack_declared_routers.update(_pdef.routers)

for router_name in get_enabled_router_names(_gateway_profile):
    if router_name in _ALL_ROUTERS:
        # Already loaded as core router
        continue
    if router_name in KERNEL_ALLOWED_OPTIONAL_ROUTERS or router_name in _pack_declared_routers:
        if router_name in OPTIONAL_ROUTER_MODULES:
            app.include_router(_load_optional_router(router_name))
            logger.info("Loaded optional router: %s", router_name)
        else:
            logger.info(
                "Router '%s' declared by pack but no module registered in OPTIONAL_ROUTER_MODULES",
                router_name,
            )
    else:
        # Pack declares this router, but it's not admitted to default kernel runtime
        logger.info(
            "Skipping router '%s' (pack contract only, not in kernel admission list)",
            router_name,
        )


# -------------------- Success Envelope --------------------
_ENVELOPE_SKIP_PATHS = {"/health", "/openapi.json", "/api/docs", "/api/redoc", "/metrics"}
_ENVELOPE_MAX_BODY_BYTES = 10 * 1024 * 1024  # 10MB safety guard


@app.middleware("http")
async def success_envelope(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """Wrap successful JSON responses in the unified envelope format."""
    response = await call_next(request)

    # Only wrap successful JSON responses. Leave health/docs/metrics and
    # non-JSON payloads untouched.
    if request.url.path in _ENVELOPE_SKIP_PATHS:
        return response
    ct = response.headers.get("content-type", "")
    if response.status_code < 200 or response.status_code >= 300:
        return response
    if "application/json" not in ct:
        return response

    body_iterator = getattr(response, "body_iterator", None)
    if body_iterator is None:
        return response

    body_chunks: list[bytes] = []
    body_size = 0
    oversized = False
    async for chunk in body_iterator:
        raw = chunk if isinstance(chunk, bytes) else chunk.encode("utf-8")
        body_size += len(raw)
        body_chunks.append(raw)
        if body_size > _ENVELOPE_MAX_BODY_BYTES:
            oversized = True
            break

    if oversized:
        # Preserve the original response if buffering crosses the envelope
        # safety limit while still draining the body iterator.
        async for remaining in body_iterator:
            body_chunks.append(remaining if isinstance(remaining, bytes) else remaining.encode("utf-8"))
        logger.warning(
            "Response body exceeds %d bytes for %s, skip envelope wrapping",
            _ENVELOPE_MAX_BODY_BYTES,
            request.url.path,
        )
        return Response(
            content=b"".join(body_chunks),
            status_code=response.status_code,
            headers=dict(response.headers),
            media_type=response.media_type,
        )

    body_bytes = b"".join(body_chunks)

    try:
        original = json.loads(body_bytes)
    except (json.JSONDecodeError, UnicodeDecodeError):
        return Response(
            content=body_bytes,
            status_code=response.status_code,
            headers=dict(response.headers),
            media_type=response.media_type,
        )

    if isinstance(original, dict) and original.get("code") == "ZEN-OK-0":
        return Response(
            content=body_bytes,
            status_code=response.status_code,
            headers=dict(response.headers),
            media_type=response.media_type,
        )

    envelope = {"code": "ZEN-OK-0", "message": "ok", "data": original}
    new_body = json.dumps(envelope, ensure_ascii=False).encode("utf-8")
    new_headers = dict(response.headers)
    new_headers["content-length"] = str(len(new_body))
    return Response(
        content=new_body,
        status_code=response.status_code,
        headers=new_headers,
        media_type="application/json",
    )


# Register RequestID middleware last so it wraps the full HTTP middleware chain
# and populates contextvars for all downstream structured logs.
app.add_middleware(RequestIDMiddleware)
