# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
HTTP 中间件集合：RequestID 注入、UPS 全局只读熔断、请求体大小限制。

红线合规：
- 所有请求/响应携带 X-Request-ID
- UPS LOW_BATTERY_SHUTDOWN → 全局拒绝写入
- 请求体超限 → 413

注意：成功响应 Envelope 包装 (ADR 0010) 的唯一权威实现在 backend/api/main.py。

A-1 修复：UPS 预检也走 app.state.redis 连接池（不再 get_redis 短连接）。
"""

from __future__ import annotations

import contextvars
import logging
import os
import re
import uuid
from typing import Any

from fastapi import Request
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.responses import Response

from backend.capabilities import get_lru_matrix
from backend.core.errors import ZenErrorResponse as ErrorResponse
from backend.shared_state import service_readiness

logger = logging.getLogger(__name__)

# API 边缘层注射 X-Request-ID（使用 contextvars 避免并发污染）
_request_id_ctx: contextvars.ContextVar[str] = contextvars.ContextVar("request_id", default="NO-REQUEST-ID")
_REQUEST_ID_PATTERN = re.compile(r"^[A-Za-z0-9._:-]{1,128}$")

old_factory = logging.getLogRecordFactory()


def record_factory(*args: Any, **kwargs: Any) -> logging.LogRecord:
    record = old_factory(*args, **kwargs)
    request_id = getattr(record, "request_id_override", None) or _request_id_ctx.get()
    setattr(record, "_zen_request_id", request_id)
    if not getattr(record, "request_id", None):
        setattr(record, "request_id", request_id)
    return record


logging.setLogRecordFactory(record_factory)


def _normalize_request_id(raw_request_id: str | None) -> str:
    request_id = (raw_request_id or "").strip()
    if _REQUEST_ID_PATTERN.fullmatch(request_id):
        return request_id
    return uuid.uuid4().hex


class RequestIDMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        # 如果上游已传则复用；否则生成新 UUID4
        request_id = _normalize_request_id(
            request.headers.get("X-Request-ID") or request.headers.get("X-Trace-Id"),
        )
        request.state.request_id = request_id

        # 桥接 OTEL：将 trace_id 注入响应头，与 X-Request-ID 共存
        trace_id_hex = ""
        try:
            from backend.core.telemetry import is_otel_enabled

            if is_otel_enabled():
                from opentelemetry import trace

                span = trace.get_current_span()
                ctx = span.get_span_context()
                if ctx and ctx.trace_id:
                    trace_id_hex = format(ctx.trace_id, "032x")
        except Exception:  # noqa: BLE001
            pass

        token = _request_id_ctx.set(request_id)
        try:
            response = await call_next(request)
            response.headers["X-Request-ID"] = request_id
            if trace_id_hex:
                response.headers["X-Trace-Id"] = trace_id_hex
            return response
        finally:
            _request_id_ctx.reset(token)


async def global_readonly_lock(request: Request, call_next: RequestResponseEndpoint) -> JSONResponse | Response:
    """
    法典 3.2.4: UPS 熔断大闸。
    如果 Redis 能力矩阵探针汇报 UPS=LOW_BATTERY_SHUTDOWN，
    则全局拒绝所有 POST/PUT/DELETE/PATCH 写入请求（转入只读模式）。

    A-1: LRU 缓存为空时通过 app.state.redis 连接池读取 UPS 状态（不再建短连接）。
    """
    if request.method in ("POST", "PUT", "DELETE", "PATCH"):
        from backend.core.constants import KEY_SYSTEM_READONLY_DISK, KEY_SYSTEM_UPS_STATUS

        matrix = get_lru_matrix()

        if matrix is None:
            # LRU 缓存为空 → 走 app.state.redis 持久连接读一次
            try:
                app_redis = getattr(request.app.state, "redis", None)
                r = getattr(app_redis, "redis", None) if app_redis else None
                if r:
                    # 链路 9 修复：同时检查 UPS 状态 + 磁盘 95% 只读标志
                    ups_val = await r.get(KEY_SYSTEM_UPS_STATUS)
                    if ups_val and ups_val.strip().upper() == "LOW_BATTERY_SHUTDOWN":
                        return JSONResponse(
                            status_code=503,
                            content=ErrorResponse(
                                code="ZEN-SYS-9999",
                                message="市电中断且电池告警，系统已进入全局强制只读模式保护硬件",
                                recovery_hint="等待市电恢复后，网关将自动解除锁定放行写入",
                                details={
                                    "method": request.method,
                                    "url": str(request.url),
                                    "request_id": getattr(request.state, "request_id", "unknown"),
                                },
                            ).model_dump(mode="json"),
                        )
                    # 法典 §3.3：磁盘 95% 全局只读大闸
                    disk_val = await r.get(KEY_SYSTEM_READONLY_DISK)
                    if disk_val:
                        return JSONResponse(
                            status_code=503,
                            content=ErrorResponse(
                                code="ZEN-SYS-9998",
                                message="系统盘使用率超过 95%，已触发全局只读大闸保护物理磁盘",
                                recovery_hint="请清理磁盘空间。当使用率降至 90% 以下时将自动解除锁定",
                                details={
                                    "method": request.method,
                                    "url": str(request.url),
                                    "request_id": getattr(request.state, "request_id", "unknown"),
                                },
                            ).model_dump(mode="json"),
                        )
            except (OSError, ValueError, KeyError, RuntimeError, TypeError):
                logger.debug("Readonly precheck failed in middleware")
        else:
            ups_cap = matrix.get("ups")
            ups_status = str(getattr(ups_cap, "status", "") or "").lower()
            if ups_status == "low-battery-shutdown":
                return JSONResponse(
                    status_code=503,
                    content=ErrorResponse(
                        code="ZEN-SYS-9999",
                        message="市电中断且电池告警，系统已进入全局强制只读模式保护硬件",
                        recovery_hint="等待市电恢复后，网关将自动解除锁定放行写入",
                        details={
                            "method": request.method,
                            "url": str(request.url),
                            "request_id": getattr(request.state, "request_id", "unknown"),
                        },
                    ).model_dump(mode="json"),
                )

    # Readiness 拦截保护（快照迭代防并发修改 RuntimeError）
    path_segments = set(request.url.path.strip("/").split("/"))
    for svc_name, is_ready in list(service_readiness.items()):
        if not is_ready:
            if svc_name in path_segments:
                return JSONResponse(
                    status_code=503,
                    content=ErrorResponse(
                        code="ZEN-SVC-NOTREADY",
                        message=f"子服务 {svc_name} 尚未就绪 (Readiness Probe 失败), 流量已自动抛弃",
                        recovery_hint="请等待模型拉起完毕或节点自愈",
                        details={
                            "service": svc_name,
                            "request_id": getattr(request.state, "request_id", "unknown"),
                        },
                    ).model_dump(mode="json"),
                )

    response = await call_next(request)
    return response


# 法典 7：禁止 API 无大小限制
MAX_REQUEST_BODY_BYTES = int(os.getenv("MAX_REQUEST_BODY_BYTES", "10485760"))  # 10MB


async def limit_request_body(request: Request, call_next: RequestResponseEndpoint) -> JSONResponse | Response:
    """请求体大小限制，超限返回 413。"""
    cl = request.headers.get("content-length")
    if cl and request.method in ("POST", "PUT", "PATCH"):
        try:
            size = int(cl)
            if size > MAX_REQUEST_BODY_BYTES:
                return JSONResponse(
                    status_code=413,
                    content=ErrorResponse(
                        code="ZEN-REQ-413",
                        message="Request entity too large",
                        recovery_hint=f"请求体不得超过 {MAX_REQUEST_BODY_BYTES // (1024*1024)} MB",
                        details={
                            "max_bytes": MAX_REQUEST_BODY_BYTES,
                            "request_id": getattr(request.state, "request_id", "unknown"),
                        },
                    ).model_dump(mode="json"),
                )
        except ValueError:
            pass
    return await call_next(request)


def add_request_id() -> None:
    """已废弃：功能由 RequestIDMiddleware 统一提供（含 contextvars 日志关联）。"""
    raise RuntimeError("add_request_id is deprecated; use RequestIDMiddleware")
