# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
ZEN70 静默数据腐败巡检守护 (Bit-Rot Detection)
法典准则 §3.2.3:
通过低优先级后台任务，对底层冷数据块进行 SHA-256 哈希比对。
若发现物理扇区数据反转，即刻通过告警通道推送预警以实施数据隔离。
由于本模块低频、低并发且与核心业务隔离，明确允许使用独立 SQLite。
"""

from __future__ import annotations

import hashlib
import logging
import os
import sqlite3
import time
from pathlib import Path

import httpx

try:
    import psutil
except ImportError:  # pragma: no cover - 运行时环境差异，单测不稳定复现
    psutil = None

logger = logging.getLogger("zen70.sentinel.bit_rot")

# 独立于 Postgres，规避高并发锁问题的专属本地哈希基线库
DB_PATH = Path(__file__).parent / "bit_rot_baseline.db"
DEFAULT_CPU_LOAD_THRESHOLD_PERCENT = 50.0
DEFAULT_ALERT_TIMEOUT_SECONDS = 5.0
DEFAULT_SQLITE_CONNECT_TIMEOUT_SECONDS = 5.0
DEFAULT_SQLITE_BUSY_TIMEOUT_MS = 5000.0
ENV_CPU_LOAD_THRESHOLD_PERCENT = "BIT_ROT_CPU_LOAD_THRESHOLD_PERCENT"
ENV_ALERT_TIMEOUT_SECONDS = "BIT_ROT_ALERT_TIMEOUT_SECONDS"
ENV_SQLITE_CONNECT_TIMEOUT_SECONDS = "BIT_ROT_SQLITE_CONNECT_TIMEOUT_SECONDS"
ENV_SQLITE_BUSY_TIMEOUT_MS = "BIT_ROT_SQLITE_BUSY_TIMEOUT_MS"


def _read_positive_float_env(env_name: str, default: float) -> float:
    """读取浮点环境变量，非法值回退默认值，避免异常中断巡检主链路。"""
    raw_value = os.getenv(env_name, "").strip()
    if not raw_value:
        return default
    try:
        parsed_value = float(raw_value)
    except ValueError:
        logger.warning("环境变量 %s 非法，回退默认值 %s", env_name, default)
        return default
    if parsed_value <= 0:
        logger.warning("环境变量 %s 必须大于 0，回退默认值 %s", env_name, default)
        return default
    return parsed_value


def _connect_baseline_db() -> sqlite3.Connection:
    """创建带超时与 busy_timeout 的连接，降低文件锁竞争导致的失败概率。"""
    connect_timeout_seconds = _read_positive_float_env(
        ENV_SQLITE_CONNECT_TIMEOUT_SECONDS,
        DEFAULT_SQLITE_CONNECT_TIMEOUT_SECONDS,
    )
    busy_timeout_ms = int(
        _read_positive_float_env(
            ENV_SQLITE_BUSY_TIMEOUT_MS,
            DEFAULT_SQLITE_BUSY_TIMEOUT_MS,
        )
    )
    conn = sqlite3.connect(DB_PATH, timeout=connect_timeout_seconds)
    conn.execute(f"PRAGMA busy_timeout={busy_timeout_ms}")
    return conn


def init_baseline_db() -> None:
    conn = _connect_baseline_db()
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS file_hashes (
            filepath TEXT PRIMARY KEY,
            sha256 TEXT NOT NULL,
            last_checked REAL NOT NULL,
            size INTEGER NOT NULL
        )
    """)
    conn.commit()
    conn.close()


def compute_sha256(filepath: str, blocksize: int = 65536) -> str | None:
    """大文件防 OOM 流式哈希计算"""
    hasher = hashlib.sha256()
    try:
        with Path(filepath).open("rb") as afile:
            buf = afile.read(blocksize)
            while len(buf) > 0:
                hasher.update(buf)
                buf = afile.read(blocksize)
        return hasher.hexdigest()
    except OSError as e:
        logger.error("无法读取文件计算哈希: %s - %s", filepath, e)
        return None


def check_system_load_safe() -> bool:
    """
    法典要求：仅在核心 CPU 负载低于 10% 时才执行（模拟设定）
    为了开发测试，这里调高阈值为 50%
    """
    cpu_threshold = _read_positive_float_env(
        ENV_CPU_LOAD_THRESHOLD_PERCENT,
        DEFAULT_CPU_LOAD_THRESHOLD_PERCENT,
    )
    if psutil is None:
        logger.warning("psutil 不可用，跳过 CPU 负载门禁检查。")
        return True
    cpu_usage = psutil.cpu_percent(interval=1)
    if cpu_usage > cpu_threshold:
        logger.info("系统当前负载较高 (%s%%)，挂起 Bit-Rot 巡检任务。", cpu_usage)
        return False
    return True


def _verify_single_file(filepath: Path, cursor: sqlite3.Cursor, corrupted_files: list[Path]) -> None:
    """对单个文件执行哈希检查逻辑"""
    if not filepath.is_file() or filepath.name.startswith("."):
        return

    try:
        current_size = filepath.stat().st_size
    except OSError:
        return

    cursor.execute(
        "SELECT sha256, size FROM file_hashes WHERE filepath = ?",
        (str(filepath),),
    )
    row = cursor.fetchone()

    if not row:
        logger.info("➕ 首次发现文件，录入基线: %s", filepath)
        file_hash = compute_sha256(str(filepath))
        if file_hash:
            cursor.execute(
                "INSERT INTO file_hashes (filepath, sha256, last_checked, size) VALUES (?, ?, ?, ?)",
                (str(filepath), file_hash, time.time(), current_size),
            )
    else:
        baseline_hash, baseline_size = row
        if current_size == baseline_size:
            current_hash = compute_sha256(str(filepath))
            if current_hash and current_hash != baseline_hash:
                logger.critical("☢️ [极高危] 静默数据腐败检测触发! 位翻转发生: %s", filepath)
                corrupted_files.append(filepath)
        else:
            new_hash = compute_sha256(str(filepath))
            if new_hash:
                cursor.execute(
                    "UPDATE file_hashes SET sha256 = ?, size = ?, last_checked = ? WHERE filepath = ?",
                    (new_hash, current_size, time.time(), str(filepath)),
                )


def _scan_directory_against_baseline(target: Path) -> list[Path]:
    """扫描目录并完成本地基线比对，返回检测出的腐败文件列表。"""
    corrupted_files: list[Path] = []
    with _connect_baseline_db() as conn:
        cursor = conn.cursor()
        for filepath in target.rglob("*"):
            _verify_single_file(filepath, cursor, corrupted_files)
        conn.commit()
    return corrupted_files


def _send_corruption_alert(corrupted_files: list[Path]) -> None:
    """将静默腐败事件推送至外部告警通道。"""
    alert_webhook = os.getenv("ALERT_WEBHOOK_URL", "").strip()
    if not alert_webhook:
        return

    alert_timeout_seconds = _read_positive_float_env(
        ENV_ALERT_TIMEOUT_SECONDS,
        DEFAULT_ALERT_TIMEOUT_SECONDS,
    )
    file_list = "\n".join(str(f) for f in corrupted_files[:10])
    payload = {
        "level": "critical",
        "title": "☢️ 静默数据腐败检测触发",
        "message": f"发现 {len(corrupted_files)} 个腐败文件:\n{file_list}",
        "source": "data_integrity",
    }
    try:
        with httpx.Client(timeout=alert_timeout_seconds) as client:
            client.post(alert_webhook, json=payload)
    except (OSError, ValueError, KeyError, RuntimeError, TypeError) as alert_err:
        logger.error("告警下行通道故障: %s", alert_err)


def scan_and_verify_directory(target_dir: str) -> None:
    """递归遍历目标目录，进行状态比对与基线更新"""
    if not check_system_load_safe():
        return

    target = Path(target_dir)
    if not target.exists() or not target.is_dir():
        logger.error("巡检目录不存在或不是目录: %s", target)
        return

    corrupted_files = _scan_directory_against_baseline(target)

    if corrupted_files:
        logger.critical(
            "本次巡检发现 %s 个静默腐败文件！需要立即从高可用端或 S3 降级恢复。",
            len(corrupted_files),
        )
        # 法典：触发 AlertManager API 下发紧急通知
        _send_corruption_alert(corrupted_files)


if __name__ == "__main__":
    import logging

    logging.basicConfig(level=logging.INFO)
    logger.info("启动 ZEN70 静默腐败探针...")
    init_baseline_db()

    # 开发态下，模拟检查当前应用根目录的某个 data 文件夹
    test_dir = Path(__file__).parent.parent / "tests"
    if test_dir.exists():
        scan_and_verify_directory(str(test_dir))
