# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
ZEN70 极限生存守护者 (Thermal Overload & UPS Graceful Shutdown)
法典准则 §3.2.4:
监测 UPS 断联，当预估时间 < 5 分钟时，全量 API 进入 503 拒绝，强制数据库 CHECKPOINT 刷盘，安全终止所有 Docker 后 halt 关机。
法典准则 补充红线:
监测 CPU/GPU 温度，温度越界时同样熔断 API 并通过 Redis Pub/Sub 下发容器降级事件。
ADR-0006 合规：网关绝不直连 docker.sock，所有容器控制通过 Redis switch:events 传递。
"""

import asyncio
import json
import logging
import os
from typing import Protocol, cast

import httpx
import psutil

logger = logging.getLogger("zen70.sentinel.guardian")


class RedisLike(Protocol):
    async def set(self, name: str, value: str) -> object: ...

    async def publish(self, channel: str, message: str) -> object: ...


class SystemGuardian:
    def __init__(self) -> None:
        # 假设通过 Categraf 或者内部 API 暴露了 /api/v1/alerts/trigger 接口
        self.alert_webhook = os.getenv("ALERT_WEBHOOK_URL", "").strip()
        self.temperature_threshold = 85.0  # 摄氏度
        self.ups_battery_threshold = 20.0  # 百分比
        # ADR-0006: Redis 连接用于通过 Pub/Sub 下发控制事件（不直连 docker.sock）
        self._redis: RedisLike | None = None

    async def _get_redis(self) -> RedisLike:
        """惰性获取 Redis 连接（避免构造函数中初始化异步资源）。"""
        if self._redis is not None:
            return self._redis
        try:
            import redis.asyncio as aioredis

            host = os.getenv("REDIS_HOST", "127.0.0.1")
            port = int(os.getenv("REDIS_PORT", "6379"))
            password = os.getenv("REDIS_PASSWORD", "") or None
            self._redis = cast(RedisLike, aioredis.Redis(host=host, port=port, password=password, decode_responses=True))
            return self._redis
        except (OSError, ValueError, KeyError, RuntimeError, TypeError, ImportError) as e:
            logger.error("Redis 连接初始化失败: %s", e)
            raise

    async def emit_critical_alert(self, title: str, message: str) -> None:
        """调用 AlertManager 下发全域紧急通知 (微信/Bark)"""
        if not self.alert_webhook:
            logger.warning("ALERT_WEBHOOK_URL 未配置，跳过告警下发: %s", title)
            return
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                await client.post(
                    self.alert_webhook,
                    json={
                        "level": "critical",
                        "title": title,
                        "message": message,
                        "source": "Guardian",
                    },
                )
                logger.warning("🚨 已发射最高级别实弹警告: %s", title)
        except (OSError, ValueError, KeyError, RuntimeError, TypeError) as e:
            logger.error("警告下行通道故障: %s", e)

    def fetch_cpu_temperature(self) -> float:
        """读取硬件探针温度 (基于工业级 Linux 容器特权探针挂载)"""
        # 宽容降级 (Feature Detection)：若由于容器环境异常/权限缺失导致 sensors 模块不可用，返回安全恒定值
        if not hasattr(psutil, "sensors_temperatures"):
            return 45.0

        temps = psutil.sensors_temperatures()
        if not temps:
            return 0.0

        # 取平均最高核心温度
        max_temp = 0.0
        for _name, entries in temps.items():
            for entry in entries:
                if entry.current > max_temp:
                    max_temp = entry.current
        return max_temp

    async def lock_api_gateway(self) -> None:
        """法典极刑：向 Redis 注入全局阻塞锁，所有外部 POST/PUT 全部返回 503"""
        logger.critical("🛑 [红线防御] 执行 API 全局写锁定。")
        try:
            r = await self._get_redis()
            from backend.core.constants import KEY_SYSTEM_READONLY_DISK

            await r.set(KEY_SYSTEM_READONLY_DISK, "thermal_guardian")
            logger.critical("🛑 已写入 Redis 全局只读锁: %s", KEY_SYSTEM_READONLY_DISK)
        except (OSError, ValueError, KeyError, RuntimeError, TypeError, ImportError) as e:
            logger.error("Redis 写入全局只读锁失败: %s — API 网关可能无法拦截写请求", e)

    async def pause_heavy_containers(self) -> None:
        """
        ADR-0006 合规：通过 Redis switch:events 下发 PAUSE 事件。
        绝不直连 docker.sock，由探针 (topology_sentinel) 负责执行实际 docker pause。
        """
        logger.warning("❄️ 通过 Redis Pub/Sub 下发容器降级事件...")
        heavy_containers = ["zen70-jellyfin", "zen70-frigate", "zen70-ollama"]
        try:
            r = await self._get_redis()
            for container in heavy_containers:
                event = {
                    "switch": container,
                    "state": "PAUSE",
                    "reason": "thermal_guardian: 温度越界紧急降级",
                    "source": "guardian",
                }
                await r.publish("switch:events", json.dumps(event))
                logger.info("❄️ 已发布降级事件: switch=%s state=PAUSE", container)
        except (OSError, ValueError, KeyError, RuntimeError, TypeError, ImportError) as e:
            logger.error("Redis Pub/Sub 降级事件下发失败: %s — 容器冻结指令未送达", e)

    async def run_thermal_loop(self) -> None:
        """监控硬件温度的无限循环"""
        while True:
            temp = self.fetch_cpu_temperature()
            if temp > self.temperature_threshold:
                msg = f"核心温度已达 {temp}°C，触发一级红线预警，全系统挂载点强制降频锁死！"
                await self.emit_critical_alert("🔥 硬件核爆预警", msg)
                await self.lock_api_gateway()
                await self.pause_heavy_containers()
                # 给硬件降温 5 分钟的喘息时间
                await asyncio.sleep(300)
            else:
                await asyncio.sleep(10)  # 10 秒轮询


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logger.info("ZEN70 Guardian 已接管底层生命探测...")
    guardian = SystemGuardian()

    # 手动触发一次高危逻辑模拟 (Dev Testing)
    asyncio.run(guardian.emit_critical_alert("测试告警启动", "守护神进程接管主机"))
    asyncio.run(guardian.pause_heavy_containers())

    # 真实应用会起一个 asyncio.run(guardian.run_thermal_loop())
