# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
单元测试：数据库会话生命周期。

覆盖 get_db_session 无 DSN 时 503、正常 commit/rollback/close 流程。
全部 Mock，不需要真实 PostgreSQL。
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi import HTTPException


class TestGetDbSession:
    """get_db_session 会话工厂。"""

    @pytest.mark.asyncio
    async def test_raises_503_when_no_dsn(self) -> None:
        """无 POSTGRES_DSN 配置时应抛出 503 HTTPException。"""
        with patch("backend.db._async_session_factory", None):
            from backend.db import get_db_session

            gen = get_db_session()
            with pytest.raises(HTTPException) as exc_info:
                await gen.__anext__()

            assert exc_info.value.status_code == 503
            assert "ZEN-BUS-5030" in str(exc_info.value.detail)

    @pytest.mark.asyncio
    async def test_commits_on_success(self) -> None:
        """正常退出时应调用 commit 和 close。"""
        mock_session = AsyncMock()
        mock_factory = MagicMock(return_value=mock_session)
        mock_session.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session.__aexit__ = AsyncMock(return_value=False)

        with patch("backend.db._async_session_factory", mock_factory):
            from backend.db import get_db_session

            gen = get_db_session()
            session = await gen.__anext__()
            assert session is mock_session

            # 正常结束
            try:
                await gen.__anext__()
            except StopAsyncIteration:
                pass

            mock_session.commit.assert_awaited_once()
            mock_session.close.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_rollback_on_exception(self) -> None:
        """异常时应先 rollback 再 close，并 re-raise。"""
        mock_session = AsyncMock()
        mock_session.commit = AsyncMock(side_effect=RuntimeError("commit failed"))
        mock_factory = MagicMock(return_value=mock_session)
        mock_session.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session.__aexit__ = AsyncMock(return_value=False)

        with patch("backend.db._async_session_factory", mock_factory):
            from backend.db import get_db_session

            gen = get_db_session()
            session = await gen.__anext__()
            assert session is mock_session

            with pytest.raises(RuntimeError, match="commit failed"):
                await gen.__anext__()

            mock_session.rollback.assert_awaited_once()
            mock_session.close.assert_awaited_once()


class TestDbConfig:
    """数据库配置验证。"""

    def test_dsn_conversion(self) -> None:
        """postgresql:// 应被自动替换为 postgresql+asyncpg://。"""
        # 导入 _ASYNC_DSN 来验证（当前环境无 DSN 所以是空字符串）
        from backend.db import _ASYNC_DSN

        if _ASYNC_DSN:
            assert "asyncpg" in _ASYNC_DSN
        else:
            # 无 DSN 环境下应为空字符串
            assert _ASYNC_DSN == ""
