# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated test module. Manual modifications may be overwritten.
from __future__ import annotations

import sys
from typing import Any
from unittest.mock import AsyncMock, MagicMock

import pytest
from pytest import MonkeyPatch
from pytest_mock import MockerFixture

from backend.workers.clip_worker import CLIPInferenceEngine, process_pending_assets


def test_clip_engine_load_cpu(mocker: MockerFixture, monkeypatch: MonkeyPatch) -> None:
    monkeypatch.setenv("CAPABILITY_TAGS", "cpu_avx2")
    engine = CLIPInferenceEngine()

    mock_st = MagicMock()
    sys.modules["sentence_transformers"] = mock_st

    engine.load()
    assert engine.device == "cpu"
    assert engine._loaded is True
    del sys.modules["sentence_transformers"]


def test_clip_engine_extract_mock(mocker: MockerFixture) -> None:
    engine = CLIPInferenceEngine()
    engine._loaded = False

    res: dict[str, Any] = engine.extract("test.jpg")
    assert len(res["embedding"]) == 512
    assert res["tags"] == ["模拟标签/mock"]


@pytest.mark.asyncio
async def test_process_pending_assets(mocker: MockerFixture) -> None:
    mocker.patch("backend.workers.clip_worker._async_session_factory")
    engine_mock = mocker.patch("backend.workers.clip_worker.engine")
    engine_mock._loaded = True

    mocker.patch(
        "backend.workers.clip_worker.asyncio.to_thread",
        new_callable=AsyncMock,
        return_value={"embedding": [0.1] * 512, "tags": ["微笑", "人物"]},
    )

    mock_session = AsyncMock()
    mocker.patch(
        "backend.workers.clip_worker._async_session_factory",
        return_value=mock_session,
    )
    mock_session.__aenter__.return_value = mock_session

    mock_asset = MagicMock()
    mock_asset.file_path = "test.jpg"
    mock_asset.embedding_status = "pending"

    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [mock_asset]
    mock_session.execute.return_value = mock_result

    await process_pending_assets()

    assert mock_asset.embedding_status == "done"
    assert mock_asset.is_emotion_highlight is True
    assert mock_asset.ai_tags == ["微笑", "人物"]
    mock_session.commit.assert_awaited()
