# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
单元测试：Prometheus 性能监控中间件。

覆盖 metrics_middleware 指标记录、/metrics 路径跳过、异常处理。
全部 Mock，不需要真实 Prometheus。
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock

import pytest


class TestMetricsMiddleware:
    """Prometheus 中间件。"""

    @pytest.mark.asyncio
    async def test_records_request_duration(self) -> None:
        """应记录请求耗时。"""
        from backend.core.metrics import metrics_middleware

        request = MagicMock()
        request.url.path = "/api/v1/data"
        request.method = "GET"

        response = MagicMock()
        response.status_code = 200
        call_next = AsyncMock(return_value=response)

        result = await metrics_middleware(request, call_next)
        assert result is response
        call_next.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_skips_metrics_endpoint(self) -> None:
        """对 /metrics 路径应直接放行，不记录指标。"""
        from backend.core.metrics import metrics_middleware

        request = MagicMock()
        request.url.path = "/metrics"
        request.method = "GET"

        response = MagicMock()
        call_next = AsyncMock(return_value=response)

        result = await metrics_middleware(request, call_next)
        assert result is response

    @pytest.mark.asyncio
    async def test_skips_health_endpoint(self) -> None:
        """对 /api/v1/health 路径应直接放行。"""
        from backend.core.metrics import metrics_middleware

        request = MagicMock()
        request.url.path = "/api/v1/health"
        request.method = "GET"

        response = MagicMock()
        call_next = AsyncMock(return_value=response)

        result = await metrics_middleware(request, call_next)
        assert result is response

    @pytest.mark.asyncio
    async def test_exception_records_500(self) -> None:
        """call_next 抛异常时应记录 500 状态码。"""
        from backend.core.metrics import metrics_middleware

        request = MagicMock()
        request.url.path = "/api/v1/crash"
        request.method = "POST"

        call_next = AsyncMock(side_effect=RuntimeError("boom"))

        with pytest.raises(RuntimeError, match="boom"):
            await metrics_middleware(request, call_next)


class TestMetricsDefinitions:
    """指标定义验证。"""

    def test_counter_exists(self) -> None:
        """API_REQUESTS_TOTAL 应存在。"""
        from backend.core.metrics import API_REQUESTS_TOTAL

        assert API_REQUESTS_TOTAL is not None

    def test_histogram_exists(self) -> None:
        """API_REQUEST_DURATION 应存在。"""
        from backend.core.metrics import API_REQUEST_DURATION

        assert API_REQUEST_DURATION is not None

    def test_gauge_exists(self) -> None:
        """ACTIVE_CONNECTIONS 应存在。"""
        from backend.core.metrics import ACTIVE_CONNECTIONS

        assert ACTIVE_CONNECTIONS is not None
