# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated test module. Manual modifications may be overwritten by IaC compiler.
"""
单元测试：PIN 登录暴力破解防护。

验证 5 次失败锁定 IP 15 分钟（PIN_RATE_LIMIT_WINDOW=900）、指数退避、
锁定期间拒绝、成功登录重置计数器。
全部 Mock Redis/DB，不需要真实基础设施。
"""

from __future__ import annotations

import os
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

os.environ["DOMAIN"] = "localhost"

import pytest  # noqa: E402
from fastapi import HTTPException  # noqa: E402

# ---------------------------------------------------------------------------
# Mock 辅助工厂
# ---------------------------------------------------------------------------


def _mock_request(client_ip: str = "192.168.1.10") -> MagicMock:
    """构造 FastAPI Request mock（含 request_id + client.host）。"""
    req = MagicMock()
    req.state.request_id = "test-rid-001"
    req.client.host = client_ip
    return req


def _mock_user(pin_hash: str | None = None, username: str = "alice") -> MagicMock:
    """构造 User ORM 对象 mock。"""
    user = MagicMock()
    user.id = "user-uuid-001"
    user.username = username
    user.role = "family"
    user.pin_hash = pin_hash
    user.tenant_id = "default"
    user.is_active = True
    return user


def _mock_redis(
    *,
    get_return: str | None = None,
    incr_return: int = 1,
) -> AsyncMock:
    """构造 RedisClient mock；get/incr_with_expire/setex/delete 均为 AsyncMock。"""
    redis = AsyncMock()
    redis.get = AsyncMock(return_value=get_return)
    redis.incr_with_expire = AsyncMock(return_value=incr_return)
    redis.setex = AsyncMock()
    redis.delete = AsyncMock()
    redis.redis = MagicMock()
    redis.incr = AsyncMock(return_value=incr_return)
    redis.expire = AsyncMock()
    return redis


def _mock_db(user: Any = None) -> AsyncMock:
    """构造 AsyncSession mock（execute 返回含 scalar_one_or_none 的 result）。"""
    db = AsyncMock()
    result = MagicMock()
    result.scalar_one_or_none.return_value = user
    db.execute = AsyncMock(return_value=result)
    return db


def _pin_request(username: str = "alice", pin: str = "1234") -> MagicMock:
    """构造 PinLoginRequest mock。"""
    req = MagicMock()
    req.username = username
    req.pin = pin
    return req


# ---------------------------------------------------------------------------
# 测试用例
# ---------------------------------------------------------------------------


class TestPinLockout:
    """PIN 登录暴力破解防护测试套件。"""

    @pytest.mark.asyncio
    async def test_lockout_rejects_when_frozen(self) -> None:
        """已冻结 IP 应立即返回 429，不查询数据库。"""
        from backend.api.auth import PIN_RATE_LIMIT_WINDOW, pin_login

        redis = _mock_redis(get_return="1")  # freeze_key 已设
        db = _mock_db()
        req = _pin_request()
        request = _mock_request()

        with pytest.raises(HTTPException) as exc_info:
            await pin_login(req, request, db=db, redis=redis)

        assert exc_info.value.status_code == 429
        assert "ZEN-AUTH-429" in str(exc_info.value.detail)
        assert str(PIN_RATE_LIMIT_WINDOW // 60) in str(exc_info.value.detail)
        # 不应查询 DB
        db.execute.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_wrong_pin_increments_counter(self) -> None:
        """错误 PIN 应递增 Redis 计数器。"""
        import bcrypt

        from backend.api.auth import pin_login

        correct_hash = bcrypt.hashpw(b"9999", bcrypt.gensalt(rounds=4)).decode("utf-8")
        user = _mock_user(pin_hash=correct_hash)
        redis = _mock_redis(get_return=None, incr_return=1)
        db = _mock_db(user=user)
        req = _pin_request(pin="0000")  # 错误 PIN
        request = _mock_request()

        with pytest.raises(HTTPException) as exc_info:
            await pin_login(req, request, db=db, redis=redis)

        assert exc_info.value.status_code == 401
        redis.incr_with_expire.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_fifth_failure_triggers_freeze(self) -> None:
        """第 5 次失败时应触发冻结锁定（setex freeze_key）。"""
        import bcrypt

        from backend.api.auth import (
            PIN_RATE_LIMIT_MAX,
            PIN_RATE_LIMIT_WINDOW,
            pin_login,
        )

        correct_hash = bcrypt.hashpw(b"9999", bcrypt.gensalt(rounds=4)).decode("utf-8")
        user = _mock_user(pin_hash=correct_hash)
        redis = _mock_redis(get_return=None, incr_return=PIN_RATE_LIMIT_MAX)  # 第 5 次
        db = _mock_db(user=user)
        req = _pin_request(pin="0000")
        request = _mock_request()

        with pytest.raises(HTTPException) as exc_info:
            await pin_login(req, request, db=db, redis=redis)

        assert exc_info.value.status_code == 429
        assert str(PIN_RATE_LIMIT_WINDOW // 60) in str(exc_info.value.detail)
        # 断言 setex 被调用以触发 freeze
        redis.setex.assert_awaited_once()
        call_args = redis.setex.call_args
        assert call_args[0][1] == PIN_RATE_LIMIT_WINDOW  # TTL = 900s

    @pytest.mark.asyncio
    async def test_successful_pin_clears_counter(self) -> None:
        """正确 PIN 登录应重置 Redis 计数器。"""
        import bcrypt

        from backend.api.auth import pin_login

        pin = "1234"
        pin_hash = bcrypt.hashpw(pin.encode("utf-8"), bcrypt.gensalt(rounds=4)).decode("utf-8")
        user = _mock_user(pin_hash=pin_hash)
        redis = _mock_redis(get_return=None)
        db = _mock_db(user=user)
        req = _pin_request(pin=pin)
        request = _mock_request()

        # pin_login 成功时返回 TokenResponse，不抛异常
        with patch(
            "backend.api.auth.token_response",
            return_value={
                "access_token": "test-tok",
                "token_type": "bearer",
                "expires_in": 900,
            },
        ):
            await pin_login(req, request, db=db, redis=redis)

        # 断言清除了速率限制和冻结 key
        assert redis.delete.await_count >= 2

    @pytest.mark.asyncio
    async def test_public_ip_rejected(self) -> None:
        """非内网 IP 应被 PIN 登录拒绝（403）。"""
        from backend.api.auth import pin_login

        redis = _mock_redis(get_return=None)
        db = _mock_db()
        req = _pin_request()
        request = _mock_request(client_ip="8.8.8.8")  # 公网 IP

        with pytest.raises(HTTPException) as exc_info:
            await pin_login(req, request, db=db, redis=redis)

        assert exc_info.value.status_code == 403

    @pytest.mark.asyncio
    async def test_no_user_or_no_pin_increments(self) -> None:
        """用户不存在或无 PIN hash 时也应递增计数器。"""
        from backend.api.auth import pin_login

        redis = _mock_redis(get_return=None, incr_return=1)
        db = _mock_db(user=None)  # 用户不存在
        req = _pin_request()
        request = _mock_request()

        with pytest.raises(HTTPException) as exc_info:
            await pin_login(req, request, db=db, redis=redis)

        assert exc_info.value.status_code == 401
        redis.incr_with_expire.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_disabled_user_rejected_before_token_issue(self) -> None:
        import bcrypt

        from backend.api.auth import pin_login

        pin_hash = bcrypt.hashpw(b"1234", bcrypt.gensalt(rounds=4)).decode("utf-8")
        user = _mock_user(pin_hash=pin_hash)
        user.is_active = False
        redis = _mock_redis(get_return=None)
        db = _mock_db(user=user)
        req = _pin_request(pin="1234")
        request = _mock_request()

        with pytest.raises(HTTPException) as exc_info:
            await pin_login(req, request, db=db, redis=redis)

        assert exc_info.value.status_code == 403
