# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated test module. Manual modifications may be overwritten.
from __future__ import annotations

import sys
from unittest.mock import AsyncMock, MagicMock

import pytest
from pytest_mock import MockerFixture

import backend.workers.ai_worker as ai_worker
from backend.workers.ai_worker import get_model, process_pending_assets


def test_get_model_dry_run(mocker: MockerFixture) -> None:
    ai_worker.model_instance = None
    ai_worker.HAS_MODEL = True

    mocker.patch.dict(sys.modules, {"sentence_transformers": None})
    res = get_model()
    assert res is None
    assert ai_worker.HAS_MODEL is False


def test_get_model_success(mocker: MockerFixture) -> None:
    ai_worker.model_instance = None
    ai_worker.HAS_MODEL = True

    mock_st = MagicMock()
    mocker.patch.dict(sys.modules, {"sentence_transformers": mock_st})
    res = get_model()
    assert res is not None
    assert ai_worker.HAS_MODEL is True


@pytest.mark.asyncio
async def test_process_pending_assets_no_tasks(
    mocker: MockerFixture,
) -> None:
    mock_session = AsyncMock()
    mocker.patch(
        "backend.workers.ai_worker.AsyncSessionLocal",
        return_value=mock_session,
    )
    mock_session.__aenter__.return_value = mock_session

    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = []
    mock_session.execute.return_value = mock_result

    count = await process_pending_assets()
    assert count == 0


@pytest.mark.asyncio
async def test_process_pending_assets_success(
    mocker: MockerFixture,
) -> None:
    mock_session = AsyncMock()
    mocker.patch(
        "backend.workers.ai_worker.AsyncSessionLocal",
        return_value=mock_session,
    )
    mock_session.__aenter__.return_value = mock_session

    mock_asset = MagicMock()
    mock_asset.embedding_status = "pending"
    mock_asset.asset_type = "image/jpeg"
    mock_asset.file_path = "/tmp/fake.jpg"

    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [mock_asset]
    mock_session.execute.return_value = mock_result

    mocker.patch("backend.workers.ai_worker.get_model", return_value=MagicMock())
    ai_worker.HAS_MODEL = True

    mocker.patch("backend.workers.ai_worker.Path.exists", return_value=True)
    mocker.patch("backend.workers.ai_worker.Image.open")

    count = await process_pending_assets()
    assert count == 1
    assert mock_asset.embedding_status == "done"


@pytest.mark.asyncio
async def test_process_pending_assets_no_model(
    mocker: MockerFixture,
) -> None:
    mock_session = AsyncMock()
    mocker.patch(
        "backend.workers.ai_worker.AsyncSessionLocal",
        return_value=mock_session,
    )
    mock_session.__aenter__.return_value = mock_session

    mock_asset = MagicMock()
    mock_asset.embedding_status = "pending"
    mock_asset.asset_type = "image/jpeg"

    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [mock_asset]
    mock_session.execute.return_value = mock_result

    mocker.patch("backend.workers.ai_worker.get_model", return_value=None)
    ai_worker.HAS_MODEL = False

    count = await process_pending_assets()
    assert count == 0
    assert mock_asset.embedding_status == "failed"
