# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
api/portability.py 单元测试 — 安全粉碎 secure_shred_file。

高 ROI：验证文件覆写行为、超时降级、空文件处理。
零真实文件系统依赖：使用 tmp_path fixture。
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest


class TestSecureShredFile:
    """secure_shred_file 物理覆写验证。"""

    def test_nonexistent_file_returns_true(self, tmp_path: Path) -> None:
        """不存在的文件 → 返回 True（幂等）。"""
        from backend.api.portability import secure_shred_file

        result = secure_shred_file(str(tmp_path / "ghost.txt"))
        assert result is True

    @patch("backend.api.portability.subprocess.run")
    def test_shred_command_called_first(self, mock_run: object, tmp_path: Path) -> None:
        """Linux 环境优先调用 shred 命令。"""
        from backend.api.portability import secure_shred_file

        f = tmp_path / "test.bin"
        f.write_bytes(b"secret data 1234")
        import subprocess

        mock_run.side_effect = subprocess.CalledProcessError(1, "shred")  # type: ignore[attr-defined]

        # shred 失败后会 fallback 到 Python 覆写
        result = secure_shred_file(str(f))
        # 文件应该被删除
        assert result is True
        assert not f.exists()

    def test_python_fallback_overwrites_content(self, tmp_path: Path) -> None:
        """shred 不可用时，Python fallback 必须真正覆写磁道。"""
        from backend.api.portability import secure_shred_file

        f = tmp_path / "secret.bin"
        original = b"top secret data that must be destroyed"
        f.write_bytes(original)

        # Mock shred 为 FileNotFoundError（模拟 Linux 无 shred 工具）
        with patch(
            "backend.api.portability.subprocess.run",
            side_effect=FileNotFoundError("shred not found"),
        ):
            result = secure_shred_file(str(f))

        assert result is True
        # 文件应已被 unlink
        assert not f.exists()

    def test_empty_file_direct_delete(self, tmp_path: Path) -> None:
        """空文件 → 直接删除，不执行覆写。"""
        from backend.api.portability import secure_shred_file

        f = tmp_path / "empty.bin"
        f.write_bytes(b"")

        with patch(
            "backend.api.portability.subprocess.run",
            side_effect=FileNotFoundError("shred not found"),
        ):
            result = secure_shred_file(str(f))

        assert result is True
        assert not f.exists()

    def test_multi_pass_default_three(self, tmp_path: Path) -> None:
        """默认 3 次覆写 + 最后全零。"""
        from backend.api.portability import secure_shred_file

        f = tmp_path / "multi.bin"
        f.write_bytes(b"A" * 4096)

        with patch(
            "backend.api.portability.subprocess.run",
            side_effect=FileNotFoundError("no shred"),
        ):
            result = secure_shred_file(str(f), passes=3)

        assert result is True
        assert not f.exists()

    @patch("backend.api.portability.subprocess.run")
    def test_shred_timeout_returns_false(self, mock_run: object, tmp_path: Path) -> None:
        """shred 超时 → 返回 False（不吞没错误）。"""
        import subprocess

        from backend.api.portability import secure_shred_file

        f = tmp_path / "timeout.bin"
        f.write_bytes(b"data")

        mock_run.side_effect = subprocess.TimeoutExpired("shred", 30.0)  # type: ignore[attr-defined]
        result = secure_shred_file(str(f))
        assert result is False


@pytest.mark.asyncio
async def test_zip_stream_generator_scopes_asset_query_by_tenant() -> None:
    from backend.api.portability import zip_stream_generator

    session = AsyncMock()
    result = MagicMock()
    result.scalars.return_value.all.return_value = []
    session.execute.return_value = result

    chunks = []
    async for chunk in zip_stream_generator(session, "tenant-a", "42"):
        chunks.append(chunk)

    rendered = str(session.execute.await_args.args[0])
    assert "assets.tenant_id" in rendered
    assert "assets.is_deleted" in rendered
