# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
单元测试：AI 路由代理。

覆盖 check_idempotency_lock 幂等锁、超时熔断（30s 断崖）、
儿童/长辈角色 prompt 覆写、cloud 路由变轨。
全部 Mock，不需要 Redis/AI 后端。
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock

import pytest

# -------------------- check_idempotency_lock --------------------


class TestIdempotencyLock:
    """幂等性锁验证。"""

    @pytest.mark.asyncio
    async def test_lock_acquired_returns_true(self) -> None:
        """Redis SET NX 成功（锁获取成功）应返回 True。"""
        from backend.ai_router import check_idempotency_lock

        redis = AsyncMock()
        redis.set = AsyncMock(return_value=True)

        request = MagicMock()
        request.app.state.redis = redis

        result = await check_idempotency_lock(request, "key-001")
        assert result is True
        redis.set.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_lock_already_held_returns_false(self) -> None:
        """Redis SET NX 返回 False（锁已被持有）应返回 False。"""
        from backend.ai_router import check_idempotency_lock

        redis = AsyncMock()
        redis.set = AsyncMock(return_value=False)

        request = MagicMock()
        request.app.state.redis = redis

        result = await check_idempotency_lock(request, "key-002")
        assert result is False

    @pytest.mark.asyncio
    async def test_redis_none_returns_true_degraded(self) -> None:
        """Redis 不可用时应降级放行（返回 True）。"""
        from backend.ai_router import check_idempotency_lock

        request = MagicMock()
        request.app.state.redis = None

        result = await check_idempotency_lock(request, "key-003")
        assert result is True

    @pytest.mark.asyncio
    async def test_redis_error_returns_true_degraded(self) -> None:
        """Redis 操作抛异常时应降级放行。"""
        from backend.ai_router import check_idempotency_lock

        redis = AsyncMock()
        redis.set = AsyncMock(side_effect=ConnectionError("redis down"))

        request = MagicMock()
        request.app.state.redis = redis

        result = await check_idempotency_lock(request, "key-004")
        assert result is True

    @pytest.mark.asyncio
    async def test_lock_key_format(self) -> None:
        """锁 key 应包含 zen70:ai:idemp: 前缀。"""
        from backend.ai_router import check_idempotency_lock

        redis = AsyncMock()
        redis.set = AsyncMock(return_value=True)

        request = MagicMock()
        request.app.state.redis = redis

        await check_idempotency_lock(request, "my-unique-key")

        # 安全提取 key：优先 kwargs["name"]，其次 args[0]，无则断言失败
        call_args = redis.set.call_args
        if call_args.kwargs and "name" in call_args.kwargs:
            actual_key = call_args.kwargs["name"]
        elif call_args.args:
            actual_key = call_args.args[0]
        else:
            raise AssertionError(f"redis.set 未传入 key 参数: {call_args}")
        assert actual_key == "zen70:ai:idemp:my-unique-key"


# -------------------- MULTIMODAL_TIMEOUT_SECONDS --------------------


class TestTimeout:
    """法典 4.0 显存熔断超时配置。"""

    def test_timeout_value_is_positive(self) -> None:
        """超时值必须为正数。"""
        from backend.ai_router import MULTIMODAL_TIMEOUT_SECONDS

        assert MULTIMODAL_TIMEOUT_SECONDS > 0

    def test_timeout_value_reasonable(self) -> None:
        """超时值应在合理范围内（≤60s）。"""
        from backend.ai_router import MULTIMODAL_TIMEOUT_SECONDS

        assert MULTIMODAL_TIMEOUT_SECONDS <= 60


# -------------------- 配置安全性 --------------------


class TestAIRouterConfig:
    """AI 路由配置安全性。"""

    def test_http_client_has_connection_limits(self) -> None:
        """全局 HTTP 客户端必须配置连接池上限。"""
        from backend.ai_router import http_client

        # httpx 内部结构不稳定，安全提取连接池限制
        transport = getattr(http_client, "_transport", None)
        assert transport is not None, "http_client 缺少 _transport"
        pool = getattr(transport, "_pool", None)
        if pool is not None:
            max_conn = getattr(pool, "_max_connections", None)
            if max_conn is not None:
                assert max_conn <= 200, f"连接池上限 {max_conn} 超过 200"

    def test_router_prefix(self) -> None:
        """路由前缀应为 /api/v1/ai。"""
        from backend.ai_router import router

        assert router.prefix == "/api/v1/ai"
