# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated test module. Manual modifications may be overwritten by IaC compiler.
"""
单元测试：JWT 双轨轮转 (CURRENT / PREVIOUS 密钥)。

验证当前密钥签发与验证、旧密钥仍可验证并签发新 Token、
无效密钥拒绝、生产环境缺失密钥 fail-fast、50% 寿命自动续签。
纯内存测试，不需要外部服务。
"""

from __future__ import annotations

from datetime import timedelta
from typing import Any
from unittest.mock import patch

import pytest

# 在导入被测模块之前先 Patch 环境变量，避免模块级别读取到错误值


class TestJwtDualTrack:
    """JWT 双轨轮转测试套件。"""

    @pytest.fixture(autouse=True)
    def _patch_jwt_secrets(self) -> Any:
        """为每个测试统一 patch JWT 密钥常量。"""
        with patch.dict(
            "os.environ",
            {
                "JWT_SECRET_CURRENT": "test-current-secret-at-least-32-bytes-0001",
                "JWT_SECRET_PREVIOUS": "test-previous-secret-at-least-32-bytes-0001",
                "JWT_ACCESS_TOKEN_EXPIRE_MINUTES": "15",
                "ZEN70_ENV": "",
            },
        ):
            # 强制重新加载 jwt 模块以使用新环境变量
            import importlib

            import backend.core.jwt as jwt_mod

            importlib.reload(jwt_mod)
            self.jwt_mod = jwt_mod
            yield

    @pytest.mark.asyncio
    async def test_create_and_decode_current_secret(self) -> None:
        """用当前密钥签发的 token 可正常解码，无 new_token。"""
        data = {"sub": "user1", "username": "alice", "role": "admin"}
        token = self.jwt_mod.create_access_token(data)  # type: ignore[arg-type]
        payload, new_token = await self.jwt_mod.decode_token(token)

        assert payload["sub"] == "user1"
        assert payload["username"] == "alice"
        assert payload["role"] == "admin"
        # 刚签发的 token 未过半寿命，不应产生 new_token
        assert new_token is None

    @pytest.mark.asyncio
    async def test_previous_secret_accepted_with_new_token(self) -> None:
        """用旧密钥签发的 token 可解码，并返回新 token（X-New-Token）。"""
        data = {"sub": "user2", "username": "bob", "role": "family"}
        token = self.jwt_mod.create_access_token(data, use_current_secret=False)  # type: ignore[arg-type]
        payload, new_token = await self.jwt_mod.decode_token(token)

        assert payload["sub"] == "user2"
        # 旧密钥验证通过必定产生 new_token
        assert new_token is not None
        assert isinstance(new_token, str)
        assert len(new_token) > 10

    @pytest.mark.asyncio
    async def test_new_token_from_previous_is_valid(self) -> None:
        """旧密钥触发的 new_token 用当前密钥可正常解码。"""
        data = {"sub": "user3", "username": "carol", "role": "admin"}
        old_token = self.jwt_mod.create_access_token(data, use_current_secret=False)  # type: ignore[arg-type]
        _, new_token = await self.jwt_mod.decode_token(old_token)
        assert new_token is not None

        # 新 token 应可用当前密钥直接解码
        payload2, new_token2 = await self.jwt_mod.decode_token(new_token)
        assert payload2["sub"] == "user3"
        assert payload2["username"] == "carol"
        # 刚签发的新 token 不应再产生 new_token
        assert new_token2 is None

    @pytest.mark.asyncio
    async def test_invalid_secret_rejected(self) -> None:
        """用完全无关的密钥签发的 token 应被拒绝（401）。"""
        import jwt as pyjwt
        from fastapi import HTTPException

        bad_token = pyjwt.encode(
            {"sub": "hacker", "exp": 9999999999},
            "totally-wrong-secret-at-least-32-bytes",
            algorithm="HS256",
        )

        with pytest.raises(HTTPException) as exc_info:
            await self.jwt_mod.decode_token(bad_token)

        assert exc_info.value.status_code == 401

    @pytest.mark.asyncio
    async def test_empty_token_rejected(self) -> None:
        """空 token 应被拒绝（401）。"""
        from fastapi import HTTPException

        with pytest.raises(HTTPException) as exc_info:
            await self.jwt_mod.decode_token("")

        assert exc_info.value.status_code == 401

    @pytest.mark.asyncio
    async def test_expired_token_rejected(self) -> None:
        """过期 token 应被拒绝（401）。"""
        from fastapi import HTTPException

        data = {"sub": "user4", "username": "dave", "role": "family"}
        token = self.jwt_mod.create_access_token(data, expires_delta=timedelta(seconds=-10))  # type: ignore[arg-type]

        with pytest.raises(HTTPException) as exc_info:
            await self.jwt_mod.decode_token(token)

        assert exc_info.value.status_code == 401

    @pytest.mark.asyncio
    async def test_half_lifespan_auto_renew(self) -> None:
        """超过 50% 寿命的 token 应自动产生 new_token。"""
        from datetime import datetime, timezone

        import jwt as pyjwt

        now = datetime.now(timezone.utc).timestamp()
        # 签发已过半寿命的 token：iat=20分钟前, exp=10分钟后 → 已过 66%
        payload = {
            "sub": "user5",
            "username": "eve",
            "role": "admin",
            "iat": now - 1200,  # 20分钟前
            "exp": now + 600,  # 10分钟后
        }
        current_secret = self.jwt_mod._CURRENT
        token = pyjwt.encode(payload, current_secret, algorithm="HS256")

        result_payload, new_token = await self.jwt_mod.decode_token(token)
        assert result_payload["sub"] == "user5"
        # 已过半寿命，应产生 new_token
        assert new_token is not None

    def test_production_env_requires_secret(self) -> None:
        """生产环境缺少 JWT_SECRET_CURRENT 应 fail-fast (RuntimeError)。"""
        import importlib

        with patch.dict(
            "os.environ",
            {
                "ZEN70_ENV": "production",
                "JWT_SECRET_CURRENT": "",
                "JWT_SECRET": "",
                "JWT_SECRET_PREVIOUS": "",
            },
        ):
            with pytest.raises(RuntimeError, match="JWT_SECRET_CURRENT"):
                import backend.core.jwt as jwt_mod

                importlib.reload(jwt_mod)

    def test_expire_seconds_from_env(self) -> None:
        """get_access_token_expire_seconds 应返回配置的分钟数 × 60。"""
        result = self.jwt_mod.get_access_token_expire_seconds()
        assert result == 15 * 60  # JWT_ACCESS_TOKEN_EXPIRE_MINUTES=15

    def test_runtime_ready_rejects_insecure_default_secret(self) -> None:
        import importlib

        with patch.dict(
            "os.environ",
            {
                "ZEN70_ENV": "development",
                "JWT_SECRET_CURRENT": "",
                "JWT_SECRET": "",
                "JWT_SECRET_PREVIOUS": "",
            },
        ):
            import backend.core.jwt as jwt_mod

            importlib.reload(jwt_mod)
            with pytest.raises(RuntimeError, match="insecure default secret"):
                jwt_mod.assert_jwt_runtime_ready()
