# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
api/scenes.py 单元测试 — 场景 Pydantic 契约、触发类型、动作约束。

高 ROI：验证场景动作的边界约束和执行逻辑。
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError


class TestSceneActionModel:
    """SceneAction Pydantic 模型验证。"""

    def test_valid_action(self) -> None:
        from backend.api.scenes import SceneAction

        a = SceneAction(switch="living_room_light", state="ON")  # type: ignore[call-arg]
        assert a.switch == "living_room_light"
        assert a.state == "ON"
        assert a.delay_ms == 0

    def test_action_with_delay(self) -> None:
        from backend.api.scenes import SceneAction

        a = SceneAction(switch="fan", state="OFF", delay_ms=5000)
        assert a.delay_ms == 5000

    def test_delay_max_30_seconds(self) -> None:
        from backend.api.scenes import SceneAction

        with pytest.raises(ValidationError):
            SceneAction(switch="x", state="ON", delay_ms=30001)

    def test_delay_no_negative(self) -> None:
        from backend.api.scenes import SceneAction

        with pytest.raises(ValidationError):
            SceneAction(switch="x", state="ON", delay_ms=-1)


class TestSceneCreateRequest:
    """SceneCreateRequest 验证。"""

    def test_valid_create(self) -> None:
        from backend.api.scenes import SceneAction, SceneCreateRequest

        req = SceneCreateRequest(  # type: ignore[call-arg]
            name="晚安模式",
            actions=[SceneAction(switch="light", state="OFF")],  # type: ignore[call-arg]
        )
        assert req.name == "晚安模式"
        assert req.trigger_type == "manual"
        assert req.cron_expr is None
        assert len(req.actions) == 1

    def test_name_too_long(self) -> None:
        from backend.api.scenes import SceneAction, SceneCreateRequest

        with pytest.raises(ValidationError):
            SceneCreateRequest(  # type: ignore[call-arg]
                name="x" * 129,
                actions=[SceneAction(switch="a", state="ON")],  # type: ignore[call-arg]
            )

    def test_empty_actions_rejected(self) -> None:
        from backend.api.scenes import SceneCreateRequest

        with pytest.raises(ValidationError):
            SceneCreateRequest(name="test", actions=[])  # type: ignore[call-arg]

    def test_trigger_type_validation(self) -> None:
        from backend.api.scenes import SceneAction, SceneCreateRequest

        for tt in ["manual", "schedule", "event"]:
            req = SceneCreateRequest(  # type: ignore[call-arg]
                name="test",
                actions=[SceneAction(switch="a", state="ON")],  # type: ignore[call-arg]
                trigger_type=tt,
            )
            assert req.trigger_type == tt

    def test_invalid_trigger_type_rejected(self) -> None:
        from backend.api.scenes import SceneAction, SceneCreateRequest

        with pytest.raises(ValidationError):
            SceneCreateRequest(  # type: ignore[call-arg]
                name="test",
                actions=[SceneAction(switch="a", state="ON")],  # type: ignore[call-arg]
                trigger_type="invalid",
            )


class TestSceneUpdateRequest:
    """SceneUpdateRequest 部分更新验证。"""

    def test_all_none_is_valid(self) -> None:
        from backend.api.scenes import SceneUpdateRequest

        req = SceneUpdateRequest()  # type: ignore[call-arg]
        assert req.name is None
        assert req.actions is None

    def test_partial_update(self) -> None:
        from backend.api.scenes import SceneUpdateRequest

        req = SceneUpdateRequest(name="新名称", is_active=False)  # type: ignore[call-arg]
        assert req.name == "新名称"
        assert req.is_active is False


class TestSceneResponse:
    """SceneResponse 模型。"""

    def test_response_fields(self) -> None:
        from backend.api.scenes import SceneResponse

        resp = SceneResponse(
            id=1,
            name="test",
            description="desc",
            icon="🏠",
            actions=[{"switch": "light", "state": "ON"}],
            trigger_type="manual",
            cron_expr=None,
            is_active=True,
            created_by=1,
        )
        assert resp.id == 1
        assert resp.is_active is True

    def test_execute_response(self) -> None:
        from backend.api.scenes import SceneExecuteResponse

        resp = SceneExecuteResponse(
            scene_id=1,
            scene_name="test",
            execution_id="abc123",
            actions_dispatched=3,
            status="dispatched",
        )
        assert resp.actions_dispatched == 3
        assert resp.status == "dispatched"
