# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
单元测试：HTTP 中间件。

覆盖 RequestIDMiddleware、global_readonly_lock、limit_request_body、
success_envelope、add_request_id 废弃函数。
全部 Mock，不需要 Redis/FastAPI 运行时。
"""

from __future__ import annotations

import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi.responses import JSONResponse
from starlette.responses import Response

# -------------------- RequestIDMiddleware --------------------


class TestRequestIDMiddleware:
    """X-Request-ID 注入中间件。"""

    @pytest.mark.asyncio
    async def test_generates_request_id_when_missing(self) -> None:
        """无上游 X-Request-ID 时应自动生成。"""
        from backend.middleware import RequestIDMiddleware

        middleware = RequestIDMiddleware(app=MagicMock())

        request = MagicMock()
        request.headers = {}
        request.state = MagicMock()

        mock_response = MagicMock()
        mock_response.headers = {}
        call_next = AsyncMock(return_value=mock_response)

        await middleware.dispatch(request, call_next)

        # 应设置到 request.state 和响应头
        assert hasattr(request.state, "request_id")
        assert request.state.request_id is not None
        assert len(request.state.request_id) > 0
        assert mock_response.headers["X-Request-ID"] == request.state.request_id

    @pytest.mark.asyncio
    async def test_reuses_upstream_request_id(self) -> None:
        """上游已传 X-Request-ID 时应复用。"""
        from backend.middleware import RequestIDMiddleware

        middleware = RequestIDMiddleware(app=MagicMock())

        request = MagicMock()
        request.headers = {"X-Request-ID": "upstream-rid-001"}
        request.state = MagicMock()

        mock_response = MagicMock()
        mock_response.headers = {}
        call_next = AsyncMock(return_value=mock_response)

        await middleware.dispatch(request, call_next)

        assert request.state.request_id == "upstream-rid-001"
        assert mock_response.headers["X-Request-ID"] == "upstream-rid-001"

    @pytest.mark.asyncio
    async def test_supports_x_trace_id_fallback(self) -> None:
        """X-Trace-Id 也应被识别为 request_id。"""
        from backend.middleware import RequestIDMiddleware

        middleware = RequestIDMiddleware(app=MagicMock())

        request = MagicMock()
        request.headers = {"X-Trace-Id": "trace-abc"}
        request.state = MagicMock()

        mock_response = MagicMock()
        mock_response.headers = {}
        call_next = AsyncMock(return_value=mock_response)

        await middleware.dispatch(request, call_next)

        assert request.state.request_id == "trace-abc"


# -------------------- limit_request_body --------------------


class TestLimitRequestBody:
    """请求体大小限制中间件。"""

    @pytest.mark.asyncio
    async def test_rejects_oversized_post(self) -> None:
        """POST 请求体超限应返回 413。"""
        from backend.middleware import limit_request_body

        request = MagicMock()
        request.method = "POST"
        request.headers = {"content-length": "999999999"}
        request.state = MagicMock()

        call_next = AsyncMock()
        response = await limit_request_body(request, call_next)

        assert response.status_code == 413
        call_next.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_allows_small_post(self) -> None:
        """POST 请求体未超限应放行。"""
        from backend.middleware import limit_request_body

        request = MagicMock()
        request.method = "POST"
        request.headers = {"content-length": "1024"}
        request.state = MagicMock()

        expected_response = MagicMock()
        call_next = AsyncMock(return_value=expected_response)
        response = await limit_request_body(request, call_next)

        assert response is expected_response
        call_next.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_get_bypasses_limit(self) -> None:
        """GET 请求不检查 body 限制。"""
        from backend.middleware import limit_request_body

        request = MagicMock()
        request.method = "GET"
        request.headers = {"content-length": "999999999"}
        request.state = MagicMock()

        expected_response = MagicMock()
        call_next = AsyncMock(return_value=expected_response)
        response = await limit_request_body(request, call_next)

        assert response is expected_response

    @pytest.mark.asyncio
    async def test_invalid_content_length_passes(self) -> None:
        """Content-Length 非数字时应放行（不崩溃）。"""
        from backend.middleware import limit_request_body

        request = MagicMock()
        request.method = "POST"
        request.headers = {"content-length": "not-a-number"}
        request.state = MagicMock()

        expected_response = MagicMock()
        call_next = AsyncMock(return_value=expected_response)
        response = await limit_request_body(request, call_next)

        assert response is expected_response


# -------------------- global_readonly_lock --------------------


class TestGlobalReadOnlyLock:
    """UPS 全局只读熔断中间件。"""

    @pytest.mark.asyncio
    async def test_get_passes_through(self) -> None:
        """GET 请求不受只读锁影响。"""
        from backend.middleware import global_readonly_lock

        request = MagicMock()
        request.method = "GET"
        request.url = MagicMock()
        request.url.path = "/api/v1/health"

        expected_response = MagicMock()
        call_next = AsyncMock(return_value=expected_response)

        with patch("backend.middleware.service_readiness", {}):
            response = await global_readonly_lock(request, call_next)

        assert response is expected_response

    @pytest.mark.asyncio
    async def test_post_blocked_when_ups_low_battery_lru(self) -> None:
        """UPS LOW_BATTERY_SHUTDOWN 时 POST 应返回 503。"""
        from backend.capabilities import CapabilityItem
        from backend.middleware import global_readonly_lock

        ups_cap = CapabilityItem(status="low-battery-shutdown", enabled=False)  # type: ignore[call-arg]
        matrix = {"ups": ups_cap}

        request = MagicMock()
        request.method = "POST"
        request.url = MagicMock()
        request.url.path = "/api/v1/data"
        request.state = MagicMock()

        call_next = AsyncMock()

        with patch("backend.middleware.get_lru_matrix", return_value=matrix):
            with patch("backend.middleware.service_readiness", {}):
                response = await global_readonly_lock(request, call_next)

        assert response.status_code == 503
        call_next.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_post_passes_when_ups_online(self) -> None:
        """UPS 正常时 POST 应放行。"""
        from backend.capabilities import CapabilityItem
        from backend.middleware import global_readonly_lock

        ups_cap = CapabilityItem(status="online", enabled=True)  # type: ignore[call-arg]
        matrix = {"ups": ups_cap}

        request = MagicMock()
        request.method = "POST"
        request.url = MagicMock()
        request.url.path = "/api/v1/data"
        request.state = MagicMock()

        expected_response = MagicMock()
        call_next = AsyncMock(return_value=expected_response)

        with patch("backend.middleware.get_lru_matrix", return_value=matrix):
            with patch("backend.middleware.service_readiness", {}):
                response = await global_readonly_lock(request, call_next)

        assert response is expected_response

    @pytest.mark.asyncio
    async def test_service_not_ready_returns_503(self) -> None:
        """探针标记服务未就绪时，匹配路径应返回 503。"""
        from backend.middleware import global_readonly_lock

        request = MagicMock()
        request.method = "GET"
        request.url = MagicMock()
        request.url.path = "/api/v1/jellyfin/status"
        request.state = MagicMock()

        call_next = AsyncMock()

        # jellyfin 未就绪
        with patch("backend.middleware.get_lru_matrix", return_value=None):
            with patch("backend.middleware.service_readiness", {"jellyfin": False}):
                response = await global_readonly_lock(request, call_next)

        assert response.status_code == 503
        call_next.assert_not_awaited()


# -------------------- success_envelope --------------------
# 注意：权威实现在 backend.api.main（@app.middleware("http") 挂载）
# backend.middleware 中的旧实现已删除


class TestSuccessEnvelope:
    """成功 JSON 响应 envelope 包装（测试运行时权威实现 backend.api.main）。"""

    @pytest.mark.asyncio
    async def test_wraps_json_success(self) -> None:
        """200 JSON 响应应被包装为 {code, message, data} envelope。"""
        from backend.api.main import success_envelope

        request = MagicMock()
        request.url = MagicMock()
        request.url.path = "/api/v1/test"
        request.state = MagicMock()
        request.state.request_id = "rid-001"

        inner_body = json.dumps({"items": [1, 2, 3]}).encode("utf-8")

        async def body_iter() -> object:
            yield inner_body

        inner = Response(
            content=inner_body,
            status_code=200,
            media_type="application/json",
        )
        inner.body_iterator = body_iter()  # type: ignore[attr-defined]

        async def mock_call_next(_req: object) -> Response:
            return inner

        response = await success_envelope(request, mock_call_next)
        body = json.loads(response.body.decode("utf-8"))

        assert body["code"] == "ZEN-OK-0"
        assert body["message"] == "ok"
        assert body["data"] == {"items": [1, 2, 3]}

    @pytest.mark.asyncio
    async def test_skips_error_responses(self) -> None:
        """4xx/5xx 响应不应被包装。"""
        from backend.api.main import success_envelope

        request = MagicMock()
        request.url = MagicMock()
        request.url.path = "/api/v1/test"
        request.state = MagicMock()

        error_resp = JSONResponse(content={"error": "bad"}, status_code=400)

        async def mock_call_next(_req: object) -> Response:
            return error_resp

        response = await success_envelope(request, mock_call_next)
        assert response.status_code == 400

    @pytest.mark.asyncio
    async def test_skips_non_json(self) -> None:
        """非 JSON Content-Type 响应不应被包装。"""
        from backend.api.main import success_envelope

        request = MagicMock()
        request.url = MagicMock()
        request.url.path = "/api/v1/test"
        request.state = MagicMock()

        html_resp = Response(content="<html></html>", media_type="text/html")

        async def mock_call_next(_req: object) -> Response:
            return html_resp

        response = await success_envelope(request, mock_call_next)
        assert response.media_type == "text/html"

    @pytest.mark.asyncio
    async def test_skips_already_enveloped(self) -> None:
        """已包含 code=ZEN-OK-0 的响应不应重复包装。"""
        from backend.api.main import success_envelope

        request = MagicMock()
        request.url = MagicMock()
        request.url.path = "/api/v1/test"
        request.state = MagicMock()

        enveloped_body = json.dumps(
            {
                "code": "ZEN-OK-0",
                "message": "ok",
                "data": {"x": 1},
            }
        ).encode("utf-8")

        async def body_iter() -> object:
            yield enveloped_body

        enveloped = Response(
            content=enveloped_body,
            status_code=200,
            media_type="application/json",
        )
        enveloped.body_iterator = body_iter()  # type: ignore[attr-defined]

        async def mock_call_next(_req: object) -> Response:
            return enveloped

        response = await success_envelope(request, mock_call_next)
        body = json.loads(response.body.decode("utf-8"))
        # 不应被二次包装
        assert body.get("code") == "ZEN-OK-0"
        assert body["data"] == {"x": 1}


# -------------------- add_request_id 废弃函数 --------------------


class TestAddRequestIdDeprecated:
    """add_request_id 废弃函数。"""

    def test_raises_runtime_error(self) -> None:
        """调用废弃函数应抛出 RuntimeError。"""
        from backend.middleware import add_request_id

        with pytest.raises(RuntimeError, match="deprecated"):
            add_request_id()
