# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
单元测试：structured_logging 模块。

验证 JsonFormatter 输出合法 JSON、包含必要字段（timestamp/level/logger/caller/message/X-Request-ID）、
get_logger 返回 LoggerAdapter 并挂载 JsonFormatter。
纯内存测试，不需要外部服务。
"""

from __future__ import annotations

import json
import logging
import sys

import backend.middleware  # noqa: F401
from backend.core.structured_logging import JsonFormatter, get_logger


class TestJsonFormatter:
    """JsonFormatter 输出格式验证。"""

    def test_output_is_valid_json(self) -> None:
        """format() 输出必须为合法 JSON 单行。"""
        fmt = JsonFormatter()
        record = logging.LogRecord(
            name="test",
            level=logging.INFO,
            pathname="test.py",
            lineno=42,
            msg="hello %s",
            args=("world",),
            exc_info=None,
        )
        output = fmt.format(record)
        parsed = json.loads(output)
        assert isinstance(parsed, dict)

    def test_contains_required_fields(self) -> None:
        """输出 JSON 必须包含 timestamp/level/logger/caller/message/X-Request-ID。"""
        fmt = JsonFormatter()
        record = logging.LogRecord(
            name="zen70.test",
            level=logging.WARNING,
            pathname="/app/test.py",
            lineno=10,
            msg="test message",
            args=(),
            exc_info=None,
        )
        parsed = json.loads(fmt.format(record))
        assert "timestamp" in parsed
        assert parsed["level"] == "WARNING"
        assert parsed["logger"] == "zen70.test"
        assert "test.py:10" in parsed["caller"]
        assert parsed["message"] == "test message"
        assert "X-Request-ID" in parsed

    def test_timestamp_is_utc_iso8601(self) -> None:
        """timestamp 必须为 UTC ISO 8601 格式，以 Z 结尾。"""
        fmt = JsonFormatter()
        record = logging.LogRecord(
            name="t",
            level=logging.INFO,
            pathname="t.py",
            lineno=1,
            msg="t",
            args=(),
            exc_info=None,
        )
        parsed = json.loads(fmt.format(record))
        assert parsed["timestamp"].endswith("Z")
        assert "+" not in parsed["timestamp"]

    def test_request_id_injected_from_record(self) -> None:
        """record 上有 request_id 属性时必须注入到 X-Request-ID。"""
        fmt = JsonFormatter()
        record = logging.LogRecord(
            name="t",
            level=logging.INFO,
            pathname="t.py",
            lineno=1,
            msg="t",
            args=(),
            exc_info=None,
        )
        record.request_id = "rid-abc-123"
        parsed = json.loads(fmt.format(record))
        assert parsed["X-Request-ID"] == "rid-abc-123"

    def test_request_id_none_when_missing(self) -> None:
        """record 上无 request_id 属性时，X-Request-ID 应为 None/null。"""
        fmt = JsonFormatter()
        record = logging.LogRecord(
            name="t",
            level=logging.INFO,
            pathname="t.py",
            lineno=1,
            msg="t",
            args=(),
            exc_info=None,
        )
        parsed = json.loads(fmt.format(record))
        assert parsed["X-Request-ID"] is None

    def test_exception_info_captured(self) -> None:
        """exc_info 存在时必须输出 exception 字段。"""
        fmt = JsonFormatter()
        try:
            raise ValueError("boom")
        except ValueError:
            record = logging.LogRecord(
                name="t",
                level=logging.ERROR,
                pathname="t.py",
                lineno=1,
                msg="fail",
                args=(),
                exc_info=sys.exc_info(),
            )
        parsed = json.loads(fmt.format(record))
        assert "exception" in parsed
        assert "ValueError" in parsed["exception"]
        assert "boom" in parsed["exception"]

    def test_chinese_message_not_escaped(self) -> None:
        """中文消息不应被 ASCII 转义（ensure_ascii=False）。"""
        fmt = JsonFormatter()
        record = logging.LogRecord(
            name="t",
            level=logging.INFO,
            pathname="t.py",
            lineno=1,
            msg="磁盘已满",
            args=(),
            exc_info=None,
        )
        output = fmt.format(record)
        assert "磁盘已满" in output
        assert "\\u" not in output


class TestGetLogger:
    """get_logger 工厂函数验证。"""

    def test_returns_logger_adapter(self) -> None:
        """必须返回 LoggerAdapter 实例。"""
        lg = get_logger("test.module1")
        assert isinstance(lg, logging.LoggerAdapter)

    def test_handler_uses_json_formatter(self) -> None:
        """底层 handler 必须使用 JsonFormatter。"""
        lg = get_logger("test.module2_unique")
        base = lg.logger
        assert len(base.handlers) >= 1
        assert isinstance(base.handlers[0].formatter, JsonFormatter)

    def test_default_level_is_info(self) -> None:
        """默认日志级别必须为 INFO。"""
        lg = get_logger("test.module3_unique")
        assert lg.logger.level == logging.INFO

    def test_request_id_auto_generated_when_none(self) -> None:
        """request_id 为 None 时应自动生成 UUID。"""
        lg = get_logger("test.module4_unique", request_id=None)
        assert "request_id_override" in lg.extra  # type: ignore[operator]
        assert len(lg.extra["request_id_override"]) > 0  # type: ignore[arg-type, index]

    def test_request_id_preserved_when_provided(self) -> None:
        """提供 request_id 时应原样保留。"""
        lg = get_logger("test.module5_unique", request_id="custom-rid-999")
        assert lg.extra["request_id_override"] == "custom-rid-999"  # type: ignore[index]

    def test_request_id_override_does_not_conflict_with_log_record_factory(self) -> None:
        """Adapter extra should cooperate with the global request-id log record factory."""
        handler = logging.Handler()
        captured: dict[str, object] = {}

        def emit(record: logging.LogRecord) -> None:
            captured["request_id"] = getattr(record, "request_id", None)
            captured["_zen_request_id"] = getattr(record, "_zen_request_id", None)

        handler.emit = emit  # type: ignore[method-assign]
        lg = get_logger("test.module6_unique", request_id="custom-rid-123")
        base = lg.logger
        original_handlers = list(base.handlers)
        base.handlers = [handler]
        try:
            lg.info("hello")
        finally:
            base.handlers = original_handlers

        assert captured["request_id"] == "custom-rid-123"
        assert captured["_zen_request_id"] == "custom-rid-123"
