# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
单元测试：后台 Worker — Bit-Rot 巡检与 SRE 探针。

覆盖 _scan_and_hash_file 腐败检测、_init_bitrot_db 创建、
health_probe_worker 连续 3 次失败触发 RESTART。
全部 Mock/tmp，不需要外部服务。
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

# -------------------- _scan_and_hash_file --------------------


class TestScanAndHashFile:
    """Bit-Rot 文件哈希扫描。"""

    def test_first_scan_creates_baseline(self, tmp_path: Path) -> None:
        """首次扫描应在 SQLite 中创建基线记录。"""
        from backend.background_tasks import _scan_and_hash_file

        db_path = tmp_path / "test_bitrot.db"
        test_file = tmp_path / "video.mp4"
        test_file.write_text("INITIAL_DATA", encoding="utf-8")

        # 初始化 DB
        conn = sqlite3.connect(db_path)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS file_hashes (
                filepath TEXT PRIMARY KEY, sha256 TEXT NOT NULL, last_checked REAL NOT NULL
            )
        """
        )
        conn.commit()
        conn.close()

        result = _scan_and_hash_file(test_file, db_path)
        assert result is None  # 首次扫描无告警

        conn = sqlite3.connect(db_path)
        row = conn.execute("SELECT sha256 FROM file_hashes WHERE filepath = ?", (str(test_file),)).fetchone()
        conn.close()
        assert row is not None
        assert len(row[0]) == 64  # SHA256 hex

    def test_detects_bit_rot(self, tmp_path: Path) -> None:
        """文件内容改变（大小不变模拟腐败）应返回告警。"""
        from backend.background_tasks import _scan_and_hash_file

        db_path = tmp_path / "test_bitrot.db"
        test_file = tmp_path / "data.bin"
        test_file.write_text("AAAA", encoding="utf-8")

        conn = sqlite3.connect(db_path)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS file_hashes (
                filepath TEXT PRIMARY KEY, sha256 TEXT NOT NULL, last_checked REAL NOT NULL
            )
        """
        )
        conn.commit()
        conn.close()

        # 首次扫描建基线
        _scan_and_hash_file(test_file, db_path)

        # 篡改内容（模拟静默腐败）
        test_file.write_text("BBBB", encoding="utf-8")

        result = _scan_and_hash_file(test_file, db_path)
        assert result is not None
        assert "静默数据腐败" in result or "重大警告" in result

    def test_unchanged_file_returns_none(self, tmp_path: Path) -> None:
        """未变更文件重复扫描应返回 None（无告警）。"""
        from backend.background_tasks import _scan_and_hash_file

        db_path = tmp_path / "test_bitrot.db"
        test_file = tmp_path / "stable.bin"
        test_file.write_text("STABLE_DATA", encoding="utf-8")

        conn = sqlite3.connect(db_path)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS file_hashes (
                filepath TEXT PRIMARY KEY, sha256 TEXT NOT NULL, last_checked REAL NOT NULL
            )
        """
        )
        conn.commit()
        conn.close()

        _scan_and_hash_file(test_file, db_path)
        result = _scan_and_hash_file(test_file, db_path)
        assert result is None

    def test_nonexistent_file_returns_error(self, tmp_path: Path) -> None:
        """不存在的文件应返回错误信息（不崩溃）。"""
        from backend.background_tasks import _scan_and_hash_file

        db_path = tmp_path / "test_bitrot.db"
        conn = sqlite3.connect(db_path)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS file_hashes (
                filepath TEXT PRIMARY KEY, sha256 TEXT NOT NULL, last_checked REAL NOT NULL
            )
        """
        )
        conn.commit()
        conn.close()

        result = _scan_and_hash_file(Path("/nonexistent/file.bin"), db_path)
        assert result is not None
        assert "failed" in result.lower()


# -------------------- SRE 探针配置 --------------------


class TestHealthProbeConfig:
    """SRE 探针配置。"""

    def test_microservice_health_urls_is_dict(self) -> None:
        """_microservices_health_urls 应为 dict。"""
        from backend.background_tasks import _microservices_health_urls

        assert isinstance(_microservices_health_urls, dict)

    def test_bitrot_db_path_is_path(self) -> None:
        """BITROT_DB_PATH 应为 Path 对象。"""
        from backend.background_tasks import BITROT_DB_PATH

        assert isinstance(BITROT_DB_PATH, Path)

    def test_bitrot_scan_dirs_is_list(self) -> None:
        """BITROT_SCAN_DIRS 应为 list。"""
        from backend.background_tasks import BITROT_SCAN_DIRS

        assert isinstance(BITROT_SCAN_DIRS, list)


# -------------------- service_readiness / liveness --------------------


class TestServiceState:
    """共享状态字典。"""

    def test_service_readiness_is_dict(self) -> None:
        """service_readiness 应为可变 dict。"""
        from backend.shared_state import service_readiness

        assert isinstance(service_readiness, dict)

    def test_service_liveness_fails_is_dict(self) -> None:
        """service_liveness_fails 应为可变 dict。"""
        from backend.shared_state import service_liveness_fails

        assert isinstance(service_liveness_fails, dict)
