GO_NATIVE_PERSONA = "go-native"
PYTHON_RUNNER_PERSONA = "python-runner"
SHELL_PERSONA = "shell"
SWIFT_NATIVE_PERSONA = "swift-native"
KOTLIN_NATIVE_PERSONA = "kotlin-native"
VECTOR_WORKER_PERSONA = "vector-worker"
SEARCH_SERVICE_PERSONA = "search-service"
UNKNOWN_PERSONA = "unknown"

__all__ = (
    "GO_NATIVE_PERSONA",
    "PYTHON_RUNNER_PERSONA",
    "SHELL_PERSONA",
    "SWIFT_NATIVE_PERSONA",
    "KOTLIN_NATIVE_PERSONA",
    "VECTOR_WORKER_PERSONA",
    "SEARCH_SERVICE_PERSONA",
    "UNKNOWN_PERSONA",
)
