/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 * @description 离线存储服务
 * 读写 ZEN70Cache 中的能力矩阵，提供统一的数据源
 */
import { db, CAPABILITIES_ROW_ID } from "@/db";
import type { Capabilities } from "@/types/capability";

/** 离线缓存最大有效期：24 小时 */
const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

async function safe<T>(fn: () => Promise<T>, fallback: T): Promise<T> {
  try {
    return await fn();
  } catch {
    return fallback;
  }
}

/** 写入能力矩阵到 IndexedDB */
export async function saveCapabilities(data: Capabilities): Promise<void> {
  await safe(
    () =>
      db.capabilities.put({
        id: CAPABILITIES_ROW_ID,
        data,
        lastUpdated: Date.now(),
      }),
    undefined
  );
}

/** 离线缓存加载结果 */
export interface CachedResult {
  data: Capabilities;
  /** 缓存是否已超过 TTL（数据仍可用，但可能已过期） */
  isStale: boolean;
}

/** 从 IndexedDB 读取能力矩阵，附带 TTL 过期标记 */
export async function loadCapabilities(): Promise<CachedResult | null> {
  const row = await safe(() => db.capabilities.get(CAPABILITIES_ROW_ID), null);
  if (!row?.data) return null;
  const isStale = Date.now() - row.lastUpdated > CACHE_TTL_MS;
  return { data: row.data, isStale };
}

