# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from backend.kernel.scheduling.gen_grpc import placement_pb2 as placement__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in placement_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PlacementSolverStub(object):
    """PlacementSolver assigns pending jobs to nodes."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Solve = channel.unary_unary(
            "/placement.PlacementSolver/Solve",
            request_serializer=placement__pb2.SolveRequest.SerializeToString,
            response_deserializer=placement__pb2.SolveResponse.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/placement.PlacementSolver/Health",
            request_serializer=placement__pb2.HealthRequest.SerializeToString,
            response_deserializer=placement__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class PlacementSolverServicer(object):
    """PlacementSolver assigns pending jobs to nodes."""

    def Solve(self, request, context):
        """Solve computes job→node assignments for a dispatch window."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Health returns server liveness for readiness probes."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PlacementSolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Solve": grpc.unary_unary_rpc_method_handler(
            servicer.Solve,
            request_deserializer=placement__pb2.SolveRequest.FromString,
            response_serializer=placement__pb2.SolveResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=placement__pb2.HealthRequest.FromString,
            response_serializer=placement__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("placement.PlacementSolver", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("placement.PlacementSolver", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PlacementSolver(object):
    """PlacementSolver assigns pending jobs to nodes."""

    @staticmethod
    def Solve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/placement.PlacementSolver/Solve",
            placement__pb2.SolveRequest.SerializeToString,
            placement__pb2.SolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/placement.PlacementSolver/Health",
            placement__pb2.HealthRequest.SerializeToString,
            placement__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
