# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
集成测试：认证全流程。

验证 PIN 登录 → JWT 签发 → 受保护端点访问 → Token 刷新。
需要运行中的 Gateway + Redis。
"""

from __future__ import annotations

import pytest
import requests

from tests.integration.conftest import BASE_URL, GATEWAY_OK, REDIS_OK, _no_proxy


@pytest.mark.integration
@pytest.mark.skipif(not GATEWAY_OK, reason="Gateway not available")
class TestAuthFlowE2E:
    """认证流程端到端集成测试。"""

    def test_no_token_returns_401_or_403(self) -> None:
        """无 Token 访问受保护接口应返回 401 或 403。"""
        resp = requests.get(
            f"{BASE_URL}/api/v1/settings/flags",
            timeout=5,
            proxies=_no_proxy(),
        )
        assert resp.status_code in (401, 403), f"Expected auth error, got {resp.status_code}"
        body = resp.json()
        assert "code" in body
        assert body["code"].startswith("ZEN-")

    def test_invalid_token_rejected(self) -> None:
        """伪造 Token 应被拒绝。"""
        resp = requests.get(
            f"{BASE_URL}/api/v1/settings/flags",
            headers={"Authorization": "Bearer fake.invalid.token"},
            timeout=5,
            proxies=_no_proxy(),
        )
        assert resp.status_code in (401, 403, 422)

    def test_malformed_auth_header_rejected(self) -> None:
        """格式错误的 Authorization 头应被拒绝（不崩溃）。"""
        for bad_header in ["", "Bearer", "Basic dXNlcjpwYXNz", "NotBearer token"]:
            resp = requests.get(
                f"{BASE_URL}/api/v1/settings/flags",
                headers={"Authorization": bad_header},
                timeout=5,
                proxies=_no_proxy(),
            )
            assert resp.status_code in (401, 403, 422), (
                f"Bad header '{bad_header}' should be rejected, got {resp.status_code}"
            )

    def test_pin_endpoint_exists(self) -> None:
        """PIN 登录端点应存在（即使返回 400/422 因为缺 body）。"""
        resp = requests.post(
            f"{BASE_URL}/api/v1/auth/pin/login",
            json={"username": "__test__", "pin": "000000"},
            timeout=5,
            proxies=_no_proxy(),
        )
        # 端点存在但 PIN 错误 → 401/403/503；不存在 → 404
        assert resp.status_code != 404, "PIN auth endpoint not found at /api/v1/auth/pin/login"

    def test_pin_wrong_returns_401(self) -> None:
        """错误 PIN 码应返回 401。"""
        resp = requests.post(
            f"{BASE_URL}/api/v1/auth/pin/login",
            json={"username": "__test__", "pin": "000000"},
            timeout=5,
            proxies=_no_proxy(),
        )
        # 错误 PIN → 401；参数错误 → 422；DB 不可用 → 503
        assert resp.status_code in (401, 403, 422, 503)

    def test_error_response_has_recovery_hint(self) -> None:
        """认证错误响应必须包含 recovery_hint 帮助前端引导用户。"""
        resp = requests.get(
            f"{BASE_URL}/api/v1/settings/flags",
            timeout=5,
            proxies=_no_proxy(),
        )
        if resp.status_code in (401, 403):
            body = resp.json()
            assert "recovery_hint" in body, f"Auth error missing recovery_hint: {body}"
