# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
"""
集成测试：中间件链端到端。

验证 RequestIDMiddleware → limit_request_body → global_readonly_lock
→ metrics_middleware → success_envelope 全链协同。
需要运行中的 Gateway。
"""

from __future__ import annotations

import uuid

import pytest
import requests

from tests.integration.conftest import BASE_URL, GATEWAY_OK, _no_proxy


@pytest.mark.integration
@pytest.mark.skipif(not GATEWAY_OK, reason="Gateway not available")
class TestMiddlewareChainE2E:
    """中间件链端到端集成测试。"""

    def test_full_chain_request_id_propagation(self) -> None:
        """X-Request-ID 从请求注入 → 贯穿中间件链 → 响应头回传 → 响应体 details 中出现。"""
        custom_rid = f"chain-test-{uuid.uuid4()}"
        resp = requests.get(
            f"{BASE_URL}/api/v1/capabilities",
            headers={"X-Request-ID": custom_rid},
            timeout=5,
            proxies=_no_proxy(),
        )
        assert resp.status_code == 200
        # 响应头回传
        returned_rid = resp.headers.get("X-Request-ID", resp.headers.get("x-request-id", ""))
        assert returned_rid == custom_rid, f"Request-ID not echoed: {returned_rid}"

    def test_envelope_wraps_capabilities(self) -> None:
        """success_envelope 将 capabilities 原始 dict 包裹为 {code, message, data}。"""
        resp = requests.get(
            f"{BASE_URL}/api/v1/capabilities",
            timeout=5,
            proxies=_no_proxy(),
        )
        assert resp.status_code == 200
        body = resp.json()
        assert body["code"] == "ZEN-OK-0"
        assert body["message"] == "ok"
        assert isinstance(body["data"], dict)

    def test_body_limit_rejects_oversized_post(self) -> None:
        """limit_request_body 拒绝超限 POST（>10MB）。"""
        oversized = b"A" * (11 * 1024 * 1024)
        resp = requests.post(
            f"{BASE_URL}/api/v1/capabilities",
            data=oversized,
            timeout=15,
            proxies=_no_proxy(),
        )
        # 可能 413（body 超限）或 405（不允许 POST）
        assert resp.status_code in (405, 413)

    def test_404_returns_error_envelope(self) -> None:
        """不存在的端点返回标准 ErrorResponse envelope。"""
        resp = requests.get(
            f"{BASE_URL}/api/v1/_nonexistent_test_route",
            timeout=5,
            proxies=_no_proxy(),
        )
        assert resp.status_code in (404, 405)
        body = resp.json()
        assert "code" in body
        assert "message" in body
        assert "recovery_hint" in body or "details" in body

    def test_health_endpoint_bypasses_envelope(self) -> None:
        """健康检查端点可能不走 envelope（或走也行），但必须返回 200。"""
        resp = requests.get(
            f"{BASE_URL}/health",
            timeout=5,
            proxies=_no_proxy(),
        )
        assert resp.status_code == 200
        body = resp.json()
        assert "status" in body or "code" in body

    def test_concurrent_requests_unique_ids(self) -> None:
        """并发请求应各自获得独立的 X-Request-ID。"""
        import concurrent.futures

        ids: list[str] = []

        def _fire() -> str:
            r = requests.get(
                f"{BASE_URL}/api/v1/capabilities",
                timeout=5,
                proxies=_no_proxy(),
            )
            return r.headers.get("X-Request-ID", r.headers.get("x-request-id", ""))

        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as pool:
            futures = [pool.submit(_fire) for _ in range(5)]
            for f in concurrent.futures.as_completed(futures):
                rid = f.result()
                assert rid, "Missing X-Request-ID"
                ids.append(rid)

        # 所有 ID 应唯一
        assert len(set(ids)) == len(ids), f"Duplicate Request-IDs: {ids}"
