# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
"""Queue lane and worker-pool contracts for scheduler control plane.

Revision ID: e6f7a8b9c0d1
Revises: b7c8d9e0f1a2, d4e5f6a7b8c9
Create Date: 2026-04-01 00:30:00.000000
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "e6f7a8b9c0d1"
down_revision: Union[str, Sequence[str], None] = ("b7c8d9e0f1a2", "d4e5f6a7b8c9")
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _inspector() -> sa.Inspector:
    return sa.inspect(op.get_bind())


def _has_table(table_name: str) -> bool:
    return _inspector().has_table(table_name)


def _has_column(table_name: str, column_name: str) -> bool:
    return any(column["name"] == column_name for column in _inspector().get_columns(table_name))


def _has_index(table_name: str, index_name: str) -> bool:
    return any(index["name"] == index_name for index in _inspector().get_indexes(table_name))


def _add_column_if_missing(table_name: str, column: sa.Column[object]) -> None:
    if _has_table(table_name) and not _has_column(table_name, column.name):
        op.add_column(table_name, column)


def _drop_column_if_exists(table_name: str, column_name: str) -> None:
    if _has_table(table_name) and _has_column(table_name, column_name):
        op.drop_column(table_name, column_name)


def _create_index_if_missing(table_name: str, index_name: str, columns: list[str]) -> None:
    if _has_table(table_name) and not _has_index(table_name, index_name):
        op.create_index(index_name, table_name, columns)


def _drop_index_if_exists(table_name: str, index_name: str) -> None:
    if _has_table(table_name) and _has_index(table_name, index_name):
        op.drop_index(index_name, table_name=table_name)


def _backfill_job_queue_contracts() -> None:
    op.execute(
        sa.text(
            """
            UPDATE jobs
            SET queue_class = CASE
                WHEN COALESCE(required_gpu_vram_mb, 0) > 0 THEN 'gpu-heavy'
                WHEN kind IN ('ml.inference', 'media.transcode') THEN 'gpu-heavy'
                WHEN LOWER(COALESCE(kind, '')) LIKE '%analytics%'
                  OR LOWER(COALESCE(kind, '')) LIKE '%report%'
                  OR LOWER(COALESCE(kind, '')) LIKE '%summary%'
                  OR LOWER(COALESCE(kind, '')) LIKE '%aggregate%'
                  OR LOWER(COALESCE(kind, '')) LIKE '%rollup%'
                  OR LOWER(COALESCE(kind, '')) LIKE '%timeseries%'
                  OR LOWER(COALESCE(source, '')) LIKE '%analytics%'
                  OR LOWER(COALESCE(source, '')) LIKE '%report%'
                  OR LOWER(COALESCE(source, '')) LIKE '%summary%'
                  OR LOWER(COALESCE(source, '')) LIKE '%aggregate%'
                  OR LOWER(COALESCE(source, '')) LIKE '%rollup%'
                  OR LOWER(COALESCE(source, '')) LIKE '%timeseries%' THEN 'analytics'
                WHEN kind IN ('iot.collect', 'healthcheck') THEN 'realtime'
                WHEN kind IN ('connector.invoke', 'http.request', 'wasm.run') THEN 'interactive'
                ELSE 'batch'
            END
            WHERE queue_class IS NULL
            """
        )
    )
    op.execute(sa.text("UPDATE jobs SET worker_pool = queue_class WHERE worker_pool IS NULL"))


def _ensure_job_queue_contract_schema() -> None:
    _add_column_if_missing("jobs", sa.Column("queue_class", sa.String(length=32), nullable=True))
    _add_column_if_missing("jobs", sa.Column("worker_pool", sa.String(length=64), nullable=True))
    if _has_table("jobs"):
        _backfill_job_queue_contracts()
        op.alter_column("jobs", "queue_class", existing_type=sa.String(length=32), nullable=False, server_default="batch")
        op.alter_column("jobs", "worker_pool", existing_type=sa.String(length=64), nullable=False, server_default="batch")
    _create_index_if_missing("jobs", "ix_jobs_queue_class", ["queue_class"])
    _create_index_if_missing("jobs", "ix_jobs_worker_pool", ["worker_pool"])


def _ensure_node_worker_pool_schema() -> None:
    _add_column_if_missing(
        "nodes",
        sa.Column("worker_pools", sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )


def upgrade() -> None:
    _ensure_job_queue_contract_schema()
    _ensure_node_worker_pool_schema()


def downgrade() -> None:
    _drop_index_if_exists("jobs", "ix_jobs_worker_pool")
    _drop_index_if_exists("jobs", "ix_jobs_queue_class")
    _drop_column_if_exists("nodes", "worker_pools")
    _drop_column_if_exists("jobs", "worker_pool")
    _drop_column_if_exists("jobs", "queue_class")
