# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
"""Add software_evaluations table for all-branch all-software evaluation feature.

Revision ID: f1a2b3c4d5e6
Revises: e6f7a8b9c0d1
Create Date: 2026-04-02 23:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f1a2b3c4d5e6"
down_revision: str | Sequence[str] | None = "e6f7a8b9c0d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _inspector() -> sa.Inspector:
    return sa.inspect(op.get_bind())


def _has_table(table_name: str) -> bool:
    return _inspector().has_table(table_name)


def upgrade() -> None:
    if not _has_table("software_evaluations"):
        op.create_table(
            "software_evaluations",
            sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
            sa.Column("tenant_id", sa.String(64), nullable=False, index=True, server_default="default"),
            sa.Column("evaluation_id", sa.String(128), nullable=False, index=True),
            sa.Column("software_id", sa.String(128), nullable=False, index=True),
            sa.Column("branch", sa.String(128), nullable=False, index=True, server_default="main"),
            sa.Column("rating", sa.Integer, nullable=False),
            sa.Column("category", sa.String(64), nullable=False, index=True, server_default="general"),
            sa.Column("comment", sa.Text, nullable=True),
            sa.Column("evaluator", sa.String(128), nullable=False, server_default=""),
            sa.Column("status", sa.String(32), nullable=False, index=True, server_default="submitted"),
            sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
            sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
            sa.UniqueConstraint(
                "tenant_id",
                "evaluation_id",
                name="ux_software_evaluations_tenant_eval_id",
            ),
        )


def downgrade() -> None:
    if _has_table("software_evaluations"):
        op.drop_table("software_evaluations")
