# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
ZEN70 Tenant 聚合根模型 (ADR-0047 WP-P2b)。

设计约束:
- 最小可行根：tenant_id / display_name / plan / is_active / created_at / metadata_json
- 不引入复杂关联、不做多 home 设计、不做联邦配额
- 后续 multi-home、Home 对象、配额联邦等特性在此基础上扩展
"""

from __future__ import annotations

import datetime

from sqlalchemy import Boolean, DateTime, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from backend.models.user import Base


class Tenant(Base):
    """
    ZEN70 租户聚合根表（最小可行版）。

    所有业务对象通过 tenant_id 外键关联到此表。
    这个表让 tenant 从"隐式根"升格为"一等建模对象"，
    为后续平台治理、配额联邦、多 home 扩展提供稳定挂载点。

    激活状态: ✅ Active (control-plane)
    """

    __tablename__ = "tenants"

    # 主键 — 与其余表的 tenant_id: String(64) 保持类型一致
    tenant_id: Mapped[str] = mapped_column(String(64), primary_key=True)

    # 对外展示名（如 "我的家" / "Home Alpha"）
    display_name: Mapped[str] = mapped_column(String(128), nullable=False, default="Home")

    # 套餐/计划类型（如 "home" / "pro" / "enterprise"）
    plan: Mapped[str] = mapped_column(String(32), nullable=False, default="home")

    # 租户是否处于活动状态
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # 创建时间（法典 2.4: UTC 标准时间）
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.datetime.now(datetime.UTC).replace(tzinfo=None),
        nullable=False,
    )

    # 扩展元数据（保留给后续功能，如时区偏好、通知配置等）
    metadata_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True, default=dict)
