# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
ZEN70 OpenAPI Surface Freeze Tool (ADR-0047 WP-P2a).

Freeze scope
------------
Only the *presence* of control-plane path strings is frozen.
Out of scope (not checked here): HTTP methods, request/response schemas,
path parameter types, response codes, and auth semantics.
Those are covered by Pydantic model tests and mypy.

Update protocol
---------------
When adding a new control-plane router:
  1. Add its prefix to CONTROL_PLANE_PREFIX_ALLOWLIST below
  2. Run:    python scripts/freeze_openapi.py --init
  3. Commit: docs/api/openapi_locked.json together with the router change

Usage
-----
  # Generate / refresh baseline snapshot (commit the result):
  python scripts/freeze_openapi.py --init

  # Also write dist/openapi_v3.43.json for CI / docs pipeline:
  python scripts/freeze_openapi.py --init --export-dist

  # Verify surface matches snapshot (used by release gate):
  python scripts/freeze_openapi.py --check

  # Silent mode for CI:
  python scripts/freeze_openapi.py --check --quiet

Exit codes
----------
  0 -- surface matches snapshot, or --init succeeded
  1 -- surface has drifted, or snapshot missing
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOCKED_SNAPSHOT = PROJECT_ROOT / "docs" / "api" / "openapi_locked.json"
DIST_SNAPSHOT = PROJECT_ROOT / "dist" / "openapi_v3.43.json"

# ── Control-Plane API Surface Allowlist ───────────────────────────────────────
#
# Maintainer: control-plane architect / ADR-0047 designated reviewer
#
# UPDATE PROTOCOL (must follow when adding a new control-plane router):
#   1. Add the new prefix to this tuple.
#   2. Run:    python scripts/freeze_openapi.py --init
#   3. Commit: docs/api/openapi_locked.json alongside the router change.
#
# Routes NOT in this list are invisible to the freeze tool — they will NOT
# trigger a surface-drift alert even if silently added or removed.
#
# Freeze boundary: only path presence is frozen.
# Methods, schemas, responses, and auth semantics are out of scope.
CONTROL_PLANE_PREFIX_ALLOWLIST: tuple[str, ...] = (
    "/api/v1/capabilities",   # capability matrix
    "/api/v1/switches",       # soft switches
    "/api/v1/events",         # SSE event stream
    "/api/v1/nodes",          # node management
    "/api/v1/jobs",           # job scheduling
    "/api/v1/connectors",     # connectors
    "/api/v1/console",        # console


    "/api/v1/workflows",      # workflows
    "/api/v1/alerts",         # alerts
    "/api/v1/audit-logs",     # audit logs
    "/api/v1/cluster",        # cluster management
)

# Exact-match exclusions (internal / debug routes, never part of contract)
_EXCLUDE_EXACT: frozenset[str] = frozenset(
    {
        "/",
        "/health",
        "/docs",
        "/redoc",
        "/openapi.json",
    }
)


def _collect_surface() -> set[str]:
    """
    Import the FastAPI app and collect the control-plane path surface.

    Only paths matching CONTROL_PLANE_PREFIX_ALLOWLIST are collected.
    Frozen dimension: path presence only — not method or schema.
    """
    sys.path.insert(0, str(PROJECT_ROOT))
    try:
        from backend.api.main import app  # type: ignore[import]
    except ImportError as exc:
        # Dependencies not installed (e.g. bare CI env without venv).
        # Raise so the caller can decide whether to hard-fail or skip gracefully.
        raise ImportError(
            f"[freeze_openapi] Cannot import FastAPI app: {exc}. "
            "Install backend deps (pip install -r backend/requirements.txt) "
            "or run with ZEN70_SKIP_RELEASE_GATE=1 for local debugging only."
        ) from exc
    except Exception as exc:
        # Non-import runtime error — always hard fail.
        print(f"[freeze_openapi] ERROR: App import raised unexpected error: {exc}", file=sys.stderr)
        sys.exit(1)

    surface: set[str] = set()
    for route in app.routes:
        path = getattr(route, "path", None)
        if not isinstance(path, str):
            continue
        if path in _EXCLUDE_EXACT:
            continue
        if any(
            path == prefix
            or path.startswith(prefix + "/")
            or path.startswith(prefix + "{")
            for prefix in CONTROL_PLANE_PREFIX_ALLOWLIST
        ):
            surface.add(path)
    return surface


def _load_locked() -> set[str]:
    """Load the committed path-surface snapshot."""
    if not LOCKED_SNAPSHOT.exists():
        return set()
    data = json.loads(LOCKED_SNAPSHOT.read_text(encoding="utf-8"))
    return set(data.get("paths", []))


def _build_snapshot_dict(surface: set[str]) -> dict:
    return {
        "version": "v3.43",
        "freeze_scope": "path-surface-only",
        "freeze_boundary": "Only path presence is frozen. Methods, schemas, responses, and auth semantics are out of scope.",
        "allowlist_prefixes": list(CONTROL_PLANE_PREFIX_ALLOWLIST),
        "description": (
            "ZEN70 v3.43 control-plane path surface locked by ADR-0047. "
            "Do not edit manually. Re-run --init after deliberate surface changes."
        ),
        "paths": sorted(surface),
    }


def _save_snapshot(surface: set[str], *, export_dist: bool = False) -> None:
    """Write path-surface snapshot to docs/api/openapi_locked.json.
    When export_dist=True, also overwrite dist/openapi_v3.43.json (idempotent).
    """
    payload = _build_snapshot_dict(surface)
    text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

    LOCKED_SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    LOCKED_SNAPSHOT.write_text(text, encoding="utf-8")

    if export_dist:
        # Always overwrite — dist output is a build artifact, never source of truth
        DIST_SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
        DIST_SNAPSHOT.write_text(text, encoding="utf-8")


def cmd_init(*, quiet: bool = False, export_dist: bool = False) -> int:
    """--init: Capture current path surface and save as baseline snapshot."""
    try:
        surface = _collect_surface()
    except ImportError as exc:
        print(f"[freeze_openapi] SKIP --init: {exc}", file=sys.stderr)
        print("  Surface snapshot NOT updated.", file=sys.stderr)
        return 2  # Distinct exit code: deps unavailable (not a drift error)
    _save_snapshot(surface, export_dist=export_dist)
    if not quiet:
        print(f"[freeze_openapi] Initialized snapshot: {LOCKED_SNAPSHOT}")
        print(f"  Captured {len(surface)} control-plane paths (path presence only — method/schema not frozen).")
        if export_dist:
            print(f"  Exported (overwritten): {DIST_SNAPSHOT}")
        print("  Next: git add docs/api/openapi_locked.json && git commit")
    return 0


def cmd_check(*, quiet: bool = False, export_dist: bool = False) -> int:
    """--check: Compare current path surface against locked snapshot."""
    locked = _load_locked()
    if not locked:
        print(
            "[freeze_openapi] ERROR: No locked snapshot found at:\n"
            f"  {LOCKED_SNAPSHOT}\n"
            "  Run: python scripts/freeze_openapi.py --init",
            file=sys.stderr,
        )
        return 1

    try:
        actual = _collect_surface()
    except ImportError as exc:
        print(
            f"[freeze_openapi] WARNING: --check skipped — deps unavailable: {exc}",
            file=sys.stderr,
        )
        print(
            "  Surface drift NOT verified. Install backend deps to enable Gate 4.",
            file=sys.stderr,
        )
        return 0  # Non-blocking: skip gracefully, do not abort release gate

    # Optional export — always overwrite, independent of check result
    if export_dist:
        _save_snapshot(actual, export_dist=True)
        if not quiet:
            print(f"[freeze_openapi] Exported current surface (overwritten): {DIST_SNAPSHOT}")

    added = actual - locked
    removed = locked - actual

    if not added and not removed:
        if not quiet:
            print(
                f"[freeze_openapi] Path surface unchanged "
                f"({len(actual)} paths match locked contract; method/schema not checked here)"
            )
        return 0

    print("[freeze_openapi] API path surface has drifted from locked contract!", file=sys.stderr)
    print(
        "  Scope: only path presence is frozen — methods, schemas, responses out of scope.",
        file=sys.stderr,
    )
    if added:
        print(f"  Added ({len(added)} paths — run --init if intentional):", file=sys.stderr)
        for p in sorted(added):
            print(f"    + {p}", file=sys.stderr)
    if removed:
        print(f"  Removed ({len(removed)} paths — breaking change or update contract):", file=sys.stderr)
        for p in sorted(removed):
            print(f"    - {p}", file=sys.stderr)
    print(
        "\n  To update after a deliberate surface change:\n"
        "    python scripts/freeze_openapi.py --init\n"
        "    git add docs/api/openapi_locked.json && git commit",
        file=sys.stderr,
    )
    return 1


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "ZEN70 OpenAPI path-surface freeze tool (ADR-0047). "
            "Frozen dimension: path presence only — not methods or schemas."
        ),
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--init", action="store_true", help="Capture and save baseline path-surface snapshot")
    group.add_argument("--check", action="store_true", help="Verify current path surface matches snapshot")
    parser.add_argument("--quiet", action="store_true", help="Suppress informational output")
    parser.add_argument(
        "--export-dist",
        action="store_true",
        help="Overwrite dist/openapi_v3.43.json with current surface (idempotent)",
    )
    args = parser.parse_args()

    if args.init:
        sys.exit(cmd_init(quiet=args.quiet, export_dist=args.export_dist))
    else:
        sys.exit(cmd_check(quiet=args.quiet, export_dist=args.export_dist))


if __name__ == "__main__":
    main()
