"""
ZEN70 Domain Registry Markdown Generator.

从 backend/models/domain_registry.json（事实来源）生成
backend/models/DOMAIN_REGISTRY.md（展示层）。

用法:
    python scripts/generate_domain_registry_md.py

DOMAIN_REGISTRY.md 不应手动编辑。
修改域边界时：先改 domain_registry.json，再跑此脚本，再提交两个文件。
"""

from __future__ import annotations

import json
import textwrap
from datetime import UTC, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_JSON = PROJECT_ROOT / "backend" / "models" / "domain_registry.json"
REGISTRY_MD = PROJECT_ROOT / "backend" / "models" / "DOMAIN_REGISTRY.md"


_STATUS_ICON = {True: "✅ Active", False: "⛔ Inactive"}


def _render_md(registry: dict) -> str:
    schema_ver = registry.get("_schema_version", "?")
    adr = registry.get("_adr", "")
    domains = registry.get("domains", {})
    models = registry.get("models", [])
    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines: list[str] = []

    lines.append(textwrap.dedent(f"""\
        <!-- AUTO-GENERATED — do not edit manually.
             Source of truth: domain_registry.json (schema v{schema_ver}, {adr})
             Regenerate with: python scripts/generate_domain_registry_md.py
             Last generated: {now} -->

        # ZEN70 Domain Registry

        > **⚠️ This file is auto-generated from [`domain_registry.json`](./domain_registry.json).**
        > Do not edit this file directly. All changes must go through the JSON source.
        > Run `python scripts/generate_domain_registry_md.py` to regenerate.

        ---

        ## Domain Taxonomy
        """))

    lines.append("| Domain | Description | Activation |")
    lines.append("|---|---|---|")
    for name, info in domains.items():
        reqs = info.get("default_activation_requirements", [])
        reqs_str = ", ".join(f"`{r}`" for r in reqs) if reqs else "—"
        lines.append(f"| `{name}` | {info['description']} | {info['activation']} ({reqs_str}) |")
    lines.append("")

    lines.append("---\n")
    lines.append("## Model Registry\n")
    lines.append("| File | Path | Domain | Status | Notes |")
    lines.append("|---|---|---|---|---|")

    for entry in models:
        fname = entry["file"]
        fpath = entry["path"]
        domain = entry["domain"]
        active = entry.get("active", False)
        status = _STATUS_ICON[active]
        notes_parts: list[str] = []
        if entry.get("blocked_by"):
            notes_parts.append("blocked: " + ", ".join(f"`{b}`" for b in entry["blocked_by"]))
        if not active and entry.get("activation_requirements"):
            reqs = entry["activation_requirements"]
            notes_parts.append("needs: " + ", ".join(f"`{r}`" for r in reqs))
        notes = "; ".join(notes_parts) if notes_parts else "—"
        lines.append(f"| `{fname}` | `{fpath}` | `{domain}` | {status} | {notes} |")

    lines.append("")
    lines.append("---\n")
    lines.append(textwrap.dedent("""\
        ## Activating a business-layer Model

        1. Create a corresponding API route file and register it in `backend/control_plane/app/router_admission.py`
        2. Write an Alembic migration creating the table
        3. **In `domain_registry.json`**: set `"active": true`, remove `"blocked_by"` if present
        4. Run `python scripts/generate_domain_registry_md.py` to regenerate this file
        5. Add a domain upgrade entry to `CHANGELOG.md`

        > Skipping step 3 means the packaging script will still exclude the model,
        > regardless of any changes made to this Markdown file.
        """))

    return "\n".join(lines)


def main() -> None:
    registry = json.loads(REGISTRY_JSON.read_text(encoding="utf-8"))
    md = _render_md(registry)
    REGISTRY_MD.write_text(md, encoding="utf-8")
    print(f"[generate_domain_registry_md] Generated: {REGISTRY_MD}")
    print(f"  Source: {REGISTRY_JSON} (schema v{registry.get('_schema_version', '?')})")


if __name__ == "__main__":
    main()
