# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
ZEN70 V3.0 完整安装包打包脚本。

将项目根目录下运行安装所需的所有文件打为 zip（不含机密、不含重复子项目）。
解压后可执行 start_installer.py 图形化部署或 scripts/bootstrap.py 命令行点火；
前端须在编排前执行 cd frontend && npm ci && npm run build（见 docs/zen70_v3.0/DEPLOYMENT_GUIDE.md）。

用法（在项目根目录执行）:
    python scripts/package_install_v3.py

输出:
    dist/ZEN70_v3.0_Install.zip

可选环境变量:
    ZEN70_INSTALL_ZIP  -- 覆盖输出路径
    ZEN70_INSTALL_INCLUDE_FRONTEND_DIST  -- 设为 1 时一并打包 frontend/dist（开箱即用，包体积更大）
"""

from __future__ import annotations

import logging
import os
import sys
import zipfile
from pathlib import Path

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ZIP = PROJECT_ROOT / "dist" / "ZEN70_v3.0_Install.zip"

# 排除目录（不打包）
IGNORE_DIRS = frozenset(
    {
        ".git",
        "node_modules",
        "venv",
        ".venv",
        "__pycache__",
        ".pytest_cache",
        "dist",  # 输出目录，避免把已有 zip 打进去
        "zen70_v3.0_sre_hardened",  # 子项目副本，避免重复
        ".cursor",
        "out",
        "out_test",
    }
)

# 排除文件（不打包）
IGNORE_FILES = frozenset(
    {
        ".DS_Store",
        "Thumbs.db",
        ".env",  # 机密不落包（法典）
        "*.pyc",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
    }
)

# 排除后缀
IGNORE_SUFFIXES = (".pyc", ".pyo", ".lock")


def _should_skip_file(name: str, path: Path) -> bool:
    if name in IGNORE_FILES:
        return True
    if any(name.endswith(s) for s in IGNORE_SUFFIXES):
        return True
    if name == ".env" and path.is_file():
        return True
    return False


def main() -> None:
    env_zip = os.environ.get("ZEN70_INSTALL_ZIP")
    out_zip = Path(env_zip) if env_zip else DEFAULT_ZIP
    include_frontend_dist = os.environ.get("ZEN70_INSTALL_INCLUDE_FRONTEND_DIST", "").strip() == "1"

    out_zip.parent.mkdir(parents=True, exist_ok=True)
    source = PROJECT_ROOT

    logger.info("打包完整安装包: %s -> %s", source, out_zip)
    logger.info("排除: .git, node_modules, venv, __pycache__, dist, .env, zen70_v3.0_sre_hardened 等")
    if not include_frontend_dist:
        logger.info("未包含 frontend/dist，解压后请执行: cd frontend && npm ci && npm run build")
    else:
        logger.info("已包含 frontend/dist（开箱即用）")

    count = 0
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for file_path in source.rglob("*"):
            if not file_path.is_file():
                continue

            try:
                rel_path = file_path.relative_to(source)
            except ValueError:
                continue

            # Skip dist output dir explicitly to avoid recursive packing
            if rel_path.parts and rel_path.parts[0] == "dist":
                continue

            if any(part in IGNORE_DIRS for part in rel_path.parts[:-1]):
                continue

            # 未显式包含时跳过 frontend/dist，减小体积且符合“编排前构建”的文档约定
            if not include_frontend_dist and "frontend" in rel_path.parts and "dist" in rel_path.parts:
                continue

            if _should_skip_file(file_path.name, file_path):
                continue

            zf.write(file_path, rel_path)
            count += 1

    logger.info("完成: %s（共 %s 个文件）", out_zip, count)


if __name__ == "__main__":
    main()
    if sys.platform == "win32":
        try:
            input("按回车键退出...")
        except (EOFError, KeyboardInterrupt):
            pass
