#!/usr/bin/env python3
# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
ZEN70 零停机更新引擎 (Zero-Downtime Update Engine)。

法典 1.3 / 2.5 / 3.5 强制：
- 多源 git pull 重试（GitHub → Gitee → 本地缓存）
- 仅当 requirements.txt 变更时才重建镜像（节省时间）
- Alembic DB 迁移前获取 Redis 互斥锁（法典 §3.5 防脑裂）
- docker compose up -d --remove-orphans（start-first 滚动更新）
- 失败自动回滚到上一版本（git stash pop）
- 全程结构化日志

用法:
    python scripts/update.py              # 标准更新
    python scripts/update.py --dry-run    # 仅检查，不执行
    python scripts/update.py --force      # 强制重建镜像
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import shlex
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

# ── 路径 ──────────────────────────────────────────────────────
SCRIPT_DIR: Path = Path(__file__).resolve().parent
PROJECT_ROOT: Path = SCRIPT_DIR.parent
COMPOSE_FILE: Path = PROJECT_ROOT / "docker-compose.yml"
REQUIREMENTS: Path = PROJECT_ROOT / "backend" / "requirements.txt"
DOCKERFILE: Path = PROJECT_ROOT / "backend" / "Dockerfile"
ALEMBIC_DIR: Path = PROJECT_ROOT / "backend" / "alembic"

# ── 多源拉取（法典 §1.3）──────────────────────────────────────
GIT_REMOTES: list[str] = [
    "origin",  # 默认 remote（GitHub 或 Gitee，取决于用户 clone 源）
]

# ── ANSI 颜色 ─────────────────────────────────────────────────
GREEN = "\033[92m"
RED = "\033[91m"
CYAN = "\033[96m"
YELLOW = "\033[93m"
BOLD = "\033[1m"
DIM = "\033[2m"
RESET = "\033[0m"

# ── 日志 ──────────────────────────────────────────────────────


class _JsonFormatter(logging.Formatter):
    """法典 §2.5: 结构化 JSON 日志格式器。"""

    def format(self, record: logging.LogRecord) -> str:
        """将日志记录格式化为 JSON 字符串。"""
        entry: dict[str, Any] = {
            "timestamp": self.formatTime(record, datefmt="%Y-%m-%dT%H:%M:%S%z"),
            "level": record.levelname,
            "caller": f"{record.module}.{record.funcName}",
            "message": record.getMessage(),
        }
        return json.dumps(entry, ensure_ascii=False)


_handler = logging.StreamHandler(sys.stderr)
_handler.setFormatter(_JsonFormatter())
logger = logging.getLogger("update")
logger.setLevel(logging.INFO)
logger.addHandler(_handler)
logger.propagate = False


# ── 命令执行 ──────────────────────────────────────────────────


def _run(
    args: list[str],
    *,
    timeout: int = 60,
    cwd: Path | None = None,
    check: bool = False,
) -> tuple[int, str]:
    """
    执行子进程命令，返回 (退出码, stdout+stderr)。

    Args:
        args: 命令参数列表。
        timeout: 超时秒数。
        cwd: 工作目录。
        check: 若为 True 且退出码非零则抛出异常。

    Returns:
        (exit_code, output) 元组。

    Raises:
        RuntimeError: 当 check=True 且命令失败。
    """
    try:
        result = subprocess.run(
            args,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout,
            cwd=str(cwd) if cwd else str(PROJECT_ROOT),
        )
        output = (result.stdout + result.stderr).strip()
        if check and result.returncode != 0:
            cmd_display = shlex.join(args)
            raise RuntimeError(f"命令失败 (rc={result.returncode}): {cmd_display}\n{output[:500]}")
        return result.returncode, output
    except FileNotFoundError:
        msg = f"命令未找到: {args[0]}"
        if check:
            raise RuntimeError(msg)
        return -1, msg
    except subprocess.TimeoutExpired:
        msg = f"命令超时 ({timeout}s): {' '.join(args)}"
        if check:
            raise RuntimeError(msg)
        return -2, msg


def _file_hash(path: Path) -> str:
    """计算文件 SHA256 摘要（用于变更检测）。"""
    if not path.exists():
        return ""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _parse_changed_files(diff_output: str) -> set[str]:
    """Normalize `git diff --name-only` output into comparable relative paths."""
    return {
        line.strip().replace("\\", "/")
        for line in diff_output.splitlines()
        if line.strip()
    }


def _requirements_changed_from_diff(diff_output: str) -> bool:
    """Return True when backend requirements changed in the inspected diff."""
    return REQUIREMENTS.relative_to(PROJECT_ROOT).as_posix() in _parse_changed_files(diff_output)


def _needs_image_rebuild_from_hashes(
    pre_requirements_hash: str,
    pre_dockerfile_hash: str,
    post_requirements_hash: str,
    post_dockerfile_hash: str,
) -> bool:
    """Compare image-defining inputs to decide whether a rebuild is required."""
    return (
        pre_requirements_hash != post_requirements_hash
        or pre_dockerfile_hash != post_dockerfile_hash
    )


def _collect_dirty_files(status_output: str) -> list[str]:
    """Parse `git status --porcelain` output into a trimmed file list."""
    return [line.strip() for line in status_output.splitlines() if line.strip()]


def _parse_upstream_branch(ref_output: str) -> str | None:
    """Extract the branch name from a symbolic upstream ref like origin/master."""
    ref = ref_output.strip()
    if not ref or ref == "HEAD":
        return None
    if "/" in ref:
        branch = ref.rsplit("/", 1)[-1].strip()
        return branch or None
    return ref


def _detect_pull_branch() -> str:
    """Resolve the branch to pull, preferring env, upstream, then current HEAD."""
    env_branch = os.getenv("ZEN70_UPDATE_BRANCH", "").strip()
    if env_branch:
        return env_branch

    rc, upstream = _run(["git", "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"])
    if rc == 0:
        branch = _parse_upstream_branch(upstream)
        if branch:
            return branch

    rc, current = _run(["git", "branch", "--show-current"])
    if rc == 0 and current.strip():
        return current.strip()

    return "master"


# ── 更新步骤 ──────────────────────────────────────────────────


def step_git_pull(dry_run: bool = False) -> str:
    """
    Step 1: 拉取最新代码。

    法典 §1.3：多源重试逻辑。

    Returns:
        当前 HEAD commit hash。
    """
    logger.info("[STEP 1/6] 拉取最新代码")

    # 保存当前 HEAD（用于回滚）
    rc, old_head = _run(["git", "rev-parse", "HEAD"])
    if rc != 0:
        logger.warning("无法获取当前 HEAD: %s", old_head)
        old_head = "unknown"

    if dry_run:
        logger.info("  %s[DRY-RUN] 跳过 git pull%s", DIM, RESET)
        return old_head.strip()

    # 多源重试
    pull_branch = _detect_pull_branch()
    for remote in GIT_REMOTES:
        rc, output = _run(["git", "pull", "--rebase", remote, pull_branch], timeout=120)
        if rc == 0:
            rc2, new_head = _run(["git", "rev-parse", "--short", "HEAD"])
            new_hash = new_head.strip() if rc2 == 0 else "unknown"
            logger.info("  代码更新成功: %s → %s", old_head[:8], new_hash)
            return old_head.strip()
        logger.warning("  git pull %s 失败: %s", remote, output[:200])

    logger.error("  所有远端拉取失败，使用本地代码继续")
    return old_head.strip()


def step_check_deps_changed(force: bool = False) -> bool:
    """
    Step 2: 检查 requirements.txt 是否有变更。

    Returns:
        需要重建镜像返回 True。
    """
    logger.info("[STEP 2/6] 检查依赖变更")
    if force:
        logger.info("  --force 模式，强制重建镜像")
        return True

    # 比较 git diff 检测 requirements.txt 变更
    rc, diff = _run(["git", "diff", "HEAD~1", "--name-only", "--", str(REQUIREMENTS.relative_to(PROJECT_ROOT))])
    changed = rc == 0 and _requirements_changed_from_diff(diff)
    if changed:
        logger.info("  requirements.txt 有变更，需重建镜像")
    else:
        logger.info("  依赖未变更，跳过镜像重建（volume mount 热重载生效）")
    return changed


def step_rebuild_image(dry_run: bool = False) -> None:
    """Step 3: 重建 gateway 镜像（仅在依赖变更时调用）。"""
    logger.info("[STEP 3/6] 重建 gateway 镜像")
    if dry_run:
        logger.info("  %s[DRY-RUN] 跳过镜像重建%s", DIM, RESET)
        return

    cachebust = str(int(time.time()))
    _run(
        [
            "docker",
            "build",
            "--build-arg",
            f"CACHEBUST={cachebust}",
            "-f",
            str(DOCKERFILE),
            "-t",
            "zen70-gateway:update",
            ".",
        ],
        timeout=600,
        check=True,
    )
    logger.info("  镜像重建完成")


def step_db_migrate(dry_run: bool = False) -> None:
    """
    Step 4: 执行 Alembic 数据库迁移。

    法典 §3.5：迁移前必须向 Redis 申请全局互斥锁 (DB_MIGRATION_LOCK)，防脑裂。
    迁移失败时强制中断更新流程（raise），由 main() 触发自动回滚。
    """
    logger.info("[STEP 4/6] 数据库迁移")

    if not ALEMBIC_DIR.exists():
        logger.info("  无 alembic 目录，跳过迁移")
        return

    if dry_run:
        logger.info("  %s[DRY-RUN] 跳过 DB 迁移%s", DIM, RESET)
        return

    # ── 法典 §3.5: 获取 Redis 全局迁移锁 ─────────────────────────
    # 在 gateway 容器内执行，复用容器网络直连 Redis
    lock_acquire_script = (
        "import redis,os,sys; "
        "r=redis.Redis("
        "host=os.getenv('REDIS_HOST','redis'),"
        "port=int(os.getenv('REDIS_PORT','6379')),"
        "password=os.getenv('REDIS_PASSWORD') or None,"
        "decode_responses=True); "
        "ok=r.set('DB_MIGRATION_LOCK',"
        "f'update-engine-{os.getpid()}',"
        "nx=True,ex=120); "
        "sys.exit(0 if ok else 1)"
    )
    rc_lock, lock_output = _run(
        [
            "docker", "compose", "-f", str(COMPOSE_FILE),
            "exec", "-T", "gateway", "python", "-c", lock_acquire_script,
        ],
        timeout=15,
    )
    if rc_lock != 0:
        raise RuntimeError(
            "ZEN-DB-MIGRATION-LOCKED: 无法获取迁移锁 (DB_MIGRATION_LOCK)，"
            f"另一进程正在迁移或锁未过期。输出: {lock_output[:200]}"
        )
    logger.info("  ✓ Redis 迁移锁已获取 (TTL=120s)")

    # ── 执行 Alembic 迁移（锁保护区）────────────────────────────
    try:
        rc, output = _run(
            [
                "docker", "compose", "-f", str(COMPOSE_FILE),
                "exec", "-T", "gateway",
                "python", "-m", "alembic", "upgrade", "head",
            ],
            timeout=120,
        )
        if rc == 0:
            logger.info("  数据库迁移完成")
        elif "already at head" in output.lower() or "no new" in output.lower():
            logger.info("  数据库已是最新版本")
        else:
            # D3: 迁移失败必须强制中断，防「代码新、库旧」组合上线
            raise RuntimeError(
                f"数据库迁移失败 (rc={rc})，强制中断更新防止「代码新、库旧」: {output[:300]}"
            )
    finally:
        # ── 无论成败均释放 Redis 锁 ──────────────────────────────
        lock_release_script = (
            "import redis,os; "
            "r=redis.Redis("
            "host=os.getenv('REDIS_HOST','redis'),"
            "port=int(os.getenv('REDIS_PORT','6379')),"
            "password=os.getenv('REDIS_PASSWORD') or None,"
            "decode_responses=True); "
            "r.delete('DB_MIGRATION_LOCK')"
        )
        rc_rel, _ = _run(
            [
                "docker", "compose", "-f", str(COMPOSE_FILE),
                "exec", "-T", "gateway", "python", "-c", lock_release_script,
            ],
            timeout=10,
        )
        if rc_rel == 0:
            logger.info("  ✓ Redis 迁移锁已释放")
        else:
            logger.warning("  迁移锁释放失败 (rc=%d)，将由 TTL=120s 自动消散", rc_rel)


def step_rolling_update(dry_run: bool = False) -> None:
    """
    Step 5: 滚动更新容器（start-first + remove-orphans）。

    法典 1.2 强制：必须且只能使用 docker compose up -d --remove-orphans。
    """
    logger.info("[STEP 5/6] 滚动更新容器")
    if dry_run:
        logger.info("  %s[DRY-RUN] 跳过 compose up%s", DIM, RESET)
        return

    # 法典 §1.2: COMPOSE_PROJECT_NAME 已由 IaC 编译器写入 .env 文件
    # docker compose 自动读取 compose file 同目录的 .env，无需运行时注入
    rc, output = _run(
        [
            "docker",
            "compose",
            "-f",
            str(COMPOSE_FILE),
            "up",
            "-d",
            "--remove-orphans",
        ],
        timeout=300,
    )
    if rc != 0:
        raise RuntimeError(f"compose up 失败 (rc={rc}): {output[:500]}")
    logger.info("  容器滚动更新完成")


def step_health_check() -> bool:
    """
    Step 6: 等待 gateway 健康检查通过。

    Returns:
        健康检查通过返回 True。
    """
    logger.info("[STEP 6/6] 健康检查")
    max_attempts = 15
    for attempt in range(1, max_attempts + 1):
        time.sleep(3)
        rc, output = _run(
            [
                "docker",
                "inspect",
                "--format",
                "{{.State.Health.Status}}",
                "zen70-gateway",
            ],
            timeout=10,
        )
        status = output.strip().lower()
        if status == "healthy":
            logger.info("  gateway 健康检查通过 (第 %d/%d 次)", attempt, max_attempts)
            return True
        logger.info("  gateway 状态: %s (第 %d/%d 次)", status, attempt, max_attempts)

    logger.error("  gateway 健康检查超时")
    return False


def _check_workspace_clean() -> None:
    """
    法典强制：执行更新前必须验证 Git 工作区纯洁性。

    若存在未提交的修改，回滚时 `git reset --hard` 会物理抹除代码，
    造成不可逆的数据丢失。此函数从物理层面杜绝该风险。

    Raises:
        RuntimeError: 工作区存在未提交的变更。
    """
    rc, output = _run(["git", "status", "--porcelain"])
    if rc != 0:
        logger.warning("无法检查 Git 工作区状态 (rc=%d): %s", rc, output[:200])
        return  # 非 git 仓库或无 git 命令 — 放行但告警
    dirty_files = _collect_dirty_files(output)
    if dirty_files:
        logger.error(
            "工作区不纯净 (%d 个文件有未提交变更)，中止更新以防 reset --hard 数据丢失",
            len(dirty_files),
        )
        for df in dirty_files[:5]:
            logger.error("  脏文件: %s", df.strip())
        if len(dirty_files) > 5:
            logger.error("  ... 及其他 %d 个文件", len(dirty_files) - 5)
        raise RuntimeError(
            "工作区不纯净（有未提交变更）。"
            "请先执行 `git stash` 或 `git commit` 后重试更新。"
            "此限制是为防止自动回滚 (git reset --hard) 抹除您的本地修改。"
        )
    logger.info("  工作区纯净 ✓")


def rollback(old_head: str) -> None:
    """
    回滚到更新前的版本。

    安全前置条件：_check_workspace_clean() 已在 main() 入口验证，
    此处执行 git reset --hard 不会丢失用户的未提交变更。

    加固策略 (D2):
    1. 保存回滚前镜像层关键文件的哈希
    2. git reset --hard
    3. 若 requirements.txt 或 Dockerfile 变更 → 自动重建镜像
    4. compose up --remove-orphans
    """
    logger.warning("═══ 执行自动回滚 ═══")
    logger.warning("  目标版本: %s", old_head[:8] if len(old_head) >= 8 else old_head)

    # ── Phase 1: 保存回滚前的镜像关键文件哈希 ───────────────────
    pre_reqs_hash = _file_hash(REQUIREMENTS)
    pre_docker_hash = _file_hash(DOCKERFILE)

    # ── Phase 2: 代码回滚 ────────────────────────────────────────
    logger.warning("  [回滚 1/3] git reset --hard %s（工作区已在入口处验证为纯净）", old_head[:8] if len(old_head) >= 8 else old_head)
    rc, output = _run(["git", "reset", "--hard", old_head])
    if rc != 0:
        logger.error("  代码回滚失败: %s", output[:300])
        return

    # ── Phase 3: 检查是否需要重建镜像 ────────────────────────────
    post_reqs_hash = _file_hash(REQUIREMENTS)
    post_docker_hash = _file_hash(DOCKERFILE)
    needs_image_rebuild = _needs_image_rebuild_from_hashes(
        pre_reqs_hash,
        pre_docker_hash,
        post_reqs_hash,
        post_docker_hash,
    )

    if needs_image_rebuild:
        logger.warning("  [回滚 2/3] 检测到依赖/Dockerfile 变更，重建旧版镜像")
        rc_build, build_out = _run(
            [
                "docker", "build",
                "-f", str(DOCKERFILE),
                "-t", "zen70-gateway:update",
                ".",
            ],
            timeout=600,
            cwd=PROJECT_ROOT,
        )
        if rc_build != 0:
            logger.error("  镜像重建失败 (rc=%d): %s", rc_build, build_out[:300])
            logger.error("  容器可能运行新镜像+旧代码，请人工干预")
        else:
            logger.info("  旧版镜像重建完成 ✓")
    else:
        logger.info("  [回滚 2/3] 依赖/Dockerfile 无变更，跳过镜像重建")

    # ── Phase 4: 拉起旧版容器 ────────────────────────────────────
    logger.warning("  [回滚 3/3] 拉起旧版容器")
    _run(
        [
            "docker", "compose",
            "-f", str(COMPOSE_FILE),
            "up", "-d", "--remove-orphans",
        ],
        timeout=300,
    )
    logger.info("  回滚完成，已恢复到 %s ✓", old_head[:8] if len(old_head) >= 8 else old_head)


# ── 主流程 ────────────────────────────────────────────────────


def main() -> None:
    """零停机更新主入口。"""
    parser = argparse.ArgumentParser(description="ZEN70 零停机更新引擎")
    parser.add_argument("--dry-run", action="store_true", help="仅检查，不执行更新")
    parser.add_argument("--force", action="store_true", help="强制重建镜像")
    args = parser.parse_args()

    logger.info(
        "%s%s╔══════════════════════════════════════════════╗\n"
        "║     ZEN70 V2.0  零停机更新引擎               ║\n"
        "╚══════════════════════════════════════════════╝%s",
        BOLD,
        CYAN,
        RESET,
    )

    start_time = time.time()

    # ── Step 0: 工作区纯洁性强制预检（法典 §7 禁止脏区回滚）──
    logger.info("[STEP 0/6] 工作区纯洁性检查")
    _check_workspace_clean()

    old_head = "HEAD~1"  # 哨兵值：确保异常时 rollback 仍可执行
    try:
        # Step 1: 拉取代码
        old_head = step_git_pull(dry_run=args.dry_run)

        # Step 2: 检查依赖变更
        needs_rebuild = step_check_deps_changed(force=args.force)

        # Step 3: 重建镜像（仅在需要时）
        if needs_rebuild:
            step_rebuild_image(dry_run=args.dry_run)

        # Step 4: DB 迁移
        step_db_migrate(dry_run=args.dry_run)

        # Step 5: 滚动更新
        step_rolling_update(dry_run=args.dry_run)

        # Step 6: 健康检查
        if not args.dry_run:
            if not step_health_check():
                logger.error("更新后健康检查失败，执行自动回滚")
                rollback(old_head)
                sys.exit(1)

        elapsed = int(time.time() - start_time)
        logger.info(
            "%s%s✔ 更新完成 (%ds)%s",
            GREEN,
            BOLD,
            elapsed,
            RESET,
        )

    except RuntimeError as exc:
        logger.error("更新失败: %s", exc)
        logger.error("尝试自动回滚...")
        rollback(old_head)
        sys.exit(1)
    except KeyboardInterrupt:
        logger.info("更新被用户中断")
        sys.exit(130)


if __name__ == "__main__":
    main()
