/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 * @description 统一错误消息提取工具。全局单一入口，禁止组件内重复实现。
 */

/**
 * 从 unknown 错误中安全提取 message，避免 any。
 */
export function errorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === "object" && err !== null && "message" in err) {
    return String((err as { message: unknown }).message);
  }
  return String(err);
}

/**
 * 类型守卫：判断是否为 Axios 风格的错误对象。
 */
export function isAxiosError(err: unknown): err is { response?: { status?: number; data?: unknown }; message?: string } {
  return typeof err === "object" && err !== null && "isAxiosError" in err;
}

/**
 * 从后端响应体提取可读错误消息（兼容 {message} / {detail} / {detail:{message}}）。
 * 用于非 Axios 场景（如 push.ts fetch 调用）。
 */
export function apiErrorMessage(payload: unknown, fallback: string): string {
  if (payload && typeof payload === "object") {
    const p = payload as { message?: unknown; detail?: unknown };
    if (typeof p.message === "string" && p.message) return p.message;
    if (typeof p.detail === "string" && p.detail) return p.detail;
    if (p.detail && typeof p.detail === "object" && "message" in p.detail) {
      const m = (p.detail as { message?: unknown }).message;
      if (typeof m === "string" && m) return m;
    }
  }
  return fallback;
}

/**
 * 从 Axios 错误中提取后端返回的可读错误消息。
 * ADR 0010: 错误响应格式为 {code, message, recovery_hint, details}。
 * FastAPI 默认错误格式为 {detail: string | {message: string}}。
 * 本函数兼容两种格式，且处理 401/403/429 等常见状态码的中文提示。
 *
 * @param err - catch 块中的 unknown 错误
 * @param fallback - 无法提取消息时的兜底文案
 * @returns 人类可读的错误消息
 */
export function extractAxiosError(err: unknown, fallback: string): string {
  if (!isAxiosError(err)) {
    return err instanceof Error ? err.message : fallback;
  }
  const status = err.response?.status;
  const data = err.response?.data;

  // 常见 HTTP 状态码中文提示
  if (status === 401) return "会话已过期，请重新登录";
  if (status === 403) return "权限不足，无法执行此操作";
  if (status === 429) return "操作过于频繁，请稍后重试";

  // 从后端响应体提取消息
  if (data && typeof data === "object") {
    return apiErrorMessage(data, fallback);
  }

  return err.message ?? fallback;
}
