/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 * @description SSE client with exp backoff (1s->2s->4s, max 30s), max 10 retries,
 * visibilitychange close on hidden, 503 no infinite loop.
 * 法典 §2.1: 前端每 30s 发送 Ping，后端连续 45s 未收到必须强斩 cancel()，杜绝 FD 耗尽。
 * 法典 §3.6: 监听 visibilitychange，页面 hidden 必须 EventSource.close() 物理掐断 SSE。
 *
 * Client-Token-in-URL: 前端自主生成 UUID 拼入 URL，无需依赖服务端首包下发 connection_id。
 */
import type {
  HardwareEvent,
  SSEEvent,
  SwitchEvent,
  NodeControlEvent,
  JobControlEvent,
  ConnectorControlEvent,
} from "@/types/sse";
import { http } from "@/utils/http";
import { SSE } from "@/utils/api";
import { logError, logWarn } from "@/utils/logger";

const RECONNECT_BASE_MS = 1000;
const RECONNECT_MAX_MS = 30000;
const MAX_RETRIES = 10;
/** 法典 §2.1: 心跳间隔 30 秒 */
const PING_INTERVAL_MS = 30_000;

function parseData(e: MessageEvent): unknown {
  try {
    return typeof e.data === "string" ? JSON.parse(e.data) as unknown : e.data as unknown;
  } catch {
    return null;
  }
}

export interface SSEOptions {
  onFallbackOffline?: () => void;
}

/**
 * 创建 SSE 连接，订阅 hardware:events 和 switch:events。
 * 指数退避重连：1s->2s->4s... 上限 30s；最多 10 次后降级为离线骨架屏。
 * 页面 hidden 时关闭连接，防止僵尸句柄（V2.0 锁屏生命周期）。
 * 连接成功后自动启动 30s 心跳 Ping，后端 45s 未收到则强斩 SSE 协程。
 */
export function createSSE(
  url: string,
  onEvent: (ev: SSEEvent) => void,
  channels: readonly (
    | "hardware:events"
    | "switch:events"
    | "node:events"
    | "job:events"
    | "connector:events"
  )[] = [
    "hardware:events",
    "switch:events",
    "node:events",
    "job:events",
    "connector:events",
  ],
  options: SSEOptions = {}
): () => void {
  let es: EventSource | null = null;
  let closed = false;
  let attempt = 0;
  /** Client-Token: 前端自主生成，不依赖服务端首包 */
  let currentClientToken: string | null = null;
  let pingTimer: ReturnType<typeof setInterval> | null = null;

  /** 停止心跳定时器 */
  function stopPing(): void {
    if (pingTimer !== null) {
      clearInterval(pingTimer);
      pingTimer = null;
    }
  }

  /**
   * 启动 30s 心跳 Ping。
   * 法典 §2.1: 前端每 30s 调 POST /api/v1/events/ping 续期。
   * Client-Token-in-URL: 使用前端自主生成的 token，无需等待服务端首包。
   */
  function startPing(): void {
    stopPing();
    if (!currentClientToken) return;

    pingTimer = setInterval(() => {
      if (closed || !currentClientToken) {
        stopPing();
        return;
      }
      http.post(SSE.ping, { connection_id: currentClientToken }).catch((err: unknown) => {
        logWarn("[ZEN70 SSE] Ping failed", err);
      });
    }, PING_INTERVAL_MS);
  }

  function connect(): void {
    if (closed) return;
    if (attempt >= MAX_RETRIES) {
      options.onFallbackOffline?.();
      return;
    }

    // Client-Token-in-URL: 每次建连生成新 UUID，避免与旧 TTL 键冲突
    currentClientToken = crypto.randomUUID();
    const sep = url.includes("?") ? "&" : "?";
    const sseUrl = `${url}${sep}client_token=${currentClientToken}`;
    es = new EventSource(sseUrl);

    for (const ch of channels) {
      es.addEventListener(ch, (e: MessageEvent) => {
        try {
          onEvent({
            type: ch,
            data: parseData(e) as
              | HardwareEvent
              | SwitchEvent
              | NodeControlEvent
              | JobControlEvent
              | ConnectorControlEvent,
          });
        } catch (err: unknown) {
          logError(`[ZEN70] SSE parse ${ch}`, err);
        }
      });
    }

    es.addEventListener("connected", () => {
      // 首包确认：重置重试计数，立即启动 Ping（token 已在 URL 中传递）
      attempt = 0;
      startPing();
    });

    es.onerror = () => {
      stopPing();
      es?.close();
      es = null;
      if (closed) return;
      if (attempt >= MAX_RETRIES) {
        options.onFallbackOffline?.();
        return;
      }
      const delay = Math.min(RECONNECT_BASE_MS * 2 ** attempt, RECONNECT_MAX_MS);
      attempt += 1;
      setTimeout(connect, delay);
    };
  }

  function closeConnectionOnly(): void {
    stopPing();
    es?.close();
    es = null;
  }

  function onVisibilityChange(): void {
    if (document.visibilityState === "hidden") {
      closeConnectionOnly();
    } else if (!closed && !es) {
      attempt = 0;
      connect();
    }
  }

  document.addEventListener("visibilitychange", onVisibilityChange);
  connect();

  return () => {
    document.removeEventListener("visibilitychange", onVisibilityChange);
    closed = true;
    stopPing();
    es?.close();
    es = null;
  };
}
