# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
"""
ZEN70 图形化部署向导 V2 — 后端 API。

三步向导架构（ADR 0012 §7）：
  Step 1: /api/preflight    — 环境预检（复用 bootstrap.py check_*）
  Step 2: /api/config/*     — 参数配置（IaC 合规：全走 system.yaml）
  Step 3: /api/deploy       — 编译部署（SSE 流式日志）

IaC 铁律：所有用户输入 → system.yaml → compiler → 产物。
         安装器**绝不直接操作** .env 或 docker-compose.yml。

法典合规：
  §2.1 — SSE 反缓冲响应头 (X-Accel-Buffering: no)
  §2.1 — 严禁 WebSocket，SSE only
  §8.2 — async 路由严禁同步阻塞
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import platform
import shutil
import socket
import sys
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import yaml
from fastapi import FastAPI, Request, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse, StreamingResponse

logger = logging.getLogger("installer")

# ---------------------------------------------------------------------------
# 部署互斥锁（严禁并发启动多个 bootstrap 进程）
# 惰性初始化：避免在模块加载时（无事件循环）创建 Lock
# ---------------------------------------------------------------------------

_deploy_lock: asyncio.Lock | None = None
_deploy_active = False


def _get_deploy_lock() -> asyncio.Lock:
    """惰性获取部署互斥锁（必须在事件循环内调用）。"""
    global _deploy_lock  # noqa: PLW0603
    if _deploy_lock is None:
        _deploy_lock = asyncio.Lock()
    return _deploy_lock


# ---------------------------------------------------------------------------
# 路径常量（pathlib 动态解析，禁止硬编码）
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parent.parent
FRONTEND_HTML = Path(__file__).resolve().parent / "index.html"
BOOTSTRAP_SCRIPT = ROOT_DIR / "scripts" / "bootstrap.py"
COMPILER_SCRIPT = ROOT_DIR / "scripts" / "compiler.py"
SYSTEM_YAML = ROOT_DIR / "system.yaml"
ENV_FILE = ROOT_DIR / ".env"
DOCKER_COMPOSE_FILE = ROOT_DIR / "docker-compose.yml"
BACKUP_DIR = ROOT_DIR / ".backups"
COMPOSE_PROJECT_NAME = "zen70"  # IaC 唯一事实来源（与 loader.py / .env 对齐）
# 运行时从 .env 动态读取（编译器可能变更此值）
_env_file = ROOT_DIR / ".env"
if _env_file.exists():
    try:
        for _line in _env_file.read_text(encoding="utf-8").splitlines():
            _line = _line.strip()
            if _line.startswith("COMPOSE_PROJECT_NAME=") and not _line.startswith("#"):
                _val = _line.split("=", 1)[1].strip()
                if _val:
                    COMPOSE_PROJECT_NAME = _val
                break
    except OSError:
        pass  # 读取失败使用 fallback "zen70"

# ---------------------------------------------------------------------------
# SSE 反缓冲响应头（法典 §2.1）
# ---------------------------------------------------------------------------

_SSE_HEADERS: dict[str, str] = {
    "X-Accel-Buffering": "no",
    "Cache-Control": "no-cache",
    "Connection": "keep-alive",
}

# ---------------------------------------------------------------------------
# 应用实例
# ---------------------------------------------------------------------------

app = FastAPI(
    title="ZEN70 Gateway Kernel 部署向导",
    description="三步向导式部署器 — 环境检测 → 参数配置 → 编译部署",
    version="v3.43",
)


# ===========================================================================
# 数据结构
# ===========================================================================


@dataclass
class CheckResult:
    """单项预检结果。"""

    id: str
    label: str
    status: str  # "ok" | "fail" | "warn"
    message: str
    fix_hint: str = ""


@dataclass
class PreflightResponse:
    """预检总结果。"""

    checks: list[CheckResult] = field(default_factory=list)
    all_passed: bool = False
    recommended_profile: str = "gateway-kernel"
    detected_ram_mb: int = 0


# ===========================================================================
# Step 1: 环境预检 /api/preflight
# ===========================================================================


async def _async_check_docker() -> CheckResult:
    """异步检测 Docker 是否安装且 daemon 可用。"""
    try:
        proc = await asyncio.create_subprocess_exec(
            "docker",
            "info",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await asyncio.wait_for(proc.communicate(), timeout=10)
        if proc.returncode == 0:
            return CheckResult(
                id="docker_installed",
                label="Docker 引擎",
                status="ok",
                message="Docker daemon 运行中",
            )
        err_text = stderr.decode("utf-8", errors="replace").strip()
        return CheckResult(
            id="docker_installed",
            label="Docker 引擎",
            status="fail",
            message=f"Docker daemon 不可用: {err_text[:200]}",
            fix_hint="请安装并启动 Docker Desktop: https://docs.docker.com/get-docker/",
        )
    except FileNotFoundError:
        return CheckResult(
            id="docker_installed",
            label="Docker 引擎",
            status="fail",
            message="系统未安装 Docker",
            fix_hint="请安装 Docker Desktop: https://docs.docker.com/get-docker/",
        )
    except asyncio.TimeoutError:
        return CheckResult(
            id="docker_installed",
            label="Docker 引擎",
            status="fail",
            message="Docker 响应超时（10 秒）",
            fix_hint="请检查 Docker Desktop 是否正在启动中，稍后重试",
        )


async def _async_check_docker_version() -> CheckResult:
    """异步检测 Docker 版本 ≥ 20.10。"""
    try:
        proc = await asyncio.create_subprocess_exec(
            "docker",
            "version",
            "--format",
            "{{.Server.Version}}",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=10)
        if proc.returncode != 0:
            return CheckResult(
                id="docker_version",
                label="Docker 版本",
                status="fail",
                message="无法获取 Docker 版本",
                fix_hint="请确认 Docker daemon 已启动",
            )
        ver_str = stdout.decode("utf-8", errors="replace").strip()
        parts = ver_str.split(".")
        if len(parts) >= 2:
            major, minor = int(parts[0]), int(parts[1])
            if (major, minor) >= (20, 10):
                return CheckResult(
                    id="docker_version",
                    label="Docker 版本",
                    status="ok",
                    message=f"Docker {ver_str} ≥ 20.10",
                )
            return CheckResult(
                id="docker_version",
                label="Docker 版本",
                status="fail",
                message=f"Docker {ver_str} 过低，需要 ≥ 20.10",
                fix_hint="请升级 Docker Desktop 到最新版本",
            )
        return CheckResult(
            id="docker_version",
            label="Docker 版本",
            status="warn",
            message=f"无法解析版本号: {ver_str}",
        )
    except (FileNotFoundError, asyncio.TimeoutError):
        return CheckResult(
            id="docker_version",
            label="Docker 版本",
            status="fail",
            message="Docker 不可用",
        )


async def _async_check_compose() -> CheckResult:
    """异步检测 Docker Compose 是否可用。"""
    try:
        proc = await asyncio.create_subprocess_exec(
            "docker",
            "compose",
            "version",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=10)
        if proc.returncode == 0:
            ver = stdout.decode("utf-8", errors="replace").strip()
            return CheckResult(
                id="docker_compose",
                label="Docker Compose",
                status="ok",
                message=ver,
            )
        return CheckResult(
            id="docker_compose",
            label="Docker Compose",
            status="fail",
            message="Docker Compose 不可用",
            fix_hint="Docker Desktop 自带 Compose，请确认安装完整",
        )
    except (FileNotFoundError, asyncio.TimeoutError):
        return CheckResult(
            id="docker_compose",
            label="Docker Compose",
            status="fail",
            message="Docker Compose 命令不存在",
            fix_hint="请安装 Docker Desktop（内含 Compose 插件）",
        )


async def _async_check_ports() -> CheckResult:
    """异步检查 80/443 端口占用（在线程池中执行，避免阻塞事件循环）。"""
    loop = asyncio.get_running_loop()
    occupied = await loop.run_in_executor(None, _sync_check_ports)

    if not occupied:
        return CheckResult(
            id="ports_available",
            label="端口 80/443",
            status="ok",
            message="端口 80 和 443 可用",
        )
    return CheckResult(
        id="ports_available",
        label="端口 80/443",
        status="warn",
        message=f"端口 {occupied} 已被占用",
        fix_hint="若为重复部署属正常现象；首次部署请关闭占用程序（如 IIS/Apache/Nginx）",
    )


def _sync_check_ports() -> list[int]:
    """同步端口检测（由线程池调用）。P1.4: 改用 127.0.0.1 匹配 Docker 实际暴露行为。"""
    occupied: list[int] = []
    for port in (80, 443):
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        try:
            sock.bind(("127.0.0.1", port))
        except OSError:
            occupied.append(port)
        finally:
            sock.close()
    return occupied


def _check_disk() -> CheckResult:
    """检查项目根目录磁盘可用空间 ≥ 10 GB。"""
    try:
        _, _, free = shutil.disk_usage(ROOT_DIR)
        free_gb = free / (1024**3)
        if free_gb >= 10:
            return CheckResult(
                id="disk_space",
                label="磁盘空间",
                status="ok",
                message=f"可用空间 {free_gb:.1f} GB ≥ 10 GB",
            )
        return CheckResult(
            id="disk_space",
            label="磁盘空间",
            status="fail",
            message=f"磁盘空间不足：{free_gb:.1f} GB < 10 GB",
            fix_hint="请清理磁盘或更换到更大分区",
        )
    except OSError as e:
        return CheckResult(
            id="disk_space",
            label="磁盘空间",
            status="warn",
            message=f"无法检测磁盘空间: {e}",
        )


def _check_system_yaml() -> CheckResult:
    """检查 system.yaml 是否存在。"""
    if SYSTEM_YAML.exists():
        return CheckResult(
            id="system_yaml",
            label="配置文件",
            status="ok",
            message="system.yaml 已就绪",
        )
    return CheckResult(
        id="system_yaml",
        label="配置文件",
        status="fail",
        message="system.yaml 不存在",
        fix_hint="请确认项目文件完整，或点击部署后由点火引擎自动拉取",
    )


def _detect_ram() -> tuple[int, str]:
    """
    探测系统物理内存（MB），推荐部署画像。

    画像阈值（ADR 0012 §4.2）：
      gateway-kernel: default | full: optional expansion when host resources are sufficient
    """
    ram_mb = 0
    try:
        import psutil

        ram_mb = psutil.virtual_memory().total // (1024 * 1024)
    except ImportError:
        # psutil 不可用，尝试平台原生方法
        if platform.system() == "Linux":
            try:
                meminfo = Path("/proc/meminfo").read_text(encoding="utf-8")
                for line in meminfo.splitlines():
                    if line.startswith("MemTotal:"):
                        kb = int(line.split()[1])
                        ram_mb = kb // 1024
                        break
            except (OSError, ValueError):
                pass
        elif platform.system() == "Windows":
            try:
                import ctypes

                class MEMORYSTATUSEX(ctypes.Structure):
                    _fields_ = [
                        ("dwLength", ctypes.c_ulong),
                        ("dwMemoryLoad", ctypes.c_ulong),
                        ("ullTotalPhys", ctypes.c_ulonglong),
                        ("ullAvailPhys", ctypes.c_ulonglong),
                        ("ullTotalPageFile", ctypes.c_ulonglong),
                        ("ullAvailPageFile", ctypes.c_ulonglong),
                        ("ullTotalVirtual", ctypes.c_ulonglong),
                        ("ullAvailVirtual", ctypes.c_ulonglong),
                        ("ullAvailExtendedVirtual", ctypes.c_ulonglong),
                    ]

                stat = MEMORYSTATUSEX()
                stat.dwLength = ctypes.sizeof(MEMORYSTATUSEX)
                ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(stat))
                ram_mb = stat.ullTotalPhys // (1024 * 1024)
            except (OSError, AttributeError):
                pass

    # 画像推荐（P2.1: ARM 设备自动降一档）
    if ram_mb <= 0:
        return 0, "gateway-kernel"
    if ram_mb < 14336:
        return ram_mb, "gateway-kernel"
    return ram_mb, "full"


@app.get("/api/preflight")
async def preflight() -> dict[str, Any]:
    """
    Step 1: 环境预检。

    并发执行所有检查项，返回逐项结果 + 推荐画像。
    前端据此渲染 ✅/❌ 列表，全通过后亮起"下一步"。
    """
    # 所有检查异步并发执行（端口检测已包装为 async）
    docker_check, version_check, compose_check, port_check = await asyncio.gather(
        _async_check_docker(),
        _async_check_docker_version(),
        _async_check_compose(),
        _async_check_ports(),
    )

    # 纯计算型检查（ms 级，不涉及 I/O，可同步）
    disk_check = _check_disk()
    yaml_check = _check_system_yaml()
    ram_mb, profile = _detect_ram()

    checks = [docker_check, version_check, compose_check, port_check, disk_check, yaml_check]

    # P3.1: 平台检测预检项（Windows 强警告引导 WSL）
    host_os = platform.system()
    arch = platform.machine()
    is_arm = arch.lower() in ("aarch64", "armv7l", "arm64")
    if host_os == "Windows":
        checks.append(
            CheckResult(
                id="platform_detect",
                label="运行平台",
                status="warn",
                message=(
                    f"检测到 Windows ({arch}) 宿主机。"
                    "Windows Docker Desktop 文件 I/O 性能约为原生 Linux 的 1/10，"
                    "且挂载权限（chown）不生效。"
                ),
                fix_hint=(
                    "强烈建议：打开 WSL 终端，cd 到 Linux 文件系统 "
                    "(/home/user/zen70)，在 WSL 内重新执行 python start_installer.py。"
                    "这将获得 10 倍以上的 I/O 性能和完整的 Linux 权限支持。"
                ),
            )
        )
    elif is_arm:
        checks.append(
            CheckResult(
                id="platform_detect",
                label="运行平台",
                status="ok",
                message=f"ARM 架构 ({arch})，已自动调整资源画像",
            )
        )
    else:
        checks.append(
            CheckResult(
                id="platform_detect",
                label="运行平台",
                status="ok",
                message=f"{host_os} ({arch})",
            )
        )

    # RAM 检测结果也作为一项
    if ram_mb > 0:
        checks.append(
            CheckResult(
                id="ram_detect",
                label="系统内存",
                status="ok",
                message=f"检测到 {ram_mb / 1024:.1f} GB 内存，推荐画像: {profile}",
            )
        )
    else:
        checks.append(
            CheckResult(
                id="ram_detect",
                label="系统内存",
                status="warn",
                message="无法检测系统内存，使用默认画像 gateway-kernel",
            )
        )

    all_passed = all(c.status != "fail" for c in checks)

    result = PreflightResponse(
        checks=checks,
        all_passed=all_passed,
        recommended_profile=profile,
        detected_ram_mb=ram_mb,
    )
    return asdict(result)


# ===========================================================================
# Step 2: 配置管理 /api/config/*
# ===========================================================================


def _load_system_yaml() -> dict[str, Any]:
    """加载 system.yaml 为字典。失败返回空字典。"""
    if not SYSTEM_YAML.exists():
        return {}
    try:
        data = yaml.safe_load(SYSTEM_YAML.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (yaml.YAMLError, OSError) as e:
        logger.error("加载 system.yaml 失败: %s", e)
        return {}


def _backup_system_yaml() -> Path | None:
    """
    写入前备份 system.yaml → .backups/system.yaml.{timestamp}。

    任何 IaC 写入操作前必须调用此函数，确保可回滚。
    """
    if not SYSTEM_YAML.exists():
        return None
    try:
        BACKUP_DIR.mkdir(parents=True, exist_ok=True)
        ts = time.strftime("%Y%m%d_%H%M%S")
        backup_path = BACKUP_DIR / f"system.yaml.{ts}"
        shutil.copy2(SYSTEM_YAML, backup_path)
        logger.info("配置备份: %s", backup_path)
        return backup_path
    except OSError as e:
        logger.warning("备份 system.yaml 失败: %s", e)
        return None


def _save_system_yaml(data: dict[str, Any], *, backup: bool = True) -> bool:
    """
    保存配置到 system.yaml。

    IaC 铁律：所有变更统一写 system.yaml，由编译器渲染产物。
    优先 ruamel.yaml 保留注释，降级 PyYAML。

    Args:
        data: 要写入的配置字典。
        backup: 写入前是否创建备份（默认 True）。
    """
    if backup:
        _backup_system_yaml()

    # 确保目标目录存在（防止路径缺失导致写入失败）
    SYSTEM_YAML.parent.mkdir(parents=True, exist_ok=True)

    try:
        import io

        from ruamel.yaml import YAML as RUAMEL_YAML
        from ruamel.yaml import YAMLError as RuamelYAMLError

        ry = RUAMEL_YAML()
        ry.preserve_quotes = True
        ry.default_flow_style = False

        # 加载原文件保留注释结构，再合并新值
        if SYSTEM_YAML.exists():
            original = ry.load(SYSTEM_YAML.read_text(encoding="utf-8"))
            if original is None:
                original = {}
            _deep_update(original, data)
            target = original
        else:
            target = data

        buf = io.StringIO()
        ry.dump(target, buf)
        SYSTEM_YAML.write_text(buf.getvalue(), encoding="utf-8")
        return True
    except ImportError:
        # ruamel 不可用，降级 PyYAML（会丢失注释）
        logger.warning("ruamel.yaml 不可用，注释将丢失")
        try:
            SYSTEM_YAML.write_text(
                yaml.dump(data, allow_unicode=True, default_flow_style=False, sort_keys=False),
                encoding="utf-8",
            )
            return True
        except OSError as e:
            logger.error("PyYAML 写入失败: %s", e)
            return False
    except (OSError, RuamelYAMLError) as e:
        # 捕获 ruamel YAML 序列化错误和 I/O 异常
        logger.error("写入 system.yaml 失败: %s: %s", type(e).__name__, e)
        return False


def _deep_update(base: dict, updates: dict) -> None:
    """递归合并 updates 到 base，保留 base 的 ruamel 注释节点。"""
    for key, value in updates.items():
        if key in base and isinstance(base[key], dict) and isinstance(value, dict):
            _deep_update(base[key], value)
        else:
            base[key] = value


@app.get("/api/config/load")
async def config_load() -> dict[str, Any]:
    """
    加载当前 system.yaml 配置为 JSON。

    前端 Step 2 用此 API 填充表单、渲染服务开关。
    """
    config = _load_system_yaml()
    if not config:
        return JSONResponse(
            status_code=404,
            content={"error": "system.yaml 不存在或为空"},
        )
    return {"config": config}


@app.post("/api/config/save")
async def config_save(request: Request) -> dict[str, Any]:
    """
    保存用户配置到 system.yaml。

    IaC 铁律：所有用户输入 → system.yaml → compiler → 产物。
    安装器绝不直接操作 .env 或 docker-compose.yml。

    请求体结构:
    {
        "network": {"domain": "zen70.cn"},
        "capabilities": {"storage": {"media_path": "/mnt/media"}},
        "services": {"jellyfin": {"enabled": true}, ...},
        "deployment": {"profile": "gateway-kernel"},
        "tunnel_token": "eyJhIjoixx..."
    }
    """
    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError) as e:
        return JSONResponse(status_code=400, content={"error": f"JSON 解析失败: {e}"})

    if not isinstance(body, dict):
        return JSONResponse(status_code=400, content={"error": "请求体必须是 JSON 对象"})

    # 加载现有配置作为基础
    config = _load_system_yaml()

    # 合并用户提交的字段（只更新提交的部分，不覆盖未提交的）
    if "network" in body and isinstance(body["network"], dict):
        config.setdefault("network", {})
        _deep_update(config["network"], body["network"])

    if "capabilities" in body and isinstance(body["capabilities"], dict):
        config.setdefault("capabilities", {})
        _deep_update(config["capabilities"], body["capabilities"])

    if "deployment" in body and isinstance(body["deployment"], dict):
        config.setdefault("deployment", {})
        _deep_update(config["deployment"], body["deployment"])

    # 服务开关：只更新 enabled 字段
    if "services" in body and isinstance(body["services"], dict):
        config.setdefault("services", {})
        for svc_name, svc_data in body["services"].items():
            if isinstance(svc_data, dict) and "enabled" in svc_data:
                if svc_name in config["services"] and isinstance(config["services"][svc_name], dict):
                    config["services"][svc_name]["enabled"] = svc_data["enabled"]

    # Tunnel Token → 写入 system.yaml 的环境变量占位区
    # IaC 铁律：Token 真值由编译器 generate_secrets() 注入 .env
    tunnel_token = body.get("tunnel_token", "").strip()
    if tunnel_token:
        config.setdefault("secrets", {})
        config["secrets"]["tunnel_token"] = tunnel_token

    if _save_system_yaml(config):
        return {"status": "ok", "message": "配置已保存到 system.yaml"}
    return JSONResponse(status_code=500, content={"error": "写入 system.yaml 失败"})


@app.get("/api/config/export")
async def config_export() -> JSONResponse:
    """导出当前 system.yaml 为 JSON（供用户下载备份）。"""
    config = _load_system_yaml()
    if not config:
        return JSONResponse(status_code=404, content={"error": "system.yaml 不存在"})

    return JSONResponse(
        content=config,
        headers={"Content-Disposition": "attachment; filename=zen70-config-export.json"},
    )


@app.post("/api/config/import")
async def config_import(file: UploadFile) -> dict[str, Any]:
    """
    导入配置 JSON 文件并应用到 system.yaml。

    支持从其他部署环境导出的配置一键导入。
    """
    if not file.filename or not file.filename.endswith(".json"):
        return JSONResponse(status_code=400, content={"error": "仅支持 .json 文件"})

    # 文件大小限制：1 MB，防止超大 JSON 导致内存耗尽或 DoS。
    # UploadFile.read() 不原生限制大小，必须显式检查。
    _MAX_IMPORT_BYTES = 1 * 1024 * 1024  # 1 MB
    content = await file.read(_MAX_IMPORT_BYTES + 1)
    if len(content) > _MAX_IMPORT_BYTES:
        return JSONResponse(status_code=413, content={"error": "配置文件过大，最大允许 1 MB"})

    try:
        imported = json.loads(content.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        return JSONResponse(status_code=400, content={"error": f"JSON 解析失败: {e}"})

    if not isinstance(imported, dict):
        return JSONResponse(status_code=400, content={"error": "配置文件必须是 JSON 对象"})

    # 安全校验：必须有 config_version 或 version 字段
    if "config_version" not in imported and "version" not in imported:
        return JSONResponse(status_code=400, content={"error": "无效的配置文件（缺少 version 字段）"})

    # 合并导入（非覆盖），保留本地已有的不在导入文件中的字段
    existing = _load_system_yaml()
    if existing:
        _deep_update(existing, imported)
        merged = existing
    else:
        merged = imported

    if _save_system_yaml(merged):
        return {"status": "ok", "message": "配置已导入并合并保存"}
    return JSONResponse(status_code=500, content={"error": "写入 system.yaml 失败"})


# ===========================================================================
# 硬件扫描 /api/scan/hardware
# ===========================================================================


@app.get("/api/scan/hardware")
async def scan_hardware() -> dict[str, Any]:
    """
    扫描主机硬件：磁盘、GPU、内存。

    前端 Step 2 Tab 3 用此 API 展示硬件卡片。
    用户可将扫描到的磁盘绑定到 sentinel.mount_container_map。
    """
    result: dict[str, Any] = {"disks": [], "gpu": None, "ram_mb": 0}

    # RAM
    ram_mb, _ = _detect_ram()
    result["ram_mb"] = ram_mb

    # 磁盘扫描
    if platform.system() == "Linux":
        try:
            proc = await asyncio.create_subprocess_exec(
                "lsblk",
                "-J",
                "-o",
                "NAME,SIZE,TYPE,MOUNTPOINT,FSTYPE",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=10)
            if proc.returncode == 0:
                data = json.loads(stdout.decode("utf-8", errors="replace"))
                for device in data.get("blockdevices", []):
                    if device.get("type") in ("disk", "part"):
                        result["disks"].append(
                            {
                                "name": device.get("name", ""),
                                "size": device.get("size", ""),
                                "type": device.get("type", ""),
                                "mountpoint": device.get("mountpoint", ""),
                                "fstype": device.get("fstype", ""),
                            }
                        )
        except (FileNotFoundError, TimeoutError, json.JSONDecodeError):
            pass
    elif platform.system() == "Windows":
        try:
            proc = await asyncio.create_subprocess_exec(
                "powershell",
                "-NoProfile",
                "-Command",
                "Get-PhysicalDisk | Select-Object FriendlyName,Size,MediaType | ConvertTo-Json",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=15)
            if proc.returncode == 0:
                raw = stdout.decode("utf-8", errors="replace").strip()
                if raw:
                    disks_data = json.loads(raw)
                    if isinstance(disks_data, dict):
                        disks_data = [disks_data]
                    for disk in disks_data:
                        size_bytes = disk.get("Size", 0)
                        size_gb = f"{size_bytes / (1024 ** 3):.0f} GB" if size_bytes else "未知"
                        result["disks"].append(
                            {
                                "name": disk.get("FriendlyName", "未知磁盘"),
                                "size": size_gb,
                                "type": disk.get("MediaType", ""),
                                "mountpoint": "",
                                "fstype": "",
                            }
                        )
        except (FileNotFoundError, TimeoutError, json.JSONDecodeError):
            pass

    # GPU 扫描
    try:
        proc = await asyncio.create_subprocess_exec(
            "nvidia-smi",
            "--query-gpu=name,memory.total",
            "--format=csv,noheader,nounits",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=10)
        if proc.returncode == 0:
            gpu_line = stdout.decode("utf-8", errors="replace").strip()
            if gpu_line:
                parts = [p.strip() for p in gpu_line.split(",")]
                result["gpu"] = {
                    "name": parts[0] if parts else "未知 GPU",
                    "vram_mb": int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else 0,
                }
    except (FileNotFoundError, asyncio.TimeoutError):
        pass

    return result


# ===========================================================================
# /api/status — 增强版：返回容器状态 + 部署模式检测
# ===========================================================================


@app.get("/api/status")
async def get_status() -> dict[str, Any]:
    """
    检测当前部署状态。

    前端据此判断显示模式：
    - deployed=false → 首次安装（完整三步向导）
    - deployed=true  → 变更模式（跳过 Step 1，直接进 Step 2）
    """
    result: dict[str, Any] = {
        "deployed": False,
        "docker_available": False,
        "compose_exists": DOCKER_COMPOSE_FILE.exists(),
        "env_exists": ENV_FILE.exists(),
        "system_yaml_exists": SYSTEM_YAML.exists(),
        "containers_running": 0,
        "containers_total": 0,
        "services": [],
    }

    try:
        proc = await asyncio.create_subprocess_exec(
            "docker",
            "ps",
            "-a",
            "--filter",
            f"label=com.docker.compose.project={COMPOSE_PROJECT_NAME}",
            "--format",
            "{{.Names}}\t{{.Status}}",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=10)
        result["docker_available"] = True

        if proc.returncode == 0 and stdout:
            decoded = stdout.decode("utf-8", errors="replace").strip()
            if decoded:
                lines = [line.strip() for line in decoded.splitlines() if line.strip()]
                result["containers_total"] = len(lines)
                for line in lines:
                    parts = line.split("\t", 1)
                    name = parts[0] if parts else ""
                    status = parts[1] if len(parts) > 1 else ""
                    is_up = "up" in status.lower()
                    if is_up:
                        result["containers_running"] += 1
                    result["services"].append(
                        {
                            "name": name,
                            "status": status,
                            "running": is_up,
                        }
                    )
                # 有运行中的容器 = 已部署
                if result["containers_running"] > 0:
                    result["deployed"] = True
    except (asyncio.TimeoutError, FileNotFoundError, OSError) as exc:
        logger.warning("Docker 探测失败: %s: %s", type(exc).__name__, exc)

    return result


# ===========================================================================
# Step 3: 部署 /api/deploy (SSE)
# ===========================================================================


@app.get("/api/deploy")
async def deploy() -> StreamingResponse:
    """
    SSE 流式部署管道。

    流程：
      [PHASE:0] 配置编译（compiler.py —— IaC 唯一管道）
      [PHASE:1] 基础设施部署（bootstrap.py + docker compose up）
      [PHASE:2] 健康检查（gateway /health 探针）
      [PHASE:DONE] 完成

    IaC 合规：不直接操作 .env 或 docker-compose.yml，
             全部由 compiler → bootstrap 管道完成。

    并发安全：全局互斥锁保证同时只有一个部署进程。
    """

    async def _sse_generator():
        global _deploy_active  # noqa: PLW0603

        # 互斥锁：严禁并发部署（前端双击防抖 + 后端双保险）
        if _deploy_active:
            yield "data: [错误] 已有部署任务正在执行，请等待完成\n\n"
            yield "data: [EOF] Process completed with exit code 1\n\n"
            return

        async with _get_deploy_lock():
            _deploy_active = True
            try:
                async for chunk in _deploy_pipeline():
                    yield chunk
            finally:
                _deploy_active = False

    return StreamingResponse(
        _sse_generator(),
        media_type="text/event-stream",
        headers=_SSE_HEADERS,
    )


async def _deploy_pipeline():
    """部署管道核心逻辑（由 deploy() 的互斥锁保护）。"""
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"

    # ━━━━━━━━━━ PHASE 0: 配置编译 ━━━━━━━━━━
    yield "data: [PHASE:0] ⚙️ 配置编译阶段\n\n"

    if not SYSTEM_YAML.exists():
        yield "data: [错误] system.yaml 不存在，无法编译\n\n"
        yield "data: [EOF] Process completed with exit code 1\n\n"
        return

    # 调用 compiler.py（含自动迁移 + lint + policy + 渲染）
    # 必须传入 system.yaml 路径参数，否则编译器会找不到配置文件
    yield f"data: [编译器] 执行 {COMPILER_SCRIPT.name}...\n\n"
    try:
        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            str(COMPILER_SCRIPT),
            str(SYSTEM_YAML),
            cwd=str(ROOT_DIR),
            env=env,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        while True:
            line = await proc.stdout.readline()
            if not line:
                break
            decoded = line.decode("utf-8", errors="replace").strip()
            if decoded:
                yield f"data: [编译器] {decoded}\n\n"

        await proc.wait()
        if proc.returncode != 0:
            yield f"data: [错误] 编译器退出码 {proc.returncode}\n\n"
            yield f"data: [EOF] Process completed with exit code {proc.returncode}\n\n"
            return
        yield "data: [编译器] ✅ 编译完成\n\n"
    except OSError as e:
        yield f"data: [错误] 编译器启动失败: {e}\n\n"
        yield "data: [EOF] Process completed with exit code 1\n\n"
        return

    # ━━━━━━━━━━ PHASE 1: 基础设施部署 ━━━━━━━━━━
    yield "data: [PHASE:1] 🚀 基础设施部署阶段\n\n"

    # 从 system.yaml 读取用户选择的部署平台
    deploy_platform = "auto"
    try:
        import yaml as _yaml
        with open(str(SYSTEM_YAML), encoding="utf-8") as _f:
            _sys_cfg = _yaml.safe_load(_f) or {}
        deploy_platform = (_sys_cfg.get("deployment") or {}).get("platform", "auto")
    except (OSError, ValueError, KeyError) as _e:
        yield f"data: [点火引擎] ⚠️ 读取平台配置失败({_e})，使用自动检测\n\n"

    # P1.5: 跳过预检/拉取（已由 installer Step 1-2 完成）
    boot_cmd = [
        sys.executable, str(BOOTSTRAP_SCRIPT),
        "--skip-pull", "--skip-mounts",
        "--platform", deploy_platform,
    ]
    yield f"data: [点火引擎] 启动 {BOOTSTRAP_SCRIPT.name} (平台: {deploy_platform})...\n\n"

    # 法典 §1.3: 点火失败自动重试 1 次
    max_attempts = 2
    boot_success = False
    boot_rc = 1

    for attempt in range(1, max_attempts + 1):
        if attempt > 1:
            yield f"data: [点火引擎] 🔄 重试 ({attempt}/{max_attempts})...\n\n"
            await asyncio.sleep(3)

        try:
            proc = await asyncio.create_subprocess_exec(
                *boot_cmd,
                cwd=str(ROOT_DIR),
                env=env,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
            )
            while True:
                line = await proc.stdout.readline()
                if not line:
                    break
                decoded = line.decode("utf-8", errors="replace").strip()
                if decoded:
                    yield f"data: {decoded}\n\n"

            await proc.wait()
            boot_rc = proc.returncode or 1

            if proc.returncode == 0:
                boot_success = True
                boot_rc = 0
                break
            yield f"data: [点火引擎] ⚠️ 退出码 {proc.returncode}\n\n"
        except OSError as e:
            yield f"data: [点火引擎] ❌ 启动失败: {e}\n\n"

    if not boot_success:
        yield f"data: [点火引擎] ❌ 经 {max_attempts} 次尝试仍失败\n\n"
        yield f"data: [EOF] Process completed with exit code {boot_rc}\n\n"
        return

    yield "data: [点火引擎] ✅ 执行完毕\n\n"

    # ━━━━━━━━━━ PHASE 2: 健康检查 ━━━━━━━━━━
    yield "data: [PHASE:2] 🏥 服务健康检查\n\n"

    # P1.3: 改用 docker inspect 获取容器健康状态，绕开 Windows NAT/WSL 网络玄学
    # 法典 §1.2: 容器名从 system.yaml IaC 事实来源读取
    gateway_container = "zen70-gateway"  # 兜底默认
    try:
        sys_cfg = _load_system_yaml()
        gateway_container = (sys_cfg.get("services") or {}).get("gateway", {}).get("container_name", "zen70-gateway")
    except Exception:
        pass
    health_ok = False
    max_health = 15
    for i in range(1, max_health + 1):
        await asyncio.sleep(3)
        try:
            probe = await asyncio.create_subprocess_exec(
                "docker", "inspect",
                "--format", "{{.State.Health.Status}}",
                gateway_container,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            out, _ = await asyncio.wait_for(probe.communicate(), timeout=10)
            if probe.returncode == 0:
                status_text = out.decode("utf-8", errors="replace").strip()
                if status_text == "healthy":
                    yield f"data: [健康检查] ✅ 网关容器就绪 (status={status_text})\n\n"
                    health_ok = True
                    break
                yield f"data: [健康检查] 🔄 第 {i}/{max_health} 次检查 (status={status_text})…\n\n"
            else:
                yield f"data: [健康检查] 🔄 第 {i}/{max_health} 次检查（容器未就绪）…\n\n"
        except asyncio.TimeoutError:
            yield f"data: [健康检查] 🔄 第 {i}/{max_health} 次超时…\n\n"
        except OSError:
            yield f"data: [健康检查] 🔄 第 {i}/{max_health} 次连接失败…\n\n"

    if not health_ok:
        yield "data: [健康检查] ⚠️ 未通过，服务可能仍在启动中\n\n"

    # ━━━━━━━━━━ PHASE DONE ━━━━━━━━━━
    yield "data: [PHASE:DONE] ✅ 部署完成\n\n"
    yield f"data: [EOF] Process completed with exit code {boot_rc}\n\n"


# ===========================================================================
# 前端页面
# ===========================================================================


@app.get("/", response_class=HTMLResponse)
async def serve_ui() -> str:
    """提供前端 HTML 页面。"""
    if not FRONTEND_HTML.exists():
        return "<h1>安装器前端未找到</h1>"
    return FRONTEND_HTML.read_text(encoding="utf-8")


@app.get("/favicon.ico")
async def favicon() -> HTMLResponse:
    """消除浏览器自动请求 favicon 导致的 404 报错刷屏。"""
    return HTMLResponse(status_code=204, content="")
